### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ontheway16** [triton-inference-server/server#2166]
Hello, I am facing with this error with both image_client.py and grpc_image_client.py. 
What can be wrong in here ?   :
```
$ python grpc_image_client.py -u 192.168.1.26:32691 -m resnet50_netdef /home/user/k8s-cuda/server/qa/images/mug.jpg
/home/user/miniconda/envs/yolov4-triton/lib/python3.7/site-packages/tritongrpcclient/__init__.py:33: DeprecationWarning: The package `tritongrpcclient` is deprecated and will be removed in a future version. Please use instead `tritonclient.grpc`
  "`tritonclient.grpc`", DeprecationWarning)
/home/user/miniconda/envs/yolov4-triton/lib/python3.7/site-packages/tritongrpcclient/grpc_service_pb2.py:33: DeprecationWarning: The package `tritongrpcclient` is deprecated and will be removed in a future version. Please use instead `tritonclient.grpc.service_pb2`
  "`tritonclient.grpc.service_pb2`", DeprecationWarning)
/home/user/miniconda/envs/yolov4-triton/lib/python3.7/site-packages/tritongrpcclient/grpc_service_pb2_grpc.py:33: DeprecationWarning: The package `tritongrpcclient` is deprecated and will be removed in a future version. Please use instead `tritonclient.grpc.service_pb2_grpc`
  "`tritonclient.grpc.service_pb2_grpc`", DeprecationWarning)
/home/user/miniconda/envs/yolov4-triton/lib/python3.7/site-packages/tritongrpcclient/model_config_pb2.py:33: DeprecationWarning: The package `tritongrpcclient` is deprecated and will be removed in a future version. Please use instead `tritonclient.grpc.model_config_pb2`
  "`tritonclient.grpc.model_config_pb2`", DeprecationWarning)
Image '/home/user/k8s-cuda/server/qa/images/mug.jpg':
Traceback (most recent call last):
  File "grpc_image_client.py", line 413, in <module>
    postprocess(response, result_filenames[idx], FLAGS.batch_size)
  File "grpc_image_client.py", line 222, in postprocess
    print("    {} ({}) = {}".format(cls[0], cls[1], cls[2]))
IndexError: list index out of range
```
```
$ cat config.pbtxt 
name: "resnet50_netdef"
platform: "caffe2_netdef"
max_batch_size: 128
input [
   {
      name: "gpu_0/data"
      data_type: TYPE_FP32
      format: FORMAT_NCHW
      dims: [ 3, 224, 224 ]
   }
]
output [
   {
      name: "gpu_0/softmax"
      data_type: TYPE_FP32
      dims: [ 1000 ]
   }
]

**Comment by CoderHam** [comment]
The image_client.py and grpc_image_client.py assume the models are image classification models and contain the label files.
You are is missing the label file from the output in the model config.
```
label_filename: "resnet50_labels.txt"
```
