### ISSUE TITLE
Call to GRPC Inference API fails using generated java code

### ISSUE THREAD

**Issue by barelyreal** [triton-inference-server/server#2359]
**Description**
When calling the inference API using GRPC from a java/kotlin client generated with the `protoc` compiler, the call fails.  When calling using `curl`, the call succeeds.  Calling the metadata API with GRPC succeeds.

The model itself uses the ONNX runtime.  When calling the inference API, the following error is returned:

```
io.grpc.StatusException: INVALID_ARGUMENT: unexpected explicit tensor data for input tensor 'input_ids' for model 'distilmbert_onnx' of type 'INT64', expected datatype '<invalid>'
```

**Triton Information**
What version of Triton are you using?
20.11

Are you using the Triton container or did you build it yourself?
the prebuilt container

**To Reproduce**
Steps to reproduce the behavior.

1. generate java + kotlin client code using org.xolstice protobuf-maven-plugin, with these parameters:
```
<grpc.version>1.32.1</grpc.version>
<grpc.kotlin.version>0.2.1</grpc.kotlin.version>
<protobuf.version>3.11.4</protobuf.version>
```
2. Start triton server locally in docker with this command: `docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -v $PWD/lp_model_repository:/models triton tritonserver --model-repository=/models --strict-model-config=false --log-verbose=1`

3. Verify that calling the inference API using curl works correctly, like this:
`curl -XPOST localhost:8000/v2/models/distilmbert_onnx/infer --data '{"inputs": [ { "name":"input_ids", "datatype":"INT64", "shape":[1,6], "data":[[ 101, 15127, 11324, 10124, 42478, 102]] }, { "name":"attention_mask", "datatype":"INT64", "shape":[1,6],"data":[[1, 1, 1, 1, 1, 1]] } ]}' > test.out
`

4. Run tests that use the generated code to hit the server.  Retrieving metadata works, and returns the correct input names and types, but inference fails with the following error:
```
io.grpc.StatusException: INVALID_ARGUMENT: unexpected explicit tensor data for input tensor 'input_ids' for model 'distilmbert_onnx' of type 'INT64', expected datatype '<invalid>'
        at io.grpc.Status.asException(Status.java:549)
        at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:289)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

The test model uses the ONNX runtime, and the automatically detected config looks like this:

```
{
    "name": "distilmbert_onnx",
    "platform": "onnxruntime_onnx",
    "backend": "onnxruntime",
    "version_policy": {
        "latest": {
            "num_versions": 1
        }
    },
    "max_batch_size": 1,
    "input": [
        {
            "name": "attention_mask",
            "data_type": "TYPE_INT64",
            "dims": [
                -1
            ]
        },
        {
            "name": "input_ids",
            "data_type": "TYPE_INT64",
            "dims": [
                -1
            ]
        }
    ],
    "output": [
        {
            "name": "output_6",
            "data_type": "TYPE_FP32",
            "dims": [
                -1,
                768
            ]
        },
        {
            "name": "output_1",
            "data_type": "TYPE_FP32",
            "dims": [
                -1,
                768
            ]
        },
        {
            "name": "output_7",
            "data_type": "TYPE_FP32",
            "dims": [
                -1,
                768
            ]
        },
        {
            "name": "output_2",
            "data_type": "TYPE_FP32",
            "dims": [
                -1,
                768
            ]
        },
        {
            "name": "output_3",
            "data_type": "TYPE_FP32",
            "dims": [
                -1,
                768
            ]
        },
        {
            "name": "output_4",
            "data_type": "TYPE_FP32",
            "dims": [
                -1,
                768
            ]
        },
        {
            "name": "output_5",
            "data_type": "TYPE_FP32",
            "dims": [
                -1,
                768
            ]
        }
    ],
    "batch_input": [],
    "batch_output": [],
    "optimization": {
        "priority": "PRIORITY_DEFAULT",
        "input_pinned_memory": {
            "enable": true
        },
        "output_pinned_memory": {
            "enable": true
        }
    },
    "instance_group": [
        {
            "name": "distilmbert_onnx",
            "kind": "KIND_CPU",
            "count": 1,
            "gpus": [],
            "profile": []
        }
    ],
    "default_model_filename": "model.onnx",
    "cc_model_filenames": {},
    "metric_tags": {},
    "parameters": {},
    "model_warmup": []
}
```

**Expected behavior**
Expected behavior is that the call to inference works and a result is returned.

**Comment by barelyreal** [comment]
Maven code generation plugin definition looks like this:

```
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
                    <protocPlugins>
                        <protocPlugin>
                            <id>grpc-kotlin</id>
                            <groupId>io.grpc</groupId>
                            <artifactId>protoc-gen-grpc-kotlin</artifactId>
                            <version>${grpc.kotlin.version}</version>
                            <classifier>jdk7</classifier>
                            <mainClass>io.grpc.kotlin.generator.GeneratorRunner</mainClass>
                        </protocPlugin>
                    </protocPlugins>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

```

**Comment by barelyreal** [comment]
Kotlin test code looks like this:
```

package com.liveperson.ds.tritonclient

import kotlin.test.*
import inference.GRPCInferenceServiceGrpcKt
import inference.GrpcService
import io.grpc.ManagedChannelBuilder
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Test


class TritonClientTest {

    @Test
    fun `get metadata`(): Unit = runBlocking {
        val channel = ManagedChannelBuilder.forAddress("localhost", 8001).usePlaintext().build()
        val stub = GRPCInferenceServiceGrpcKt.GRPCInferenceServiceCoroutineStub(channel)
        val metadata = stub.modelMetadata(GrpcService.ModelMetadataRequest.newBuilder()
                .setName("distilmbert_onnx")
                .build())

        for (tensorMetadata in metadata.inputsList) {
            println("******* Input Tensor name: ${tensorMetadata.name}")
            println("******* Input Tensor type: ${tensorMetadata.datatype}")
        }
        channel.shutdownNow()
    }

    @Test
    fun `get inference`(): Unit = runBlocking {
        val channel = ManagedChannelBuilder.forAddress("localhost", 8001).usePlaintext().build()
        val stub = GRPCInferenceServiceGrpcKt.GRPCInferenceServiceCoroutineStub(channel)
        val inputIds = GrpcService.ModelInferRequest.InferInputTensor.newBuilder()
                .setName("input_ids")
                .addAllShape(listOf(1,6))
                .setContents(GrpcService.InferTensorContents.newBuilder()
                        .addAllInt64Contents(listOf(101, 15127, 11324, 10124, 42478, 102)))
                .build()

        val attentionMask = GrpcService.ModelInferRequest.InferInputTensor.newBuilder()
                .setName("attention_mask")
                .addAllShape(listOf(1,6))
                .setContents(GrpcService.InferTensorContents.newBuilder()
                        .addAllInt64Contents(listOf(1, 1, 1, 1, 1, 1)))
                .build()

        val request = GrpcService.ModelInferRequest.newBuilder()
                .addInputs(inputIds)
                .addInputs(attentionMask)
                .setModelName("distilmbert_onnx")
                .build()

        val result = stub.modelInfer(request)
        for (outputTensor in result.outputsList) {
            println("******* Tensor name: ${outputTensor.name}")
        }
        channel.shutdownNow()
    }
}

```

**Comment by deadeyegoodwin** [comment]
Were you able to resolve this issue? We have a grpc java example here that may be helpful: https://github.com/triton-inference-server/server/tree/master/src/clients/java

Closing, reopen if you have additional information.
