### ISSUE TITLE
When I set the concurrency increase, the service returns a data exception

### ISSUE THREAD

**Issue by ruilongzhang** [triton-inference-server/server#2370]
**Description**
ror e: Parse error at offset 115: Invalid value.]
Traceback (most recent call last):
  File "/app/workdir/task_script.py", line 45, in run
    event_info = main_logic(filter_structures, direction, raw_plate_no, data, input_img, seq_no, normal_line)
  File "/app/workdir/person_vehicle_monitoring/core/core_interface.py", line 248, in main_logic
    direction, plate_box)
  File "/app/workdir/person_vehicle_monitoring/core/core_interface.py", line 150, in vehicle_event
    result = task.get_result()
  File "/app/workdir/person_vehicle_monitoring/tools/httpclient.py", line 1263, in get_result
    return InferResult(response, self._verbose)
  File "/app/workdir/person_vehicle_monitoring/tools/httpclient.py", line 1550, in __init__
    self._result = json.loads(content)
rapidjson.JSONDecodeError: Parse error at offset 115: Invalid value.

**Triton Information**
Triton 20-7

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
Looks like you have a json parse error, but from the information you have provided there is no way to determine what you are trying to do, what code or scripts you are running, etc. You need to provide more precise repro instructions.
