### ISSUE TITLE
tritonclient.utils.InferenceServerException / StatusCode.UNAVAILABLE] / Request for unknown model / model is not found

### ISSUE THREAD

**Issue by karoly-hars** [triton-inference-server/server#2419]
**Description**
I am trying to serve a simple ResNet50 classification model with Triton Serving. The server docker container runs without any visisble warning after calling
```
docker run --gpus device=4  --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 --rm --net=host -v $(pwd)/to_deploy/:/models nvcr.io/nvidia/tritonserver:20.12-py3 tritonserver --model-repository=/models --strict-model-config=false
```
where the ```to_deploy``` folder has the following tree:
```
to_deploy/
└── cls_resnet50
    └── 1
        └── model.savedmodel
            ├── assets
            ├── saved_model.pb
            └── variables
                ├── variables.data-00000-of-00001
                └── variables.index

5 directories, 3 files
```
The end of the docker run call:
```
2021-01-14 15:08:05.618192: I tensorflow/cc/saved_model/loader.cc:251] Restoring SavedModel bundle.
2021-01-14 15:08:06.275936: I tensorflow/cc/saved_model/loader.cc:200] Running initialization op on SavedModel bundle at path: /models/cls_resnet50/1/model.savedmodel
2021-01-14 15:08:06.429215: I tensorflow/cc/saved_model/loader.cc:379] SavedModel load for tags { serve }; Status: success. Took 1096149 microseconds.
I0114 15:08:06.429458 1 model_repository_manager.cc:960] successfully loaded 'cls_resnet50' version 1
I0114 15:08:06.429828 1 server.cc:490] 
+-------------+-----------------------------------------------------------------+------+
| Backend     | Config                                                          | Path |
+-------------+-----------------------------------------------------------------+------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}   |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}   |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}   |
+-------------+-----------------------------------------------------------------+------+

I0114 15:08:06.429902 1 server.cc:533] 
+--------------+---------+--------+
| Model        | Version | Status |
+--------------+---------+--------+
| cls_resnet50 | 1       | READY  |
+--------------+---------+--------+

I0114 15:08:06.430108 1 tritonserver.cc:1620] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                              |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                             |
| server_version                   | 2.6.0                                                                                                                                              |
| server_extensions                | classification sequence model_repository schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /models                                                                                                                                            |
| model_control_mode               | MODE_NONE                                                                                                                                          |
| strict_model_config              | 0                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                          |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                           |
| min_supported_compute_capability | 6.0                                                                                                                                                |
| strict_readiness                 | 1                                                                                                                                                  |
| exit_timeout                     | 30                                                                                                                                                 |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+

I0114 15:08:06.433073 1 grpc_server.cc:3979] Started GRPCInferenceService at 0.0.0.0:8001
I0114 15:08:06.433516 1 http_server.cc:2717] Started HTTPService at 0.0.0.0:8000
I0114 15:08:06.475208 1 http_server.cc:2736] Started Metrics Service at 0.0.0.0:8002
2021-01-14 15:08:29.127228: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-14 15:08:29.590460: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
```

I am using triton-client and gRPC to send requests with the following short dummy client script:
```
import numpy as np
import cv2
import tritonclient.grpc as grpc_client


MODEL_NAME = 'cls_resnet50'
URL = 'localhost:8001/v2/models/'
TRITON_CLIENT = grpc_client.InferenceServerClient(url=URL)


def get_bytes_img_request(batch=1):
    img = np.random.randint(low=0, high=255, size=(205, 400, 3), dtype=np.uint8)
    _, buffer = cv2.imencode('.jpg', img)
    input_bytes = np.array([buffer.tobytes()])
    input_bytes = np.tile(input_bytes, (batch, 1))
    bytes_input = grpc_client.InferInput('input_0', [batch, 1], 'BYTES')
    bytes_input.set_data_from_numpy(input_bytes)
    return [bytes_input]


def send_request(inputs):
    return TRITON_CLIENT.infer(model_name=MODEL_NAME, inputs=inputs)


inputs = get_bytes_img_request(batch=1)
output = send_request(inputs)
print(output.get_response())
```

I would expect an output response like this:
```
model_name: "cls_resnet50"
model_version: "1"
outputs {
  name: "confidences"
  datatype: "FP32"
  shape: 1
  shape: 1
}
raw_output_contents: "\235\243\001?"
```
but that is not always the case. If I run the client script 10 times, ~6-7 times out of 10 I get
```
Traceback (most recent call last):
  File "serving/triton_serving_client.py", line 26, in <module>
    output = send_request(inputs)
  File "serving/triton_serving_client.py", line 22, in send_request
    return TRITON_CLIENT.infer(model_name=MODEL_NAME, inputs=inputs)
  File "/home/user/.local/lib/python3.6/site-packages/tritonclient/grpc/__init__.py", line 1061, in infer
    raise_error_grpc(rpc_error)
  File "/home/user/.local/lib/python3.6/site-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] Request for unknown model: 'cls_resnet50' is not found
```

**Triton Information**
What version of Triton are you using?
```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 20.12 (build 18156940)
```

Are you using the Triton container or did you build it yourself?
I am using the most recent container.

**To Reproduce**
Try to serve a simple classification model with the 20.12 container, try to test from another window.

**Expected behavior**
The output response is printed without any exceptions.

**Comment by karoly-hars** [comment]
Resolved.

It seems like the root of the issue was the fact that I was running multiple tritonservers and they might have been using the same ports.
