### ISSUE TITLE
Build failing in python build script

### ISSUE THREAD

**Issue by philipp-schmidt** [triton-inference-server/server#2458]
**Description**

```
python3 build.py --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main --backend=custom --backend=ensemble --backend=tensorrt --backend=identity:main --backend=repeat:main --backend=square:main --backend=onnxruntime:main --backend=pytorch:main --backend=tensorflow1:main --backend=tensorflow2:main --backend=python:main --backend=dali:main
```

leads to the following error:

```
...
...
Step 95/95 : ENV NVIDIA_TRITON_SERVER_VERSION ${TRITON_CONTAINER_VERSION}
 ---> Running in 57f5ead825a1
Removing intermediate container 57f5ead825a1
 ---> 82a2dfa53b40
Successfully built 82a2dfa53b40
Successfully tagged tritonserver_buildbase:latest
ERROR:root:Traceback (most recent call last):
  File "build.py", line 994, in container_build
    client = docker.from_env(timeout=3600)
  File "/home/xxx/.local/lib/python3.6/site-packages/docker/client.py", line 101, in from_env
    **kwargs_from_env(**kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/docker/api/client.py", line 132, in __init__
    config_dict=self._general_configs, credstore_env=credstore_env,
TypeError: load_config() got an unexpected keyword argument 'config_dict'

error: container build failed
```

**Triton Information**
master branch 53a45b6d

**Comment by deadeyegoodwin** [comment]
That exception is from the "docker" pip package. Do you have a recent version of that package? If docker working correctly on your build system?

**Comment by philipp-schmidt** [comment]
### python --version
`Python 3.6.9`

### docker --version
`Docker version 20.10.1, build 831ebea`

### docker info
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 17
  Running: 14
  Paused: 0
  Stopped: 3
 Images: 661
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux nvidia runc io.containerd.runc.v2
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-62-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.82GiB
 Name: titan
 ID: ZESX:LHRF:D4AE:CUTX:6PIU:L4K5:QX7F:UUIM:PC5H:FSPX:CG4N:GQ2Q
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

### pip freeze | grep docker

Using a conda environment.
```
docker==4.4.1
docker-py==1.10.6
docker-pycreds==0.2.1
```

**Comment by philipp-schmidt** [comment]
Could conda / virtualenv be the problem here?

**Comment by philipp-schmidt** [comment]
`pip uninstall docker-py` fixed the issue. Having both packages installed crashes the build.
