### ISSUE TITLE
Start tensorrtserver on boot

### ISSUE THREAD

**Issue by HoangTienDuc** [triton-inference-server/server#2555]
i try to start on my python script by using systemd, but i got bellow error. 
ModuleNotFoundError: No module named 'tensorrtserver'
```
sub_loiter.service - Hello, world! service
   Loaded: loaded (/lib/systemd/system/sub_loiter.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-02-24 17:32:24 +07; 5s ago
  Process: 4352 ExecStart=/home/ducht/sub.sh (code=exited, status=1/FAILURE)
 Main PID: 4352 (code=exited, status=1/FAILURE)

Thg 2 24 17:32:24 x-team sub.sh[4352]: Traceback (most recent call last):
Thg 2 24 17:32:24 x-team sub.sh[4352]:   File "/home/ducht/Downloads/lpr-engine/main.py", line 1, in <module>
Thg 2 24 17:32:24 x-team sub.sh[4352]:     from utils.module_controler import Director, ConcreteFR
Thg 2 24 17:32:24 x-team sub.sh[4352]:   File "/home/ducht/Downloads/lpr-engine/utils/module_controler.py", line 6, in <module>
Thg 2 24 17:32:24 x-team sub.sh[4352]:     from utils.trtis import UserData
Thg 2 24 17:32:24 x-team sub.sh[4352]:   File "/home/ducht/Downloads/lpr-engine/utils/trtis.py", line 4, in <module>
Thg 2 24 17:32:24 x-team sub.sh[4352]:     from tensorrtserver.api import *
Thg 2 24 17:32:24 x-team sub.sh[4352]: ModuleNotFoundError: No module named 'tensorrtserver'
Thg 2 24 17:32:24 x-team systemd[1]: sub_loiter.service: Main process exited, code=exited, status=1/FAILURE
Thg 2 24 17:32:24 x-team systemd[1]: sub_loiter.service: Failed with result 'exit-code'.
```

my service file
```
[Unit]
Description=lpr project

[Service]
Type=simple
WorkingDirectory=/home/ducht/Downloads/lpr-engine
ExecStart=/home/ducht/miniconda3/bin/python3 -u /home/ducht/Downloads/lpr-engine/main.py
#ExecStart=/home/ducht/sub.sh

[Install]
WantedBy=multi-user.target
Alias=hello.service

```

**Comment by deadeyegoodwin** [comment]
Does the script work when you run it manually? This seems like a systemd question but I would guess that systemd is running your script as some user (possibly root) that doesn't have the tensorrtserver python module installed. Also from that naming is appears you are using a very old version of Triton.
