### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cancelled'

### ISSUE THREAD

**Issue by ThiagoMateo** [triton-inference-server/server#2598]
After inference an image done. i recieved bellow error. 
```
Exception ignored in: <bound method InferenceServerClient.__del__ of <tritonclient.grpc.InferenceServerClient object at 0x7f4b0c97e748>>
Traceback (most recent call last):
  File "/home/.local/lib/python3.6/site-packages/tritonclient/grpc/__init__.py", line 172, in __del__
  File "/home/.local/lib/python3.6/site-packages/tritonclient/grpc/__init__.py", line 180, in close
  File "/home/.local/lib/python3.6/site-packages/grpc/_channel.py", line 1444, in close
  File "/home/.local/lib/python3.6/site-packages/grpc/_channel.py", line 1428, in _close
AttributeError: 'NoneType' object has no attribute 'cancelled'
```

**Comment by deadeyegoodwin** [comment]
We can't really tell much from just that output. Can you provide a repro case so that we can see the failure?

**Comment by ThiagoMateo** [comment]
one more question. can you explain to me why i got below warning?
```
[TensorRT] WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors
```
