### ISSUE TITLE
tritonclient.utils.InferenceServerException: request specifies invalid shape for input 'input' for face_det_tensorrt_0_3_gpu0. Error details: model expected the shape of dimension 0 to be between 1 and 1 but received 2

### ISSUE THREAD

**Issue by ffffwyy** [triton-inference-server/server#2768]
**Description**
i write a sample to use triton_client.async_infer, and got this.
 i send 100 requests to server ,and after several cycles comes to this. All the input is the same as shape (1,1,240,320)

**Triton Information**
21.03

Are you using the Triton container or did you build it yourself?
yes
**To Reproduce**
Steps to reproduce the behavior.

erro log:
Traceback (most recent call last):
  File "hll_http_infer_client.py", line 214, in <module>
    result_t = out.get_result()
  File "/usr/local/conda/envs/triton/lib/python3.8/site-packages/tritonclient/http/__init__.py", line 1286, in get_result
    _raise_if_error(response)
  File "/usr/local/conda/envs/triton/lib/python3.8/site-packages/tritonclient/http/__init__.py", line 63, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: request specifies invalid shape for input 'input' for face_det_tensorrt_0_3_gpu0. Error details: model expected the shape of dimension 0 to be between 1 and 1 but received 2

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
tensorrt backend 
**Expected behavior**

**Comment by ffffwyy** [comment]
i use command line below to convert onnx to trt . why does it not accept dynamic batch inputs?

 trtexec --onnx=model.onnx --explicitBatch --minShapes=\'input\':1x1x240x32 --optShapes=\'input\':32x1x240x320 --maxShapes=\'input\’:128x1x240x320  --saveEngine=model.plan

**Comment by GuanLuo** [comment]
Did you specify the `max_batch_size` to a value > 1 in your model config?

**Comment by ffffwyy** [comment]
> Did you specify the `max_batch_size` to a value > 1 in your model config?

yes

name: "face_det_tensorrt"
platform: "tensorrt_plan"
max_batch_size: 128
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 1, 240, 320  ]
    
  }
 
]

output [
  {
    name: "bbox"
    data_type: TYPE_FP32
    dims: [ 13260, 4 ]
    
  },
  {
    name: "cls"
    data_type: TYPE_FP32
    dims: [  13260, 3 ]
    
  },
  {
    name: "pose"
    data_type: TYPE_FP32
    dims: [  13260, 3 ]
    
  }
]

instance_group [
    {
      count: 4
      kind: KIND_GPU
    }
]

dynamic_batching {
    preferred_batch_size: [ 8, 32, 64, 128 ]
    max_queue_delay_microseconds: 10000
}

**Comment by GuanLuo** [comment]
Can you share a minimal repro steps so we can investigate further?

**Comment by tanmayv25** [comment]
Closing because of inactivity. Please re-open with requested information if still seeing this issue.

**Comment by miyaxu0312** [comment]
@ffffwyy have you solved this problem? i met this problem too.
