### ISSUE TITLE
rapidjson.JSONDecodeError Error in Running Python Model

### ISSUE THREAD

**Issue by chandrameenamohan** [triton-inference-server/server#2968]
**Description**
I have build the triton server from the source. 
I have only built the python backend model as my I want to run python model. I have used this python example model: https://github.com/triton-inference-server/python_backend/tree/main/examples/add_sub. 
I am getting this error:
```
Traceback (most recent call last):
  File "client.py", line 31, in <module>
    outputs=outputs)
  File "/usr/local/lib/python3.6/site-packages/tritonclient/http/__init__.py", line 1114, in infer
    _raise_if_error(response)
  File "/usr/local/lib/python3.6/site-packages/tritonclient/http/__init__.py", line 61, in _raise_if_error
    error = _get_error(response)
  File "/usr/local/lib/python3.6/site-packages/tritonclient/http/__init__.py", line 50, in _get_error
    error_response = json.loads(response.read())
rapidjson.JSONDecodeError: Parse error at offset 0: The document is empty.
```

**Triton Information**
What version of Triton are you using?
21.04

Are you using the Triton container or did you build it yourself?
Yes. I build it myself.

**To Reproduce**
Steps to reproduce the behavior.
I did not use ubuntu to build it.  I have build it using Oracle Linux Server 7.9.
` ./build.py --cmake-dir=/home/server/build --build-dir=/tmp/citritonbuild --no-container-build --endpoint=http --endpoint=grpc --repo-tag=common:r21.04 --repo-tag=core:r21.04 --repo-tag=backend:r21.04 --repo-tag=thirdparty:r21.04 --backend=python:r21.04 --enable-logging --enable-stats --enable-tracing`

I tried to debug by adding logs in httpclient side:

```
Request uri v2/models/add_sub/infer
Body  b'{"id":"1","inputs":[{"name":"INPUT0","shape":[4],"datatype":"FP32","parameters":{"binary_data_size":16}},{"name":"INPUT1","shape":[4],"datatype":"FP32","parameters":{"binary_data_size":16}}],"outputs":[{"name":"OUTPUT0","parameters":{"binary_data":true}},{"name":"OUTPUT1","parameters":{"binary_data":true}}]}Q\xf5\x96>X6Y?\x1a\x08I?\x9e$\x15?z\x0b\x88>R\xba\t?\xb68h?\xb9]Y>'
POST /v2/models/add_sub/infer, headers {'Inference-Header-Content-Length': 309}
b'{"id":"1","inputs":[{"name":"INPUT0","shape":[4],"datatype":"FP32","parameters":{"binary_data_size":16}},{"name":"INPUT1","shape":[4],"datatype":"FP32","parameters":{"binary_data_size":16}}],"outputs":[{"name":"OUTPUT0","parameters":{"binary_data":true}},{"name":"OUTPUT1","parameters":{"binary_data":true}}]}Q\xf5\x96>X6Y?\x1a\x08I?\x9e$\x15?z\x0b\x88>R\xba\t?\xb68h?\xb9]Y>'
Headers {'Inference-Header-Content-Length': 309}
I0606 10:07:12.153984 65495 http_server.cc:1229] HTTP request: 2 /v2/models/add_sub/infer
<HTTPSocketPoolResponse status=405 headers={'content-length': '0', 'content-type': 'text/plain'}>
```
 
I see that client made the call to server for inference but not sure what happened afterwards. 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Python backend model: https://github.com/triton-inference-server/python_backend/tree/main/examples/add_sub

**Expected behavior**

**Comment by tanmayv25** [comment]
> `rapidjson.JSONDecodeError: Parse error at offset 0: The document is empty.`

This message suggests server returned an empty response. Can you share the verbose logs from the server side as well? This will provide more insights into what exactly is happening.

Just add `--log-verbose=1` option to the server CLI invocation.

**Comment by chandrameenamohan** [comment]
My logs look this:
```
bash-4.2# tritonserver --model-repository `pwd`/models --log-verbose=1
I0608 10:10:36.759729 54646 backend_factory.h:44] Create TritonBackendFactory
I0608 10:10:36.761658 54646 model_repository_manager.cc:770] AsyncLoad() 'add_sub'
I0608 10:10:36.761793 54646 model_repository_manager.cc:1009] TriggerNextAction() 'add_sub' version 1: 1
I0608 10:10:36.761807 54646 model_repository_manager.cc:1047] Load() 'add_sub' version 1
I0608 10:10:36.761818 54646 model_repository_manager.cc:1066] loading: add_sub:1
I0608 10:10:36.867775 54646 model_repository_manager.cc:1126] CreateInferenceBackend() 'add_sub' version 1
I0608 10:10:36.868253 54646 shared_library.cc:44] OpenLibraryHandle: /opt/tritonserver/backends/python/libtriton_python.so
I0608 10:10:36.869956 54646 python.cc:998] 'python' TRITONBACKEND API version: 1.0
I0608 10:10:36.870138 54646 python.cc:1018] backend configuration:
{}
I0608 10:10:36.870195 54646 python.cc:1085] shm-default-bytes=67108864,shm-growth-bytes=67108864,stub-timeout-seconds=4
I0608 10:10:36.870545 54646 python.cc:1124] TRITONBACKEND_ModelInitialize: add_sub (version 1)
I0608 10:10:36.873855 54646 model_config_utils.cc:1545] ModelConfig 64-bit fields:
I0608 10:10:36.873979 54646 model_config_utils.cc:1547]     ModelConfig::dynamic_batching::default_queue_policy::default_timeout_microseconds
I0608 10:10:36.874022 54646 model_config_utils.cc:1547]     ModelConfig::dynamic_batching::max_queue_delay_microseconds
I0608 10:10:36.874063 54646 model_config_utils.cc:1547]     ModelConfig::dynamic_batching::priority_queue_policy::value::default_timeout_microseconds
I0608 10:10:36.874108 54646 model_config_utils.cc:1547]     ModelConfig::ensemble_scheduling::step::model_version
I0608 10:10:36.874149 54646 model_config_utils.cc:1547]     ModelConfig::input::dims
I0608 10:10:36.874423 54646 model_config_utils.cc:1547]     ModelConfig::input::reshape::shape
I0608 10:10:36.874548 54646 model_config_utils.cc:1547]     ModelConfig::model_warmup::inputs::value::dims
I0608 10:10:36.874589 54646 model_config_utils.cc:1547]     ModelConfig::optimization::cuda::graph_spec::graph_lower_bound::input::value::dim
I0608 10:10:36.874704 54646 model_config_utils.cc:1547]     ModelConfig::optimization::cuda::graph_spec::input::value::dim
I0608 10:10:36.874752 54646 model_config_utils.cc:1547]     ModelConfig::output::dims
I0608 10:10:36.874872 54646 model_config_utils.cc:1547]     ModelConfig::output::reshape::shape
I0608 10:10:36.874890 54646 model_config_utils.cc:1547]     ModelConfig::sequence_batching::direct::max_queue_delay_microseconds
I0608 10:10:36.874921 54646 model_config_utils.cc:1547]     ModelConfig::sequence_batching::max_sequence_idle_microseconds
I0608 10:10:36.874960 54646 model_config_utils.cc:1547]     ModelConfig::sequence_batching::oldest::max_queue_delay_microseconds
I0608 10:10:36.875041 54646 model_config_utils.cc:1547]     ModelConfig::version_policy::specific::versions
I0608 10:10:36.875572 54646 python.cc:1173] TRITONBACKEND_ModelInstanceInitialize: add_sub_0 (CPU device 0)
I0608 10:10:36.875682 54646 backend_model_instance.cc:72] Creating instance add_sub_0 on CPU using artifact ''
I0608 10:10:36.875755 54646 python.cc:1193] TRITONBACKEND_ModelInstanceInitialize: instance initialization successful add_sub_0 (device 0)
I0608 10:10:36.882619 54646 python.cc:819] Preinit finished.
I0608 10:10:37.049393 54646 dynamic_batch_scheduler.cc:230] Starting dynamic-batch scheduler thread 0 at nice 5...
I0608 10:10:37.049635 54646 model_repository_manager.cc:1240] successfully loaded 'add_sub' version 1
I0608 10:10:37.049720 54646 model_repository_manager.cc:1009] TriggerNextAction() 'add_sub' version 1: 0
I0608 10:10:37.049773 54646 model_repository_manager.cc:1024] no next action, trigger OnComplete()
I0608 10:10:37.049857 54646 model_repository_manager.cc:615] VersionStates() 'add_sub'
I0608 10:10:37.049946 54646 model_repository_manager.cc:615] VersionStates() 'add_sub'
I0608 10:10:37.050080 54646 server.cc:504] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+
I0608 10:10:37.050106 54646 server.cc:543] 
+---------+-------------------------------------------------------+--------+
| Backend | Path                                                  | Config |
+---------+-------------------------------------------------------+--------+
| python  | /opt/tritonserver/backends/python/libtriton_python.so | {}     |
+---------+-------------------------------------------------------+--------+
I0608 10:10:37.050118 54646 model_repository_manager.cc:591] BackendStates()
I0608 10:10:37.050146 54646 server.cc:586] 
+---------+---------+--------+
| Model   | Version | Status |
+---------+---------+--------+
| add_sub | 1       | READY  |
+---------+---------+--------+
I0608 10:10:37.050301 54646 tritonserver.cc:1658] 
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                              |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                             |
| server_version                   | 2.9.0                                                                                                                              |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_mem |
|                                  | ory cuda_shared_memory binary_tensor_data statistics                                                                               |
| model_repository_path[0]         | /home/git/server/models                                                                                                            |
| model_control_mode               | MODE_NONE                                                                                                                          |
| strict_model_config              | 1                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                          |
| min_supported_compute_capability | 0.0                                                                                                                                |
| strict_readiness                 | 1                                                                                                                                  |
| exit_timeout                     | 30                                                                                                                                 |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
I0608 10:10:37.051579 54646 grpc_server.cc:225] Ready for RPC 'ServerLive', 0
I0608 10:10:37.051629 54646 grpc_server.cc:225] Ready for RPC 'ServerReady', 0
I0608 10:10:37.051665 54646 grpc_server.cc:225] Ready for RPC 'ModelReady', 0
I0608 10:10:37.051678 54646 grpc_server.cc:225] Ready for RPC 'ServerMetadata', 0
I0608 10:10:37.051727 54646 grpc_server.cc:225] Ready for RPC 'ModelMetadata', 0
I0608 10:10:37.051776 54646 grpc_server.cc:225] Ready for RPC 'ModelConfig', 0
I0608 10:10:37.051792 54646 grpc_server.cc:225] Ready for RPC 'ModelStatistics', 0
I0608 10:10:37.051848 54646 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryStatus', 0
I0608 10:10:37.051891 54646 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryRegister', 0
I0608 10:10:37.051950 54646 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryUnregister', 0
I0608 10:10:37.051985 54646 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryStatus', 0
I0608 10:10:37.051998 54646 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryRegister', 0
I0608 10:10:37.052010 54646 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryUnregister', 0
I0608 10:10:37.052035 54646 grpc_server.cc:225] Ready for RPC 'RepositoryIndex', 0
I0608 10:10:37.052069 54646 grpc_server.cc:225] Ready for RPC 'RepositoryModelLoad', 0
I0608 10:10:37.052084 54646 grpc_server.cc:225] Ready for RPC 'RepositoryModelUnload', 0
I0608 10:10:37.052115 54646 grpc_server.cc:416] Thread started for CommonHandler
I0608 10:10:37.052201 54646 grpc_server.cc:3117] New request handler for ModelInferHandler, 1
I0608 10:10:37.052218 54646 grpc_server.cc:2176] Thread started for ModelInferHandler
I0608 10:10:37.052355 54646 grpc_server.cc:3467] New request handler for ModelStreamInferHandler, 3
I0608 10:10:37.052412 54646 grpc_server.cc:2176] Thread started for ModelStreamInferHandler
I0608 10:10:37.052426 54646 grpc_server.cc:4028] Started GRPCInferenceService at 0.0.0.0:8001
I0608 10:10:37.052673 54646 http_server.cc:2761] Started HTTPService at 0.0.0.0:8000
I0608 10:10:41.090462 54646 http_server.cc:1229] HTTP request: 2 /v2/models/add_sub/infer
```

**Comment by tanmayv25** [comment]
Are these the complete log? Is the server still running after the client returned error?

**Comment by chandrameenamohan** [comment]
These are complete log:
```
I0609 04:49:09.964151 25 grpc_server.cc:2176] Thread started for ModelStreamInferHandler
I0609 04:49:09.964437 25 grpc_server.cc:4028] Started GRPCInferenceService at 0.0.0.0:8001
I0609 04:49:09.966191 25 http_server.cc:2761] Started HTTPService at 0.0.0.0:8000
I0609 04:49:52.786659 25 http_server.cc:1229] HTTP request: 2 /v2/models/add_sub/infer
I0609 04:50:00.252040 25 http_server.cc:1229] HTTP request: 2 /v2/models/add_sub/infer
I0609 04:50:09.596586 25 http_server.cc:1229] HTTP request: 2 /v2/models/add_sub/infer
```

I made 3 calls; Server is running;

**Comment by tanmayv25** [comment]
We don't officially support **Oracle Linux Server 7.9**. We do have sufficient testing on Ubuntu 20.04 for your use-case. 

Anyways, I will file a ticket with our dev team to look further into the issue.

**Comment by chandrameenamohan** [comment]
I figured it out. It was because of RE2.
I was using Version : 20160401 of RE2.
I have rebuilt it from the source: https://github.com/google/re2/. It worked for me.

**Comment by dongteng** [comment]
> I figured it out. It was because of RE2. I was using Version : 20160401 of RE2. I have rebuilt it from the source: https://github.com/google/re2/. It worked for me.

I want to know how to slove it with re2? Hope your reply. Thanks!
