### ISSUE TITLE
is_server_live and is_server_ready results in connection reset when tritonserver crash

### ISSUE THREAD

**Issue by Han-Huaqiao** [triton-inference-server/server#3086]
**Description**
I used grpcclient.InferenceServerClient to get triton_client
```python
   triton_client = httpclient.InferenceServerClient(
       url=url, verbose=verbose)
```

Then, when tritonserver is running normally,  triton_client.is_server_live() and triton_client.is_server_ready() return Ture.
But,  I execute triton_client.is_server_live() and triton_client.is_server_ready() funtion when tritonserver crash, got
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 190, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socket3.py", line 450, in recv
    return self._sock.recv(*args)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cv_general_test.py", line 116, in min_resolution_test
    result = triton_client.infer(FLAGS.model_name, inputs, outputs=outputs)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 1097, in infer
    response = self._post(request_uri=request_uri,
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 296, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 260, in request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 298, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 170, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 203, in _read_headers
    raise HTTPConnectionClosed(
geventhttpclient.response.HTTPConnectionClosed: connection closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 190, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socket3.py", line 450, in recv
    return self._sock.recv(*args)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cv_general_test.py", line 564, in <module>
    min_resolution_test(images_data_list, images_bytes_list, images_path_list)        
  File "cv_general_test.py", line 120, in min_resolution_test
    print(triton_client.is_server_ready())
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 363, in is_server_ready
    response = self._get(request_uri=request_uri,
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 258, in _get
    response = self._client_stub.get(request_uri)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 266, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 260, in request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 298, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 170, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 203, in _read_headers
    raise HTTPConnectionClosed(
geventhttpclient.response.HTTPConnectionClosed: connection closed.
```
I refer to the [issue](https://github.com/triton-inference-server/server/issues/2725), but can not solve it.

**Triton Information**
triton version = 20.12

Using the NVIDIA Triton container.

**To Reproduce**
Steps to reproduce the behavior.

Not including config file since this behavior is not model-specific.

**Expected behavior**
is_server_live() and is_server_ready() should return False.

**Comment by dzier** [comment]
Can you reproduce this bug in the latest 21.06 container?

**Comment by tanmayv25** [comment]
Closing the issue because of inactivity. Please re-open if still an issue.
