### ISSUE TITLE
rapidjson.JSONDecodeError: Parse error at offset 0: Invalid value.

### ISSUE THREAD

**Issue by universewill** [triton-inference-server/server#3114]
client error :
```
Traceback (most recent call last):
  File "face_client.py", line 106, in <module>
    results = test_infer(model_name, image.numpy(), headers_dict)
  File "face_client.py", line 24, in test_infer
    headers=headers)
  File "/Users/gaoxianglu/miniconda3/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 1258, in infer
    _raise_if_error(response)
  File "/Users/gaoxianglu/miniconda3/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 62, in _raise_if_error
    error = _get_error(response)
  File "/Users/gaoxianglu/miniconda3/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 51, in _get_error
    error_response = json.loads(response.read())
rapidjson.JSONDecodeError: Parse error at offset 0: Invalid value.
```

How to solve this problem? The client is ok because it can get result from anther server on another machine successfully.
Besides, where to find the logs of server?

**Comment by deadeyegoodwin** [comment]
Server log is printed to stdout/stderr, so typically will be shown in the console where you launched the server.
Can you turn on verbose output in the client API, that will likely provide some additional information.
