### ISSUE TITLE
Triton spins on startup running in EGX

### ISSUE THREAD

**Issue by flawaetz** [triton-inference-server/server#3126]
**Description**
When attempting to launch triton on NVIDIA EGX the model server consumes 100% CPU and never finishes startup.

**Triton Information**
21.06

Are you using the Triton container or did you build it yourself?
Container 

**To Reproduce**
I'm running on an EGX instance with two A100 GPUs on Ubuntu 20.04 with docker-ce 20.10.7.   CUDA 11.2 with driver 460.73.01.  

After noticing my regular model repository was failing to launch I tried with the sample model repository provided by [fetch_model.sh](https://github.com/triton-inference-server/server/tree/main/docs/examples) which also exhibited the same behavior.  This is with or without the model configuration files present.

Container launch command:
`docker run -it --entrypoint /bin/bash --runtime nvidia nvcr.io/nvidia/tritonserver:21.06-py3`

Triton start command:
`tritonserver --log-verbose 1 --model-repository /opt/tritonserver/model_repository`

After the following output:
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/1516944/125985016-c259311e-78ae-4db6-89a4-90717f9bbce7.png">

the container just sits at 100% CPU indefinitely with no further output.  I straced the process and it looks like its busy mostly in userspace with some repeating system calls.

**Expected behavior**
Triton should finish starting.

**Comment by flawaetz** [comment]
A couple additional notes:

- The behavior is the same even if I point triton to an empty directory for its model repository.  `tritonserver` sits at 100% CPU indefinitely.  

- If I set `CUDA_VISIBLE_DEVICES=""` the server starts up immediately.

**Comment by deadeyegoodwin** [comment]
Do you encounter the same problem with earlier versions of Triton?

**Comment by flawaetz** [comment]
Yes, I cycled back as far as 21.02 and encountered the same issue.

**Comment by flawaetz** [comment]
I made a debug build of triton and captured the following while `tritonserver` was sitting at 100% CPU.


```
(gdb) info threads
  Id   Target Id                                         Frame
* 1    Thread 0x7fdcc5b63000 (LWP 424) "tritonserver"    0x00007fdcc18e5bab in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
  2    Thread 0x7fdcc5b5a000 (LWP 428) "tritonserver"    0x00007fdcc65bf618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fdcc5b535a0, clockid=0, expected=0, 
    futex_word=0x55ec45330470) at ../sysdeps/nptl/futex-internal.h:320
  3    Thread 0x7fdcc5359000 (LWP 429) "tritonserver"    0x00007fdcc65bf618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fdcc53525a0, clockid=0, expected=0,
    futex_word=0x55ec45330470) at ../sysdeps/nptl/futex-internal.h:320
  4    Thread 0x7fdcc44cf000 (LWP 430) "cache_mgr_event" futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fdcc44b3180, clockid=<optimized out>, expected=0,
    futex_word=0x55ec4534c720) at ../sysdeps/nptl/futex-internal.h:320
  5    Thread 0x7fdcc3bcc000 (LWP 431) "tritonserver"    0x00007fdcc65bf618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fdcc3bc4ed0, clockid=0, expected=0,
    futex_word=0x55ec4533fc80) at ../sysdeps/nptl/futex-internal.h:320
  6    Thread 0x7fdcc33cb000 (LWP 432) "cache_mgr_main"  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fdcc33c1c70, clockid=<optimized out>, expected=0,
    futex_word=0x55ec4534f1e4) at ../sysdeps/nptl/futex-internal.h:320
  7    Thread 0x7fdcc1423000 (LWP 433) "tritonserver"    0x00007fdcc62e1c90 in accept4 (fd=21, addr=..., addr_len=0x7fdcc141c4b4, flags=524288) at ../sysdeps/unix/sysv/linux/accept4.c:32      
  8    Thread 0x7fdcc0c22000 (LWP 434) "tritonserver"    0x00007fdcc629e3bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fdcc0c1b380, rem=0x7fdcc0c1b380)  
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  9    Thread 0x7fdcadfff000 (LWP 435) "cuda-EvtHandlr"  0x00007fdcc62d3aff in __GI___poll (fds=0x7fdca4000b80, nfds=6, timeout=100) at ../sysdeps/unix/sysv/linux/poll.c:29
(gdb)

(gdb) thread apply all bt

Thread 9 (Thread 0x7fdcadfff000 (LWP 435)):
#0  0x00007fdcc62d3aff in __GI___poll (fds=0x7fdca4000b80, nfds=6, timeout=100) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fdcc1795a21 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fdcc174f72a in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fdcc178bd76 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fdcc65b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007fdcc62e0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fdcc0c22000 (LWP 434)):
#0  0x00007fdcc629e3bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fdcc0c1b380, rem=0x7fdcc0c1b380) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78    
#1  0x00007fdcc62a4047 in __GI___nanosleep (requested_time=<optimized out>, remaining=<optimized out>) at nanosleep.c:27
#2  0x00007fdcc6673403 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/include/c++/9/thread:378
#3  0x00007fdcc66b8ca7 in nvidia::inferenceserver::Metrics::<lambda()>::operator()(void) const (__closure=0x55ec45375f48) at /workspace/src/core/metrics.cc:364
#4  0x00007fdcc66bb897 in std::__invoke_impl<void, nvidia::inferenceserver::Metrics::InitializeDcgmMetrics()::<lambda()> >(std::__invoke_other, nvidia::inferenceserver::Metrics::<lambda()> &&) (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#5  0x00007fdcc66bb838 in std::__invoke<nvidia::inferenceserver::Metrics::InitializeDcgmMetrics()::<lambda()> >(nvidia::inferenceserver::Metrics::<lambda()> &&) (__fn=...) at /usr/include/c++/9/bits/invoke.h:95
#6  0x00007fdcc66bb7d6 in std::thread::_Invoker<std::tuple<nvidia::inferenceserver::Metrics::InitializeDcgmMetrics()::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55ec45375f48) at /usr/include/c++/9/thread:244
#7  0x00007fdcc66bb797 in std::thread::_Invoker<std::tuple<nvidia::inferenceserver::Metrics::InitializeDcgmMetrics()::<lambda()> > >::operator()(void) (this=0x55ec45375f48) at /usr/include/c++/9/thread:251
#8  0x00007fdcc66bb76c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<nvidia::inferenceserver::Metrics::InitializeDcgmMetrics()::<lambda()> > > >::_M_run(void) (this=0x55ec45375f40) at /usr/include/c++/9/thread:195
#9  0x00007fdcc64a1d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fdcc65b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007fdcc62e0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fdcc1423000 (LWP 433)):
#0  0x00007fdcc62e1c90 in accept4 (fd=21, addr=..., addr_len=0x7fdcc141c4b4, flags=524288) at ../sysdeps/unix/sysv/linux/accept4.c:32
#1  0x00007fdcc16ca3e3 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fdcc178bd76 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fdcc65b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007fdcc62e0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fdcc33cb000 (LWP 432)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fdcc33c1c70, clockid=<optimized out>, expected=0, futex_word=0x55ec4534f1e4) at ../sysdeps/nptl/futex-internal.h:320    
#1  __pthread_cond_wait_common (abstime=0x7fdcc33c1c70, clockid=<optimized out>, mutex=0x55ec45308be8, cond=0x55ec4534f1b8) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x55ec4534f1b8, mutex=0x55ec45308be8, abstime=0x7fdcc33c1c70) at pthread_cond_wait.c:656
#3  0x00007fdcc5e5e9a3 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#4  0x00007fdcc5d433c8 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#5  0x00007fdcc5d437fd in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#6  0x00007fdcc5e4f989 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#7  0x00007fdcc5e501d9 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
--Type <RET> for more, q to quit, c to continue without paging--c
#8  0x00007fdcc65b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007fdcc62e0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fdcc3bcc000 (LWP 431)):
#0  0x00007fdcc65bf618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fdcc3bc4ed0, clockid=0, expected=0, futex_word=0x55ec4533fc80) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55ec4533fc80, abstime=abstime@entry=0x7fdcc3bc4ed0, clockid=0) at sem_waitcommon.c:112
#2  0x00007fdcc65bf743 in __new_sem_wait_slow (sem=0x55ec4533fc80, abstime=0x7fdcc3bc4ed0, clockid=0) at sem_waitcommon.c:184
#3  0x00007fdcc3bf89ff in ?? () from /lib/x86_64-linux-gnu/libdcgmmodulenvswitch.so.2
#4  0x00007fdcc3beda91 in ?? () from /lib/x86_64-linux-gnu/libdcgmmodulenvswitch.so.2
#5  0x00007fdcc3c11fa9 in ?? () from /lib/x86_64-linux-gnu/libdcgmmodulenvswitch.so.2
#6  0x00007fdcc3c127f9 in ?? () from /lib/x86_64-linux-gnu/libdcgmmodulenvswitch.so.2
#7  0x00007fdcc65b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007fdcc62e0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fdcc44cf000 (LWP 430)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fdcc44b3180, clockid=<optimized out>, expected=0, futex_word=0x55ec4534c720) at ../sysdeps/nptl/futex-internal.h:320    
#1  __pthread_cond_wait_common (abstime=0x7fdcc44b3180, clockid=<optimized out>, mutex=0x55ec4534c6d0, cond=0x55ec4534c6f8) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x55ec4534c6f8, mutex=0x55ec4534c6d0, abstime=0x7fdcc44b3180) at pthread_cond_wait.c:656
#3  0x00007fdcc5e509b8 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#4  0x00007fdcc5d4b2f5 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#5  0x00007fdcc5d4c697 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#6  0x00007fdcc5e4f989 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#7  0x00007fdcc5e501d9 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#8  0x00007fdcc65b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007fdcc62e0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fdcc5359000 (LWP 429)):
#0  0x00007fdcc65bf618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fdcc53525a0, clockid=0, expected=0, futex_word=0x55ec45330470) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55ec45330470, abstime=abstime@entry=0x7fdcc53525a0, clockid=0) at sem_waitcommon.c:112
#2  0x00007fdcc65bf743 in __new_sem_wait_slow (sem=0x55ec45330470, abstime=0x7fdcc53525a0, clockid=0) at sem_waitcommon.c:184
#3  0x00007fdcc5e38c5f in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#4  0x00007fdcc5e39e72 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#5  0x00007fdcc604ae5d in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#6  0x00007fdcc65b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fdcc62e0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fdcc5b5a000 (LWP 428)):
#0  0x00007fdcc65bf618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fdcc5b535a0, clockid=0, expected=0, futex_word=0x55ec45330470) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55ec45330470, abstime=abstime@entry=0x7fdcc5b535a0, clockid=0) at sem_waitcommon.c:112
#2  0x00007fdcc65bf743 in __new_sem_wait_slow (sem=0x55ec45330470, abstime=0x7fdcc5b535a0, clockid=0) at sem_waitcommon.c:184
#3  0x00007fdcc5e38c5f in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#4  0x00007fdcc5e39e72 in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#5  0x00007fdcc604ae5d in ?? () from /lib/x86_64-linux-gnu/libdcgm.so.2
#6  0x00007fdcc65b5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fdcc62e0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fdcc5b63000 (LWP 424)):
#0  0x00007fdcc18e5bab in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007fdcc16f6877 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fdcc15f61db in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fdcc1677d72 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fdcc16313cf in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fdcc178f5ec in cuDevicePrimaryCtxRetain () from /lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007fdcc6a91e72 in __cudart813 () from /opt/tritonserver/bin/../lib/libtritonserver.so
#7  0x00007fdcc6a92107 in __cudart812 () from /opt/tritonserver/bin/../lib/libtritonserver.so
#8  0x00007fdcc6a959b8 in __cudart817 () from /opt/tritonserver/bin/../lib/libtritonserver.so
#9  0x00007fdcc6a8791c in __cudart991 () from /opt/tritonserver/bin/../lib/libtritonserver.so
#10 0x00007fdcc6a6a798 in __cudart717 () from /opt/tritonserver/bin/../lib/libtritonserver.so
#11 0x00007fdcc6aa6c36 in cudaHostAlloc () from /opt/tritonserver/bin/../lib/libtritonserver.so
#12 0x00007fdcc67261e4 in nvidia::inferenceserver::PinnedMemoryManager::Create (options=...) at /workspace/src/core/pinned_memory_manager.cc:232
#13 0x00007fdcc678964c in nvidia::inferenceserver::InferenceServer::Init (this=0x55ec4532f1d0) at /workspace/src/core/server.cc:158
#14 0x00007fdcc679c69f in TRITONSERVER_ServerNew (server=0x7ffc6a566ab8, options=0x55ec4532ec50) at /workspace/src/core/tritonserver.cc:1635
#15 0x000055ec4367f9c9 in main (argc=5, argv=0x7ffc6a566dc8) at /workspace/src/servers/main.cc:1523
(gdb)
```

**Comment by jbkyang-nvi** [comment]
@flawaetz it looks like you have found the issue.
