### ISSUE TITLE
Client Script Error

### ISSUE THREAD

**Issue by sarperkilic** [triton-inference-server/server#3260]
**Description**

Hello,

I successfully deploy the ONNX segmentation model to the server.

When I try to send an image request to the model by using Python image client script, I got an error.

Below, I share the error log.

Traceback (most recent call last):
  File "image_client_seg.py", line 413, in <module>
    outputs=outputs))
  File "/.local/lib/python3.6/site-packages/tritonclient/http/__init__.py", line 1255, in infer
    query_params=query_params)
  File "/.local/lib/python3.6/site-packages/tritonclient/http/__init__.py", line 306, in _post
    headers=headers)
  File "/.local/lib/python3.6/site-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/.local/lib/python3.6/site-packages/geventhttpclient/client.py", line 254, in request
    block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
  File "/.local/lib/python3.6/site-packages/geventhttpclient/response.py", line 298, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/.local/lib/python3.6/site-packages/geventhttpclient/response.py", line 170, in __init__
    self._read_headers()
  File "/.local/lib/python3.6/site-packages/geventhttpclient/response.py", line 190, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/.local/lib/python3.6/site-packages/gevent/_socketcommon.py", line 663, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: timed out

What should I do and why I got error like this?

Thanks for any help.

**Triton Information**
What version of Triton are you using?
2.12.0

Are you using the Triton container or did you build it yourself?
Build myself from source
tritonserver2.12.0-jetpack4.6

**To Reproduce**
Steps to reproduce the behavior.
I succesfully deployed the model and then send an image request to the model by using python image client script.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

name: "segmentation"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "ImageTensor:0"
    data_type: TYPE_UINT8
    dims: [1,1000,1000,3 ]
  }
]
output [
  {
    name: "SemanticPredictions:0"
    data_type: TYPE_INT32
    dims: [1,-1,-1]
  }
]

**Expected behavior**

Served models should get the inference request and produce prediction response.

**Comment by Tabrizian** [comment]
Are the Triton server ports exposed correctly? If you are using the HTTP client the port number is 8000 by default.

**Comment by audrey-siqueira** [comment]
I am having the same problem, even setting the ports correctly .

Did you find any solution?

**Comment by Tabrizian** [comment]
Looks like your request is timing out. Can you try increasing the timeout for your client? https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_infer_client.py#L130

**Comment by audrey-siqueira** [comment]
Hi Tabrizian, thank you for your answer.

I am using  image_client.py  and not simple_grpc_infer_client.py , so in image_client.py  there is no line **client_timeout=FLAGS.client_timeout**

My error output is this one, in line 441 of  **image_client.py**:

Traceback (most recent call last):
File "image_client.py", line 441, in
outputs=outputs))
File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/tritonclient/http/init.py", line 1255, in infer
query_params=query_params)
File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/tritonclient/http/init.py", line 306, in _post
headers=headers)
File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/client.py", line 272, in post
return self.request(METHOD_POST, request_uri, body=body, headers=headers)
File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/client.py", line 254, in request
block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/response.py", line 298, in init
super(HTTPSocketPoolResponse, self).init(sock, **kw)
File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/response.py", line 170, in init
self._read_headers()
File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/response.py", line 190, in _read_headers
data = self._sock.recv(self.block_size)
File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/gevent/_socketcommon.py", line 663, in recv
self._wait(self._read_event)
File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: timed out


Do you have any idea how to proceed?

**Comment by sarperkilic** [comment]
> Looks like your request is timing out. Can you try increasing the timeout for your client? https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_infer_client.py#L130

Hi,

I am using http client script and I cannot see client_timeout setting in http client script.

What do you suggest?

Thanks

**Comment by Tabrizian** [comment]
@audrey-siqueira  / @sarperkilic  Sorry I missed the notification for this thread. There is a timeout field in the httpclient as well. https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/http/__init__.py#L1174

In imageclient, when httpclient is created you can increase the timeout: https://github.com/triton-inference-server/client/blob/b3005f9db154247a4c792633e54f25f35ccadff0/src/python/examples/image_client.py#L317
