### ISSUE TITLE
unable to build custom image: unexpected keyword argument

### ISSUE THREAD

**Issue by mlizhardy** [triton-inference-server/server#3425]
I am trying to build a custom image as described here: https://github.com/triton-inference-server/server/blob/main/docs/compose.md

To test I am trying the very first example, i.e:

```
git clone https://github.com/triton-inference-server/server.git -b r21.08
cd server
python3 compose.py --backend tensorflow1 --backend tensorflow2 --repoagent checksum --enable-gpu
```

I get the following console output and error:

```
version 2.13.0
using container version 21.08
pulling container:nvcr.io/nvidia/tritonserver:21.08-py3
21.08-py3: Pulling from nvidia/tritonserver
Digest: sha256:6a1ef84e93327fef53ac11379fa4e53082c9e228de5db24e0abdfc5aff5676cf
Status: Image is up to date for nvcr.io/nvidia/tritonserver:21.08-py3
nvcr.io/nvidia/tritonserver:21.08-py3
Traceback (most recent call last):
  File "compose.py", line 342, in <module>
    argmap = create_argmap(images)
  File "compose.py", line 166, in create_argmap
    text=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

```

**Comment by CoderHam** [comment]
@mlizhardy can you retry with python 3.7 or higher?

**Comment by mlizhardy** [comment]
3.7 worked - thanks
