### ISSUE TITLE
Need help authoring Model configuration for Pytorch MNIST

### ISSUE THREAD

**Issue by rduser** [triton-inference-server/server#3541]
Hi I am trying to host my first model in triton.

- Ran the MNIST model from examples/main.py at https://github.com/pytorch/examples/tree/master/mnist
- Saved model to "mnist_cnn.pt"
- Converted saved model to torchscript format.
- Created the following config and followed the steps at https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md to create a model repository

When I to run inference I get error saying mnist model failed, bad request.

```
platform: "pytorch_libtorch"
max_batch_size: 0
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 28,28 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]
```
What am I missing?

**Comment by dzier** [comment]
Are you sure you want to set `max_batch_size` to 0? From the example script for mnist that you pointed out, it looks like it supports batching on the first dimension, meaning `max_batch_size` needs to be greater than or equal to 1.

https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#maximum-batch-size

**Comment by rduser** [comment]
let me try with the change and report back

**Comment by CoderHam** [comment]
> I tried following config but get error saying mnist model failed

Can you share the exact error you are seeing?

**Comment by rduser** [comment]
Here are my attempts



**Attempt 1**
From the Triton SDK docker,
` python /workspace/client/src/python/examples/image_client.py -v -m mnist -s NONE /models/image.jpg`

image8.jpg -> digit 8

Output
```
GET /v2/models/mnist, headers None
<HTTPSocketPoolResponse status=200 headers={'content-type': 'application/json', 'content-length': '194'}>
bytearray(b'{"name":"mnist","versions":["1"],"platform":"pytorch_libtorch","inputs":[{"name":"INPUT__0","datatype":"FP32","shape":[1,28,28]}],"outputs":[{"name":"output__0","datatype":"FP32","shape":[10]}]}')
GET /v2/models/mnist/config, headers None
<HTTPSocketPoolResponse status=200 headers={'content-type': 'application/json', 'content-length': '860'}>
bytearray(b'{"name":"mnist","platform":"pytorch_libtorch","backend":"pytorch","version_policy":{"latest":{"num_versions":1}},"max_batch_size":0,"input":[{"name":"INPUT__0","data_type":"TYPE_FP32","format":"FORMAT_NONE","dims":[1,28,28],"is_shape_tensor":false,"allow_ragged_batch":false}],"output":[{"name":"output__0","data_type":"TYPE_FP32","dims":[10],"label_filename":"","is_shape_tensor":false}],"batch_input":[],"batch_output":[],"optimization":{"priority":"PRIORITY_DEFAULT","input_pinned_memory":{"enable":true},"output_pinned_memory":{"enable":true},"gather_kernel_buffer_threshold":0,"eager_batching":false},"instance_group":[{"name":"mnist","kind":"KIND_CPU","count":1,"gpus":[],"secondary_devices":[],"profile":[],"passive":false,"host_policy":""}],"default_model_filename":"model.pt","cc_model_filenames":{},"metric_tags":{},"parameters":{},"model_warmup":[]}')
Traceback (most recent call last):
  File "/workspace/client/src/python/examples/image_client.py", line 345, in <module>
    max_batch_size, input_name, output_name, c, h, w, format, dtype = parse_model(
  File "/workspace/client/src/python/examples/image_client.py", line 121, in parse_model
    raise Exception("unexpected input format " +
Exception: unexpected input format FORMAT_NONE, expecting FORMAT_NCHW or FORMAT_NHWC
```

**Attempt 2:**
Make a Http PUT to 'http://127.0.0.1:8000/v2/models/mnist/infer' with the following payload

```
{
  "inputs": [
    {
      "name": "INPUT__0",
      "datatype": "FP32",
      "data": [ 0.47, 0.337, 0.953, 0.206, 0.194, 0.716, 0.335, 0.443, 0.454, 0.138, 0.737, 0.694, 0.43, 0.183, 0.738, 0.377, 0.317, 0.264, 0.021, 0.586, 0.792, 0.01, 0.079, 0.297, 0.647, 0.297, 0.244, 0.211, 0.493, 0.008, 0.516, 0.635, 0.65, 0.404, 0.172, 0.288, 0.125, 0.291, 0.111, 0.386, 0.913, 0.671, 0.431, 0.877, 0.045, 0.857, 0.29, 0.786, 0.36, 0.534, 0.194, 0.176, 0.992, 0.816, 0.992, 0.461, 0.258, 0.656, 0.559, 0.897, 0.472, 0.124, 0.95, 0.445, 0.623, 0.102, 0.044, 0.026, 0.011, 0.45, 0.252, 0.026, 0.152, 0.635, 0.673, 0.121, 0.579, 0.202, 0.252, 0.789, 0.007, 0.458, 0.852, 0.959, 0.814, 0.34, 0.643, 0.833, 0.412, 0.711, 0.03, 0.469, 0.732, 0.215, 0.914, 0.789, 0.721, 0.985, 0.254, 0.944, 0.813, 0.265, 0.775, 0.909, 0.282, 0.169, 0.024, 0.357, 0.143, 0.871, 0.882, 0.056, 0.404, 0.77, 0.89, 0.014, 0.272, 0.991, 0.631, 0.283, 0.459, 0.211, 0.614, 0.3, 0.421, 0.783, 0.294, 0.937, 0.721, 0.885, 0.399, 0.593, 0.948, 0.308, 0.977, 0.742, 0.682, 0.942, 0.677, 0.645, 0.316, 0.286, 0.691, 0.54, 0.829, 0.974, 0.065, 0.962, 0.325, 0.9, 0.517, 0.731, 0.354, 0.971, 0.485, 0.602, 0.651, 0.475, 0.489, 0.499, 0.875, 0.086, 0.636, 0.258, 0.472, 0.289, 0.108, 0.095, 0.793, 0.148, 0.332, 0.33, 0.314, 0.987, 0.966, 0.172, 0.52, 0.074, 0.472, 0.447, 0.718, 0.332, 0.612, 0.821, 0.368, 0.669, 0.239, 0.977, 0.823, 0.375, 0.091, 0.208, 0.454, 0.178, 0.77, 0.23, 0.651, 0.432, 0.069, 0.54, 0.866, 0.97, 0.168, 0.177, 0.568, 0.187, 0.417, 0.368, 0.005, 0.313, 0.081, 0.577, 0.003, 0.041, 0.781, 0.543, 0.474, 0.814, 0.89, 0.803, 0.05, 0.131, 0.272, 0.419, 0.057, 0.124, 0.876, 0.135, 0.217, 0.736, 0.522, 0.088, 0.005, 0.932, 0.581, 0.748, 0.164, 0.435, 0.253, 0.181, 0.251, 0.872, 0.972, 0.511, 0.293, 0.514, 0.205, 0.412, 0.397, 0.227, 0.756, 0.836, 0.542, 0.265, 0.49, 0.735, 0.698, 0.75, 0.121, 0.444, 0.311, 0.282, 0.151, 0.269, 0.791, 0.993, 0.572, 0.071, 0.46, 0.032, 0.38, 0.039, 0.561, 0.71, 0.552, 0.178, 0.159, 0.761, 0.125, 0.542, 0.919, 0.464, 0.738, 0.99, 0.981, 0.686, 0.546, 0.739, 0.442, 0.847, 0.051, 0.414, 0.314, 0.809, 0.87, 0.97, 0.721, 0.703, 0.72, 0.3, 0.942, 0.134, 0.953, 0.365, 0.847, 0.716, 0.276, 0.832, 0.714, 0.312, 0.576, 0.936, 0.624, 0.579, 0.525, 0.848, 0.544, 0.161, 0.288, 0.105, 0.447, 0.833, 0.628, 0.613, 0.982, 0.966, 0.725, 0.752, 0.84, 0.582, 0.457, 0.457, 0.041, 0.826, 0.6, 0.785, 0.511, 0.373, 0.143, 0.264, 0.41, 0.714, 0.026, 0.13, 0.271, 0.114, 0.789, 0.736, 0.284, 0.022, 0.426, 0.56, 0.414, 0.615, 0.853, 0.11, 0.506, 0.339, 0.383, 0.881, 0.992, 0.524, 0.992, 0.132, 0.855, 0.119, 0.896, 0.799, 0.979, 0.74, 0.337, 0.17, 0.017, 0.024, 0.695, 0.733, 0.807, 0.498, 0.342, 0.867, 0.177, 0.989, 0.468, 0.818, 0.156, 0.897, 0.043, 0.425, 0.973, 0.49, 0.28, 0.172, 0.99, 0.262, 0.273, 0.886, 0.722, 0.894, 0.275, 0.152, 0.219, 0.99, 0.757, 0.544, 0.686, 0.255, 0.543, 0.39, 0.92, 0.119, 0.303, 0.007, 0.997, 0.516, 0.705, 0.002, 0.056, 0.174, 0.976, 0.958, 0.076, 0.47, 0.826, 0.489, 0.46, 0.165, 0.18, 0.756, 0.752, 0.809, 0.011, 0.913, 0.223, 0.19, 0.648, 0.186, 0.232, 0.923, 0.132, 0.901, 0.354, 0.653, 0.505, 0.854, 0.187, 0.272, 0.175, 0.474, 0.557, 0.27, 0.829, 0.548, 0.918, 0.317, 0.076, 0.749, 0.164, 0.268, 0.084, 0.521, 0.075, 0.787, 0.638, 0.111, 0.108, 0.39, 0.784, 0.807, 0.868, 0.519, 0.77, 0.133, 0.042, 0.075, 0.604, 0.424, 0.965, 0.972, 0.302, 0.188, 0.99, 0.707, 0.198, 0.482, 0.98, 0.463, 0.995, 0.906, 0.114, 0.899, 0.022, 0.964, 0.84, 0.612, 0.826, 0.566, 0.015, 0.394, 0.745, 0.797, 0.488, 0.367, 0.606, 0.039, 0.5, 0.697, 0.506, 0.843, 0.713, 0.652, 0.784, 0.192, 0.965, 0.896, 0.53, 0.368, 0.589, 0.156, 0.131, 0.645, 0.395, 0.879, 0.693, 0.969, 0.497, 0.806, 0.293, 0.43, 0.25, 0.038, 0.409, 0.571, 0.227, 0.506, 0.7, 0.623, 0.101, 0.16, 0.982, 0.283, 0.957, 0.153, 0.193, 0.462, 0.116, 0.83, 0.999, 0.944, 0.081, 0.457, 0.977, 0.858, 0.263, 0.1, 0.402, 0.609, 0.674, 0.637, 0.542, 0.694, 0.403, 0.076, 0.593, 0.675, 0.244, 0.213, 0.965, 0.46, 0.195, 0.908, 0.267, 0.43, 0.175, 0.848, 0.688, 0.242, 0.686, 0.232, 0.853, 0.667, 0.807, 0.35, 0.349, 0.793, 0.061, 0.55, 0.307, 0.127, 0.104, 0.091, 0.949, 0.464, 0.618, 0.288, 0.88, 0.88, 0.56, 0.518, 0.218, 0.902, 0.864, 0.54, 0.748, 0.174, 0.19, 0.548, 0.684, 0.416, 0.412, 0.16, 0.924, 0.443, 0.784, 0.874, 0.887, 0.053, 0.728, 0.8, 0.614, 0.693, 0.906, 0.838, 0.356, 0.104, 0.959, 0.804, 0.812, 0.886, 0.968, 0.808, 0.683, 0.167, 0.014, 0.951, 0.803, 0.267, 0.601, 0.175, 0.603, 0.513, 0.866, 0.892, 0.715, 0.944, 0.168, 0.506, 0.68, 0.743, 0.401, 0.827, 0.152, 0.759, 0.904, 0.524, 0.996, 0.026, 0.184, 0.644, 0.215, 0.386, 0.736, 0.797, 0.448, 0.604, 0.477, 0.756, 0.429, 0.833, 0.072, 0.619, 0.452, 0.553, 0.197, 0.101, 0.827, 0.014, 0.124, 0.412, 0.936, 0.453, 0.124, 0.068, 0.485, 0.141, 0.655, 0.923, 0.263, 0.489, 0.955, 0.777, 0.084, 0.957, 0.96, 0.217, 0.777, 0.069, 0.444, 0.11, 0.467, 0.411, 0.077, 0.846, 0.672, 0.782, 0.374, 0.599, 0.562, 0.803, 0.697, 0.982, 0.902, 0.772, 0.708, 0.762, 0.262, 0.668, 0.312, 0.307, 0.949, 0.554, 0.494, 0.939, 0.878, 0.295, 0.536, 0.495, 0.593, 0.981, 0.325, 0.758, 0.571, 0.014, 0.945, 0.525, 0.376, 0.278, 0.397, 0.704, 0.766, 0.056, 0.361, 0.46, 0.792, 0.973, 0.875, 0.312, 0.249, 0.199, 0.955, 0.109, 0.757, 0.137, 0.161, 0.913, 0.917, 0.138, 0.968, 0.377, 0.246, 0.879, 0.006, 0.581, 0.479, 0.939, 0.411, 0.888, 0.827, 0.183, 0.386, 0.984, 0.271, 0.609, 0.541, 0.893, 0.193, 0.034, 0.147, 0.905, 0.42, 0.224, 0.246, 0.394, 0.026 ],
      "shape": [1, 28,28]
    }
  ]
}
```
Error:
BadRequest
{"error":"Unable to parse 'data': Shape does not match true shape of 'data' field"}

**Comment by CoderHam** [comment]
@rduser for the image client case it appears the model does not have the inputs format specified in the model config.
```
Exception: unexpected input format FORMAT_NONE, expecting FORMAT_NCHW or FORMAT_NHWC
```
This needs to be specified to use the image client as is. 

For the second error the number of elements is 783 but it should be 28*28*1 = 784. This is why the HTTP server responds with the shape error.

Please make the necessary fix and try again.

**Comment by rduser** [comment]
Great catch @CoderHam 

I made the change to 784 but then hit some problem coming from the model itself. 
So, then I rrecreated the torchscript model and restarted docker with the following config.

```
platform: "pytorch_libtorch"
max_batch_size: 0
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 1,1,28,28 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]

```
Then when I sent my request for **7**, the long elusive OK was here!!! 
```
{
  "inputs": [
    {
      "name": "INPUT__0",
      "datatype": "FP32",
      "data": [ -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 0.6450, 1.9305, 1.5996, 1.4978, 0.3395, 0.0340, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 2.4015, 2.8088, 2.8088, 2.8088, 2.8088, 2.6433, 2.0960, 2.0960, 2.0960, 2.0960, 2.0960, 2.0960, 2.0960, 2.0960, 1.7396, 0.2377, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 0.4286, 1.0268, 0.4922, 1.0268, 1.6505, 2.4651, 2.8088, 2.4396, 2.8088, 2.8088, 2.8088, 2.7578, 2.4906, 2.8088, 2.8088, 1.3577, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.2078, 0.4159, -0.2460, 0.4286, 0.4286, 0.4286, 0.3268, -0.1569, 2.5797, 2.8088, 0.9250, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 0.6322, 2.7960, 2.2360, -0.1951, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.1442, 2.5415, 2.8215, 0.6322, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 1.2177, 2.8088, 2.6051, 0.1358, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 0.3268, 2.7451, 2.8088, 0.3649, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 1.2686, 2.8088, 1.9560, -0.3606, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.3097, 2.1851, 2.7324, 0.3140, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 1.1795, 2.8088, 1.8923, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 0.5304, 2.7706, 2.6306, 0.3013, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.1824, 2.3887, 2.8088, 1.6887, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.3860, 2.1596, 2.8088, 2.3633, 0.0213, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 0.0595, 2.8088, 2.8088, 0.5559, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.0296, 2.4269, 2.8088, 1.0395, -0.4115, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 1.2686, 2.8088, 2.8088, 0.2377, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 0.3522, 2.6560, 2.8088, 2.8088, 0.2377, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 1.1159, 2.8088, 2.8088, 2.3633, 0.0849, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, 1.1159, 2.8088, 2.2105, -0.1951, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242, -0.4242],
      "shape": [1,1,28,28]
    }
  ]
}

OK
{"model_name":"mnist","model_version":"1","outputs":[{"name":"output__0","datatype":"FP32","shape":[1,10],"data":[-21.243730545043947,-23.028860092163087,-18.318389892578126,-20.073509216308595,-25.95116424560547,-27.99608612060547,-30.47653579711914,-5.960462772236497e-7,-22.443450927734376,-14.40283203125]}]}

```

I had been working on this problem in August, but then got stuck and lost some of my notes and scratch work. 

Thanks all for the help 🙏🏾🙏🏾🙏🏾

**Comment by thewq** [comment]
@rduser 
I try steps you mentioned above, but I meet a problem,
    ` failed to get power limit for GPU 0: Not Supported`
I think I have a wrong Environment Configuration，can you tell me your CUDA，pytorch version？
