### ISSUE TITLE
Triton HTTP python client library call `get_result()` on `InferAsyncRequest` object in different thread results in `greenlet .error`

### ISSUE THREAD

**Issue by yichong96** [triton-inference-server/server#3808]
I am trying out a producer-consumer pattern in python whereby the producer in the main thread sends asynchronous requests to Triton and puts the request into a `queue.Queue()` while the consumer thread consumes the result from this queue. 

While the other thread consumes from this queue, I am met with an error when I poll `InferAsyncRequest` object from the queue and call `get_result()` on it . The error shows `greenlet.error: cannot switch to a different thread`. 

I have managed to achieve such a pattern using gRPC bi-directional streaming but am curious whether it is possible to achieve such a pattern using the HTTP client library. 

Am also curious as to whether there are any benefits of using HTTP REST client library over gRPC since gRPC seems to be more optimised with its use of `protocol buffers` and `HTTP/2`. Especially so when the client batches data over to the server because the client using gRPC can send the inference requests over a single connection.

**Comment by dyastremsky** [comment]
Can you please provide the steps to reproduce your greenlet.error, including code and a sample model? Similar to the bug report template. 

As for HTTP vs gRPC, the performance should be similar. The best way to know would be to run perf_analyzer.

**Comment by yichong96** [comment]
Sorry, here is the code to reproduce the error.
```
import tritonclient.http as httpclient
from tritonclient.utils import InferenceServerException
from PIL import Image
import numpy as np
import time
import zmq
import argparse
import sys
import cv2
import queue
import threading

def preprocess(img, r_h, r_w):
  img = cv2.resize(img, (r_h, r_w), interpolation=cv2.INTER_CUBIC) # resize
  img = np.transpose(img, (2,0,1))    # C,H,W
  #img = np.expand_dims(img, axis=0)   
  img = img.astype(dtype="float32")
  return img

def test_infer(batched_image_data, input_name, output_name, dtype, model_name, request_id):
  inputs = []
  inputs = [httpclient.InferInput(input_name, batched_image_data.shape, dtype)]
  # Initialize the data
  inputs[0].set_data_from_numpy(batched_image_data)

  outputs = [httpclient.InferRequestedOutput(output_name)]
  return triton_client.async_infer(
    model_name,
    inputs,
    outputs=outputs,
    request_id=request_id)
  
def get_results(async_requests):
  count = 0
  while (count < args.num_images):
    data_item = async_requests.get()
    result = data_item.get_result() # error occurs here. 
    if type(data_item) == InferenceServerException:
      print(data_item)
    output_array = result.as_numpy("output_0")
    count += output_array.shape[0] # number of images batched
    print("Completed request: {}".format(result.get_response()["id"]), flush=True)

if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("--connect", type=str, required=True, help="socket subscriber subscribe to interface tcp://<connect_ip>:<tcp_port>")
  parser.add_argument("--num_images", type=int, required=True, help="number of images to expect being streamed over")
  parser.add_argument("--triton_url", type=str, default="localhost:8000", help="url to triton http server")
  parser.add_argument("--verbose", action="store_true", required=False, default=False, help="enable triton verbose")
  parser.add_argument("--model_name", required=True, help="model name on triton used to serve inference request")
  args = parser.parse_args()
  
  ctx = zmq.Context()
  s = ctx.socket(zmq.SUB)
  s.connect(args.connect)
  s.setsockopt(zmq.SUBSCRIBE, b'')
 
  count = 0
  request_id = 0
  async_requests = queue.Queue()
  thread = threading.Thread(target=get_results, args=(async_requests, ))
  thread.start()
  start_time = time.monotonic()
  try:
    triton_client = httpclient.InferenceServerClient(url=args.triton_url, concurrency = 20)
    while count < args.num_images:
      images = s.recv_pyobj()
      count += len(images)
      print("received: {} numer of images".format(count))
      processed = list(map(lambda x: preprocess(np.asarray(Image.open(x)), 128, 256), images))
      process_batch = np.stack(processed, axis = 0)
      async_requests.put(test_infer(batched_image_data=process_batch, input_name="input_0", output_name="output_0", dtype="FP32", model_name=args.model_name, request_id=str(request_id)))
      request_id += 1
    print("Time to send all request: {}".format(time.monotonic() - start_time))
  except Exception as e:
    print("Inference failed: " + str(e))
    sys.exit(1)
    
  print("Completed")
  thread.join()
  print('Took seconds: {} to complete all inferences'.format(time.monotonic() - start_time))
```

I am streaming in the images via a zmq socket. This is the error 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "httpRequest.py", line 37, in get_results
    result = data_item.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 1470, in get_result
    response = self._greenlet.get(block=block, timeout=timeout)
  File "src/gevent/greenlet.py", line 824, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 812, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
greenlet.error: cannot switch to a different thread
```

Thank you for your help !

**Comment by dyastremsky** [comment]
We'll investigate the error. To replicate it, we'll need sample models (with config files), the version of Triton you're using, whether you built the server or used the pre-built container, and the commands to run.

@GuanLuo, do you know if Triton and perf analyzer run on MacOS? Also, are there significant reasons to choose gRPC vs HTTP? My understanding was the performance was comparable, so let me know if that's not true.

**Comment by deadeyegoodwin** [comment]
I believe you are hitting a limitation of the greenlet library that the HTTP client is based on. @tanmayv25  please correct if I am wrong. You can look into greenlet to see if there is any way to work around this limitation. On our roadmap we also have a request to implement an asyncio version of the HTTP client that may be a solution for this issue, but we don't have any timeline for when that could be implemented.

**Comment by yichong96** [comment]
@deadeyegoodwin thanks for confirmation on this issue

**Comment by tanmayv25** [comment]
@yichong96  You are hitting the same problem as being described here: https://stackoverflow.com/questions/33531745/python-gevent-shared-queue-listener-process

In order to use this architecture seemlessly you must use greenlet friendly queue. 
```
import gevent
from gevent.queue import Queue
```
