### ISSUE TITLE
error when trying to allocate a region of cuda shared memory

### ISSUE THREAD

**Issue by benbarron** [triton-inference-server/server#3968]
**Description**
I am getting the following error when trying to allocate a region of cuda shared memory. 
```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    cudashm.create_shared_memory_region('test', 1024*1024, 0)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/utils/cuda_shared_memory/__init__.py", line 124, in create_shared_memory_region
    byref(cuda_shm_handle))))
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/utils/cuda_shared_memory/__init__.py", line 88, in _raise_if_error
    raise ex
tritonclient.utils.cuda_shared_memory.CudaSharedMemoryException: unable to create cuda shared memory handle
```

**Triton Information**
I am using triton version 2.13.0 on a jetson agx with jetpack 4.6.1 

I am using the following docker image
```
FROM nvcr.io/nvidia/l4t-base:r32.6.1

WORKDIR /root

RUN apt update && apt install -y ca-certificates \
    libglfw3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    build-essential \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libv4l-dev \
    libxvidcore-dev \
    libx264-dev \
    libgtk-3-dev \
    libatlas-base-dev \
    autoconf \
    automake \
    build-essential \
    libb64-dev \
    libre2-dev \
    libssl-dev \
    libtool \
    libboost-dev \
    python3-dev \
    python3-pip 

ARG TRITON_VERSION="2.13.0"
ARG JETPACK_VERSION="4.6"
RUN mkdir /opt/tritonserver && \
    cd /opt/tritonserver && \
    wget https://github.com/triton-inference-server/server/releases/download/v${TRITON_VERSION}/tritonserver${TRITON_VERSION}-jetpack${JETPACK_VERSION}.tgz && \
    tar -xf tritonserver${TRITON_VERSION}-jetpack${JETPACK_VERSION}.tgz && \
    rm -rf tritonserver${TRITON_VERSION}-jetpack${JETPACK_VERSION}.tgz

RUN pip3 install --upgrade wheel setuptools cython && pip3 install --upgrade grpcio-tools numpy future attrdict
RUN pip3 install --upgrade /opt/tritonserver/clients/python/tritonclient-${TRITON_VERSION}-py3-none-linux_aarch64.whl
```
**To Reproduce**
When I run the commands 
```
import tritonclient.utils.cuda_shared_memory as cudashm
cudashm.create_shared_memory_region('test', 1024*1024, 0)
```
I get the following error 
```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    cudashm.create_shared_memory_region('test', 1024*1024, 0)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/utils/cuda_shared_memory/__init__.py", line 124, in create_shared_memory_region
    byref(cuda_shm_handle))))
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/utils/cuda_shared_memory/__init__.py", line 88, in _raise_if_error
    raise ex
tritonclient.utils.cuda_shared_memory.CudaSharedMemoryException: unable to create cuda shared memory handle
```

**Comment by CoderHam** [comment]
@benbarron Cuda shared memory is not support on Jetson/ Jetpack.
