### ISSUE TITLE
tritonserver exited with coredump when using cuda graph optimization

### ISSUE THREAD

**Issue by wangchengdng** [triton-inference-server/server#4017]
**Description**
We have some TensorRT models that use cuda graph optimization. Our online models need to be updated regularly, but we found that the server will exit when the model is updated, and a coredump will be generated, and the server works fine without using cuda graph.
**Triton Information**
What version of Triton are you using?
22.02
Are you using the Triton container or did you build it yourself?
Using the container.
```
docker pull nvcr.io/nvidia/tritonserver:22.02-py3
```
**To Reproduce**
Step 1:
Prepare the model, the model directory structure is as follows
```
pdd_vrbd_model_ple_v3_time_noclip
├── 1
│   └── model.plan
├── config.pbtxt
└── mv.sh
```
The model configuration is as follows
```
platform: "tensorrt_plan"

instance_group [
  {
    count: 2
    kind: KIND_GPU
    gpus: [0]
  }
]

optimization{
   graph: {
       level : 1
   },
   eager_batching : 1,
   cuda: {
       graphs: 1,
       graph_spec: [
    {
        batch_size: 167
    }
    ]
       busy_wait_events:1,
       output_copy_stream: 1
   }
}
```
Step 2:
Start the server with the following command
```
./bin/tritonserver --grpc-port=8899  --model-repository=model_zoo  --model-control-mode=explicit  --strict-model-config=false --log-verbose=false
```
Step 3:
Use a script to update the model every 5 seconds
```
for ((i=1;i<=100000;i++));
do
    src=$(($i))
    dst=$(($i+1))
    cp -rf  $src $dst
    curl 127.0.0.1:8000/v2/repository/models/pdd_vrbd_model_ple_v3_time_noclip/load -X POST
    sleep 5
done
```
Step 4:
Use perfclient to request the server
```
./perf_client -m pdd_vrbd_model_ple_v3_time_noclip  -p3000 -t5 -b167 -v -u 127.0.0.1:8000
```

When the model is updated, the following error will be reported
```
E0307 03:51:14.842791 3164 logging.cc:43] 1: [cudaDriverHelpers.cpp::cudaEventRecordWithExternalEvent::135] Error Code 1: Cuda Driver (operation failed due to a previous error during capture)
E0307 03:51:14.842840 3164 logging.cc:43] 1: [checkMacros.cpp::catchCudaError::272] Error Code 1: Cuda Runtime (operation failed due to a previous error during capture)
E0307 03:51:14.842854 3164 tensorrt.cc:4996] unable to record CUDA graph for pdd_vrbd_model_ple_v3_time_noclip_0_0
E0307 03:51:14.842979 3164 tensorrt.cc:5004] unable to finish CUDA graph for pdd_vrbd_model_ple_v3_time_noclip_0_0: operation failed due to a previous error during capture
E0307 03:51:14.843961 3164 logging.cc:43] 1: [cudaDriverHelpers.cpp::cudaEventRecordWithExternalEvent::135] Error Code 1: Cuda Driver (operation failed due to a previous error during capture)
E0307 03:51:14.843984 3164 logging.cc:43] 1: [checkMacros.cpp::catchCudaError::272] Error Code 1: Cuda Runtime (operation failed due to a previous error during capture)
E0307 03:51:14.843998 3164 tensorrt.cc:4996] unable to record CUDA graph for pdd_vrbd_model_ple_v3_time_noclip_0_0
E0307 03:51:14.844072 3164 tensorrt.cc:5004] unable to finish CUDA graph for pdd_vrbd_model_ple_v3_time_noclip_0_0: operation failed due to a previous error during capture
I0307 03:51:14.844085 3164 tensorrt.cc:1409] Created instance pdd_vrbd_model_ple_v3_time_noclip_0_0 on GPU 0 with stream priority 0 and optimization profile default[0];
Signal (11) received.
```
The server will generate the following coredump
```
#0  0x00007f39578af2ba in nvidia::inferenceserver::PinnedMemoryManager::AllocInternal(void**, unsigned long, TRITONSERVER_memorytype_enum*, bool, nvidia::inferenceserver::PinnedMemoryManager::PinnedMemory*) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#1  0x00007f39578b05e1 in nvidia::inferenceserver::PinnedMemoryManager::Alloc(void**, unsigned long, TRITONSERVER_memorytype_enum*, bool) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#2  0x00007f39579f858d in TRITONBACKEND_MemoryManagerAllocate () from /opt/tritonserver/bin/../lib/libtritonserver.so
#3  0x00007f37f053ac2f in triton::backend::BackendOutputResponder::FlushPendingPinned(char const*, TRITONSERVER_memorytype_enum, long) () from /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so
#4  0x00007f37f053c274 in triton::backend::BackendOutputResponder::ProcessTensor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, TRITONSERVER_datatype_enum, std::vector<long, std::allocator<long> >&, char const*, TRITONSERVER_memorytype_enum, long) () from /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so
#5  0x00007f37f04d124f in triton::backend::tensorrt::ModelInstanceState::Run(TRITONBACKEND_Request**, unsigned int, unsigned long) () from /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so
#6  0x00007f37f04db0ce in triton::backend::tensorrt::ModelInstanceState::ProcessRequests(TRITONBACKEND_Request**, unsigned int) () from /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so
#7  0x00007f37f04dc156 in TRITONBACKEND_ModelInstanceExecute () from /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so
#8  0x00007f3957a0bf9a in nvidia::inferenceserver::TritonModelInstance::Execute(std::vector<TRITONBACKEND_Request*, std::allocator<TRITONBACKEND_Request*> >&) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#9  0x00007f3957a0c6b7 in nvidia::inferenceserver::TritonModelInstance::Schedule(std::vector<std::unique_ptr<nvidia::inferenceserver::InferenceRequest, std::default_delete<nvidia::inferenceserver::InferenceRequest> >, std::allocator<std::unique_ptr<nvidia::inferenceserver::InferenceRequest, std::default_delete<nvidia::inferenceserver::InferenceRequest> > > >&&, std::function<void ()> const&) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#10 0x00007f39578a41a1 in nvidia::inferenceserver::Payload::Execute(bool*) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#11 0x00007f3957a06527 in nvidia::inferenceserver::TritonModelInstance::TritonBackendThread::BackendThread(int, int) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#12 0x00007f3957258de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007f39576d5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x00007f3956f43163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
**Expected behavior**
We hope to use cuda graph to optimize inference speed
We hope that the model can be updated normally when using cuda graph

**Comment by rmccorm4** [comment]
Hi @wangchengdng, thanks for raising this issue.

Do you have a simple/minimal model that you can share for us to reproduce the issue? (the original model before conversion to TensorRT and the conversion steps you took to generate the TensorRT engine)

@tanmayv25 @GuanLuo any experience working with TRT engines making use of CUDA graphs?

**Comment by rmccorm4** [comment]
Model received - ticket 3530 / bug 3561162
