### ISSUE TITLE
Client Hung 

### ISSUE THREAD

**Issue by eanmikale** [triton-inference-server/server#4096]
When running the client the following line gets hung... Hardware Jetson Nano Jetpack 4.6 256GB Micro-SD WIFI 

./image_client -m densenet_onnx -c 3 -s INCEPTION /path/to/image

The server shot is below...

![Servershot1](https://user-images.githubusercontent.com/25436318/159754630-f2ac02d7-a3d6-4e12-ab09-c8b6fe25b2be.png)

Any assistance is appreciated.

**Comment by CoderHam** [comment]
@eanmikale can you use the --log-verbose=1 argument while running the server?

This will allow you to see the server logs and confirm that the server received the request. 

Which version of the Triton Jetson tar are you using for your experiments?

**Comment by eanmikale** [comment]
I tried with the flag you provided, and the C++ version of the image_client still hung. I tried the python version and got the following: 

python3 image_client.py -m inception-graphdef -s INCEPTION /home/infinit8enano2/server/docs/images/mug.jpg
Traceback (most recent call last):
  File "image_client.py", line 327, in <module>
    model_name=FLAGS.model_name, model_version=FLAGS.model_version)
  File "/home/infinite8nano2/archiconda3/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 502, in get_model_metadata
    query_params=query_params)
  File "/home/infinite8nano2/archiconda3/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 266, in _get
    response = self._client_stub.get(request_uri)
  File "/home/infinite8nano2/archiconda3/lib/python3.7/site-packages/geventhttpclient/client.py", line 266, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/home/infinite8nano2/archiconda3/lib/python3.7/site-packages/geventhttpclient/client.py", line 254, in request
    block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
  File "/home/infinite8nano2/archiconda3/lib/python3.7/site-packages/geventhttpclient/response.py", line 298, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/home/infinite8nano2/archiconda3/lib/python3.7/site-packages/geventhttpclient/response.py", line 170, in __init__
    self._read_headers()
  File "/home/infinite8nano2/archiconda3/lib/python3.7/site-packages/geventhttpclient/response.py", line 190, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/home/infinite8nano2/archiconda3/lib/python3.7/site-packages/gevent/_socketcommon.py", line 663, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: timed out

Here is the Triton Jetpack Tar file: [tritonserver2.19.0-jetpack4.6.1.tgz](https://github.com/triton-inference-server/server/releases/download/v2.19.0/tritonserver2.19.0-jetpack4.6.1.tgz).

The command times out, when running Python3 image_client.py. I can't get any verbose output from the C++ image_client at all when issuing command with server up. 

Note: Is it necessary to have a repository agent and path?

**Comment by CoderHam** [comment]
@eanmikale what command did you use to launch Triton server?

Can you confirm the instance of Triton server is running and accessible from where you run your client scripts. You can use curl for the same: 

```
curl -v localhost:8000/v2/health/ready
```

**Comment by eanmikale** [comment]
./tritonserver --repoagent-directory=/home/jetsonx/Downloads/qa/checksum_repository_agent/ --model-repository=/home/jetsonx/server/docs/examples/model_repository/ --backend-directory=/home/jetsonx/Downloads/backends/ --backend-config=onnxruntime,enable-global-threadpool=0 --backend-config=onnxruntime,intra_op_thread_count=0 --backend-config=onnxruntime,inter_op_thread_count=0 --log-verbose=1

The command returns: 

< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
 

Also, can anything be done regarding the inability to pull up the repository agent path? Thanks!

**Comment by eanmikale** [comment]
I didn't do anything different, but the image_client now runs successfully. Here is the command used: 
./image_client -m densenet_onnx -c 3 -s INCEPTION /home/jetsonx/Downloads/qa/images/mug.jpg 

However, this does not solve the "Repo agent path"? Assistance with this would still be appreciated. Do I need to open another issue? Thanks.

**Comment by eanmikale** [comment]
![AINetworkTests_i](https://user-images.githubusercontent.com/25436318/160301385-ab67dfa2-73bb-408a-becb-5341de47f62e.png)

**Comment by GuanLuo** [comment]
Repo agent is a optional feature for user to manipulate the model files (i.e. decryption) at different stages of the model lifecycle (see [doc](https://github.com/triton-inference-server/server/blob/main/docs/repository_agents.md) for detail), you don't need to specify it if your model doesn't use repo agent.

Closing the ticket as the original issue is resolved.
