### ISSUE TITLE
Build failure when building PyTorch CPU tritonserver container: /usr/bin/ld: cannot find -ltorch

### ISSUE THREAD

**Issue by andremoeller** [triton-inference-server/server#4333]
**Description**

I'm building a cpu-only PyTorch container with the following command, which results in a build failure:

```
python  build.py --cmake-dir=./build --build-dir=/tmp/tritonbuild \
      --enable-logging --enable-stats --enable-tracing --enable-metrics \
      --endpoint=http --endpoint=grpc --repo-tag=common:r22.02 --repo-tag=core:r22.02 \
      --repo-tag=backend:r22.02 --repo-tag=thirdparty:r22.02 \
      --backend=pytorch:r22.02 --repoagent=checksum:r22.02
```

The build fails with this error:
```
Cloning into 'pytorch'...
Error: No such container: pytorch_backend_ptlib
/usr/bin/ld: cannot find -ltorch
/usr/bin/ld: cannot find -ltorchvision
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/triton-pytorch-backend.dir/build.make:117: libtriton_pytorch.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:144: CMakeFiles/triton-pytorch-backend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Triton Information**

What version of Triton are you using?

I'm building version `r22.02`, so I've checked out branch r22.02. I'm on commit `5a903ec9a79915797fbb2cac67976c0a8b917387`.

I'm using Ubuntu 20.04.

Are you using the Triton container or did you build it yourself?

I'm building the Triton container using `build.py`

**To Reproduce**

```
python  build.py --cmake-dir=./build --build-dir=/tmp/tritonbuild \
      --enable-logging --enable-stats --enable-tracing --enable-metrics \
      --endpoint=http --endpoint=grpc --repo-tag=common:r22.02 --repo-tag=core:r22.02 \
      --repo-tag=backend:r22.02 --repo-tag=thirdparty:r22.02 \
      --backend=pytorch:r22.02 --repoagent=checksum:r22.02
```

**Expected behavior**

I expect the build to complete. Tips on how to debug this are appreciated. Thank you!

**Comment by CoderHam** [comment]
@andremoeller did you see an error logged saying that the pytorch container docker pull failed? The error log from the build looks incomplete.

**Comment by andremoeller** [comment]
@CoderHam 

Thanks for the response (and apologies about the late reply!)
This is the extended error message: it looks like the pull succeeded, and that torchvision and torch were copied from the pytorch container:

```
22.02-py3: Pulling from nvidia/pytorch
Digest: sha256:a66869fcfb7203ca6be9f793bc1f2dce946ed6569b728422db8503172542f574
Status: Image is up to date for nvcr.io/nvidia/pytorch:22.02-py3
nvcr.io/nvidia/pytorch:22.02-py3
docker rm pytorch_backend_ptlib || echo "error ignored..." || true
Error: No such container: pytorch_backend_ptlib
error ignored...
docker create --name pytorch_backend_ptlib nvcr.io/nvidia/pytorch:22.02-py3
[ 80%] Linking CXX static library libtritontableprinter.a
cd /tmp/tritonbuild/pytorch/build/_deps/repo-common-build && /usr/bin/cmake -P CMakeFiles/triton-common-table-printer.dir/cmake_clean_target.cmake
cd /tmp/tritonbuild/pytorch/build/_deps/repo-common-build && /usr/bin/cmake -E cmake_link_script CMakeFiles/triton-common-table-printer.dir/link.txt --verbose=0
make[2]: Leaving directory '/tmp/tritonbuild/pytorch/build'
[ 80%] Built target triton-common-table-printer
1d4a4fdec21b55e8109b40274db4fda8123766cc6629401dccb063fc2cb58135
/bin/sh -c "for i in libmkl_core.so libmkl_gnu_thread.so libmkl_intel_lp64.so libmkl_intel_thread.so libmkl_def.so libmkl_vml_def.so libmkl_rt.so libmkl_avx2.so libmkl_avx512.so libmkl_sequential.so libomp.so ; do echo copying \$i && docker cp -L pytorch_backend_ptlib:/opt/conda/lib/\$i \$i ; done"
copying libmkl_core.so
copying libmkl_gnu_thread.so
copying libmkl_intel_lp64.so
copying libmkl_intel_thread.so
copying libmkl_def.so
copying libmkl_vml_def.so
copying libmkl_rt.so
copying libmkl_avx2.so
copying libmkl_avx512.so
copying libmkl_sequential.so
[ 85%] Linking CXX static library libtritonbackendutils.a
cd /tmp/tritonbuild/pytorch/build/_deps/repo-backend-build && /usr/bin/cmake -P CMakeFiles/triton-backend-utils.dir/cmake_clean_target.cmake
cd /tmp/tritonbuild/pytorch/build/_deps/repo-backend-build && /usr/bin/cmake -E cmake_link_script CMakeFiles/triton-backend-utils.dir/link.txt --verbose=0
make[2]: Leaving directory '/tmp/tritonbuild/pytorch/build'
copying libomp.so
[ 85%] Built target triton-backend-utils
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so libc10.so
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch/lib/libc10_cuda.so libc10_cuda.so
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch/lib/libtorch.so libtorch.so
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so libtorch_cpu.so
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so libtorch_cuda.so
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_global_deps.so libtorch_global_deps.so
docker cp pytorch_backend_ptlib:/opt/pytorch/vision/build/libtorchvision.so libtorchvision.so
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch_tensorrt/lib/libtorchtrt_runtime.so libtorchtrt_runtime.so || echo "error ignored..." || true
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch_tensorrt/bin/torchtrtc torchtrtc || echo "error ignored..." || true
docker cp pytorch_backend_ptlib:/opt/pytorch/pytorch/LICENSE LICENSE.pytorch
docker cp pytorch_backend_ptlib:/opt/conda/lib/python3.8/site-packages/torch/include include/torch
docker cp pytorch_backend_ptlib:/opt/pytorch/pytorch/torch/csrc/jit/codegen include/torch/torch/csrc/jit/codegen
docker cp pytorch_backend_ptlib:/opt/pytorch/vision/torchvision/csrc include/torchvision/torchvision
docker cp pytorch_backend_ptlib:/usr/lib/x86_64-linux-gnu/libopencv_videoio.so.3.4.11 libopencv_videoio.so
docker cp pytorch_backend_ptlib:/usr/lib/x86_64-linux-gnu/libopencv_highgui.so.3.4.11 libopencv_highgui.so
docker cp pytorch_backend_ptlib:/usr/lib/x86_64-linux-gnu/libopencv_video.so.3.4.11 libopencv_video.so
docker cp pytorch_backend_ptlib:/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.4.11 libopencv_imgcodecs.so
docker cp pytorch_backend_ptlib:/usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.3.4.11 libopencv_imgproc.so
docker cp pytorch_backend_ptlib:/usr/lib/x86_64-linux-gnu/libopencv_core.so.3.4.11 libopencv_core.so
docker cp pytorch_backend_ptlib:/usr/lib/x86_64-linux-gnu/libpng16.so.16.37.0 libpng16.so
/bin/sh -c "if [ -f libmkl_def.so ]; then patchelf --add-needed libmkl_gnu_thread.so libmkl_def.so; fi"
/bin/sh -c "if [ -f libmkl_def.so ]; then patchelf --add-needed libmkl_core.so libmkl_def.so; fi"
/bin/sh -c "if [ -f libmkl_avx2.so ]; then patchelf --add-needed libmkl_gnu_thread.so libmkl_avx2.so; fi"
/bin/sh -c "if [ -f libmkl_avx2.so ]; then patchelf --add-needed libmkl_core.so libmkl_avx2.so; fi"
/bin/sh -c "if [ -f libmkl_avx512.so ]; then patchelf --add-needed libmkl_gnu_thread.so libmkl_avx512.so; fi"
/bin/sh -c "if [ -f libmkl_avx512.so ]; then patchelf --add-needed libmkl_core.so libmkl_avx512.so; fi"
docker rm pytorch_backend_ptlib
pytorch_backend_ptlib
make[2]: Leaving directory '/tmp/tritonbuild/pytorch/build'
[ 85%] Built target ptlib_target
make  -f CMakeFiles/triton-pytorch-backend.dir/build.make CMakeFiles/triton-pytorch-backend.dir/depend
make[2]: Entering directory '/tmp/tritonbuild/pytorch/build'
cd /tmp/tritonbuild/pytorch/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tritonbuild/pytorch /tmp/tritonbuild/pytorch /tmp/tritonbuild/pytorch/build /tmp/tritonbuild/pytorch/build /tmp/tritonbuild/pytorch/build/CMakeFiles/triton-pytorch-backend.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/tritonbuild/pytorch/build'
make  -f CMakeFiles/triton-pytorch-backend.dir/build.make CMakeFiles/triton-pytorch-backend.dir/build
make[2]: Entering directory '/tmp/tritonbuild/pytorch/build'
[ 90%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o
[ 95%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o
/usr/bin/c++ -DTRITON_ENABLE_STATS=1 -Dtriton_pytorch_backend_EXPORTS -I/tmp/tritonbuild/pytorch/src -I/usr/include/python3.8 -I/tmp/tritonbuild/pytorch/build/include/torch -I/tmp/tritonbuild/pytorch/build/include/torch/torch/csrc/api/include -I/tmp/tritonbuild/pytorch/build/include/torchvision -I/tmp/tritonbuild/pytorch/build/_deps/repo-core-src/include -I/tmp/tritonbuild/pytorch/build/_deps/repo-backend-src/include -I/tmp/tritonbuild/pytorch/build/_deps/repo-common-src/include -O3 -DNDEBUG -fPIC -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wall -Wextra -Wno-unused-parameter -Wno-type-limits -pthread -MD -MT CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o -MF CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o.d -o CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o -c /tmp/tritonbuild/pytorch/src/libtorch.cc
/usr/bin/c++ -DTRITON_ENABLE_STATS=1 -Dtriton_pytorch_backend_EXPORTS -I/tmp/tritonbuild/pytorch/src -I/usr/include/python3.8 -I/tmp/tritonbuild/pytorch/build/include/torch -I/tmp/tritonbuild/pytorch/build/include/torch/torch/csrc/api/include -I/tmp/tritonbuild/pytorch/build/include/torchvision -I/tmp/tritonbuild/pytorch/build/_deps/repo-core-src/include -I/tmp/tritonbuild/pytorch/build/_deps/repo-backend-src/include -I/tmp/tritonbuild/pytorch/build/_deps/repo-common-src/include -O3 -DNDEBUG -fPIC -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wall -Wextra -Wno-unused-parameter -Wno-type-limits -pthread -MD -MT CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o -MF CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o.d -o CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o -c /tmp/tritonbuild/pytorch/src/libtorch_utils.cc
[100%] Linking CXX shared library libtriton_pytorch.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/triton-pytorch-backend.dir/link.txt --verbose=0
/usr/bin/ld: cannot find -ltorch
/usr/bin/ld: cannot find -ltorchvision
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/triton-pytorch-backend.dir/build.make:117: libtriton_pytorch.so] Error 1
make[2]: Leaving directory '/tmp/tritonbuild/pytorch/build'
make[1]: *** [CMakeFiles/Makefile2:144: CMakeFiles/triton-pytorch-backend.dir/all] Error 2
make[1]: Leaving directory '/tmp/tritonbuild/pytorch/build'
make: *** [Makefile:136: all] Error 2
platform linux
machine x86_64
version 2.19.0
default repo-tag: r22.02
backend "pytorch" at tag/branch "r22.02"
repoagent "checksum" at tag/branch "r22.02"
Building Triton Inference Server
component "common" at tag/branch "r22.02"
component "core" at tag/branch "r22.02"
component "backend" at tag/branch "r22.02"
component "thirdparty" at tag/branch "r22.02"
error: make install failed
error: docker run tritonserver_builder failed
Traceback (most recent call last):
  File "build_triton.py", line 140, in <module>
    main()
  File "build_triton.py", line 136, in main
    _build_triton_image(args.backends, args.hardware)
  File "build_triton.py", line 96, in _build_triton_image
    _build_cpu_image(backends, tmp_dir, repository_uri)
  File "build_triton.py", line 24, in _build_cpu_image
    subprocess.run(shlex.split(cmd), check=True, cwd=os.path.join(tmp_dir, "server"))
  File "/home/akm/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', 'build.py', '--cmake-dir=./build', '--build-dir=/tmp/tritonbuild', '--enable-logging', '--enable-stats', '--enable-tracing', '--enable-metrics', '--endpoint=http', '--endpoint=grpc', '--repo-tag=common:r22.02', '--repo-tag=core:r22.02', '--repo-tag=backend:r22.02', '--repo-tag=thirdparty:r22.02', '--repoagent=checksum:r22.02', '--backend=pytorch:r22.02']' returned non-zero exit status 1.
```

**Comment by CoderHam** [comment]
@andremoeller support for CPU only PyTorch was added in r22.04. The specific issue here is caused by a bug when using the GPU enabled PyTorch NGC container to build the CPU PyTorch backend in CPU only container.

The fix came from https://github.com/triton-inference-server/pytorch_backend/commit/1c4db7023e669e6b2ba021b97ffd777687dd4b7f and https://github.com/triton-inference-server/server/commit/821cdfef03da2066cda32b71dc63d74c441fd08c

Please move forward to using r22.04 to unblock yourself.
