### ISSUE TITLE
Parse error at offset 0: The document is empty.

### ISSUE THREAD

**Issue by bchinnari** [triton-inference-server/server#4406]
I am using triton server, I want to send input and get output using http client.
I am using docker for server (nvcr.io/nvidia/tritonserver:22.04-py3) and I installed triton client using pip. 
I have an onnx model at (/n/w1-bchinnari/onnxruntime_expts/models) and I am mounting it when I am running the docker using -v
I want to run the model on CPU only. Following is the logs when I run the docker
```
docker run  --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /n/w1-bchinnari/onnxruntime_expts/models:/models b60593591cfc tritonserver --model-repository=/models

NVIDIA Release 22.04 (build 36821869)
Triton Server Version 2.21.0
Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 495.29.05 which has support for CUDA 11.5.  This container
  was built with CUDA 11.6 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[System has unsupported display driver / cuda driver combination (CUDA_ERROR_SYSTEM_DRIVER_MISMATCH) cuInit()=803]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

I0519 10:34:51.253064 1 libtorch.cc:1381] TRITONBACKEND_Initialize: pytorch
I0519 10:34:51.253154 1 libtorch.cc:1391] Triton TRITONBACKEND API version: 1.9
I0519 10:34:51.253158 1 libtorch.cc:1397] 'pytorch' TRITONBACKEND API version: 1.9
2022-05-19 10:34:51.531886: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0519 10:34:51.555857 1 tensorflow.cc:2181] TRITONBACKEND_Initialize: tensorflow
I0519 10:34:51.555885 1 tensorflow.cc:2191] Triton TRITONBACKEND API version: 1.9
I0519 10:34:51.555890 1 tensorflow.cc:2197] 'tensorflow' TRITONBACKEND API version: 1.9
I0519 10:34:51.555893 1 tensorflow.cc:2221] backend configuration:
{}
I0519 10:34:51.560179 1 onnxruntime.cc:2400] TRITONBACKEND_Initialize: onnxruntime
I0519 10:34:51.560190 1 onnxruntime.cc:2410] Triton TRITONBACKEND API version: 1.9
I0519 10:34:51.560194 1 onnxruntime.cc:2416] 'onnxruntime' TRITONBACKEND API version: 1.9
I0519 10:34:51.560197 1 onnxruntime.cc:2446] backend configuration:
{}
I0519 10:34:51.577097 1 openvino.cc:1207] TRITONBACKEND_Initialize: openvino
I0519 10:34:51.577108 1 openvino.cc:1217] Triton TRITONBACKEND API version: 1.9
I0519 10:34:51.577111 1 openvino.cc:1223] 'openvino' TRITONBACKEND API version: 1.9
W0519 10:34:52.795543 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: the provided PTX was compiled with an unsupported toolchain.
I0519 10:34:52.796381 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
E0519 10:34:53.331363 1 server.cc:199] Failed to finalize CUDA memory manager: CNMEM_STATUS_CUDA_ERROR
I0519 10:34:53.333410 1 server.cc:549] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0519 10:34:53.333451 1 server.cc:576] 
+-------------+-------------------------------------------------------------------------+--------+
| Backend     | Path                                                                    | Config |
+-------------+-------------------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so                 | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so         | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so         | {}     |
| openvino    | /opt/tritonserver/backends/openvino_2021_4/libtriton_openvino_2021_4.so | {}     |
+-------------+-------------------------------------------------------------------------+--------+

I0519 10:34:53.333462 1 server.cc:619] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+


I0519 10:34:53.384411 1 metrics.cc:650] Collecting metrics for GPU 0: NVIDIA A100-SXM-80GB
I0519 10:34:53.384858 1 tritonserver.cc:2123] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                        |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                       |
| server_version                   | 2.21.0                                                                                                                                                                                       |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace |
| model_repository_path[0]         | /models                                                                                                                                                                                      |
| model_control_mode               | MODE_NONE                                                                                                                                                                                    |
| strict_model_config              | 1                                                                                                                                                                                            |
| rate_limit                       | OFF                                                                                                                                                                                          |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                    |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                     |
| response_cache_byte_size         | 0                                                                                                                                                                                            |
| min_supported_compute_capability | 6.0                                                                                                                                                                                          |
| strict_readiness                 | 1                                                                                                                                                                                            |
| exit_timeout                     | 30                                                                                                                                                                                           |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0519 10:34:53.390021 1 grpc_server.cc:4544] Started GRPCInferenceService at 0.0.0.0:8001
I0519 10:34:53.392492 1 http_server.cc:3242] Started HTTPService at 0.0.0.0:8000
I0519 10:34:53.433422 1 http_server.cc:180] Started Metrics Service at 0.0.0.0:8002
```

docker seems running fine
```
curl -v localhost:8000/v2/health/ready
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/health/ready HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
```

I am trying to run following client code . I am creating random matrix and sending as input to the server 
```
import numpy as np
import sys
import time

import tritonclient.http as httpclient
from tritonclient.utils import InferenceServerException

def simple_infer(model_name, logfbanks):
    inlen = logfbanks.shape[2]
    inputs = httpclient.InferInput('audio_signal', [1, 80, inlen], "FP32")
    inputs.set_data_from_numpy(logfbanks, binary_data=False)
    outputs = httpclient.InferRequestedOutput('logprobs', binary_data=False)
    results = triton_client.infer(model_name, [inputs], outputs=[outputs])
    return results

try:
    triton_client = httpclient.InferenceServerClient(url='localhost:8000', verbose=False)
except Exception as e:
    print("channel creation failed: " + str(e))
    sys.exit(1)

model_name="/models/citrinet-1024-8x-stride-gamma-025.onnx"

logfbanks = np.random.randn(1,80, 32).astype('f')
results = simple_infer(model_name, logfbanks)
print(results)
```

I am getting following error when I runn the client code
```
$ python eg_client.py 
Traceback (most recent call last):
  File "/n/w1-bchinnari/tritonExpts/eg_client.py", line 28, in <module>
    results = simple_infer(model_name, logfbanks)
  File "/n/w1-bchinnari/tritonExpts/eg_client.py", line 14, in simple_infer
    results = triton_client.infer(model_name, [inputs], outputs=[outputs])
  File "/n/w1-bchinnari/miniconda3/envs/trt1_p39/lib/python3.9/site-packages/tritonclient/http/__init__.py", line 1372, in infer
    _raise_if_error(response)
  File "/n/w1-bchinnari/miniconda3/envs/trt1_p39/lib/python3.9/site-packages/tritonclient/http/__init__.py", line 62, in _raise_if_error
    error = _get_error(response)
  File "/n/w1-bchinnari/miniconda3/envs/trt1_p39/lib/python3.9/site-packages/tritonclient/http/__init__.py", line 51, in _get_error
    error_response = json.loads(response.read())
rapidjson.JSONDecodeError: Parse error at offset 0: The document is empty.
```

I don't know what I am missing. Help is appreciated

Thanks
Bhargav

**Comment by krishung5** [comment]
Hi @bchinnari, could you run the server with `--log-verbose=1` flag to be more verbose? Looks like the model is not loaded correctly. If models are loaded, the log should look like:
```
I0518 17:08:22.180638 21048 server.cc:626]
+-----------------------+---------+--------+
| Model                 | Version | Status |
+-----------------------+---------+--------+
| add_sub               | 1       | READY  |
| batch_auto_complete   | 1       | READY  |
| bls_sync              | 1       | READY  |
| nobatch_auto_complete | 1       | READY  |
| pytorch               | 1       | READY  |
| repeat_int32          | 1       | READY  |
| square_int32          | 1       | READY  |
+-----------------------+---------+--------+
```

**Comment by bchinnari** [comment]
I have a model (citrinet-1024-8x-stride-gamma-025.onnx) in this dir  `/n/w1-bchinnari/onnxruntime_expts/models`
I am mounting this dir using -v and this is the command I am running
```
docker run  --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /n/w1-bchinnari/onnxruntime_expts/models:/models b60593591cfc tritonserver --model-repository=/models --log-verbose=1
```

```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.04 (build 36821869)
Triton Server Version 2.21.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 495.29.05 which has support for CUDA 11.5.  This container
  was built with CUDA 11.6 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[System has unsupported display driver / cuda driver combination (CUDA_ERROR_SYSTEM_DRIVER_MISMATCH) cuInit()=803]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

I0519 17:52:17.757130 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
I0519 17:52:18.166019 1 libtorch.cc:1381] TRITONBACKEND_Initialize: pytorch
I0519 17:52:18.166041 1 libtorch.cc:1391] Triton TRITONBACKEND API version: 1.9
I0519 17:52:18.166044 1 libtorch.cc:1397] 'pytorch' TRITONBACKEND API version: 1.9
I0519 17:52:18.166096 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so
2022-05-19 17:52:18.307831: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0519 17:52:18.333241 1 tensorflow.cc:2181] TRITONBACKEND_Initialize: tensorflow
I0519 17:52:18.333269 1 tensorflow.cc:2191] Triton TRITONBACKEND API version: 1.9
I0519 17:52:18.333273 1 tensorflow.cc:2197] 'tensorflow' TRITONBACKEND API version: 1.9
I0519 17:52:18.333277 1 tensorflow.cc:2221] backend configuration:
{}
I0519 17:52:18.333332 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so
I0519 17:52:18.342246 1 onnxruntime.cc:2400] TRITONBACKEND_Initialize: onnxruntime
I0519 17:52:18.342263 1 onnxruntime.cc:2410] Triton TRITONBACKEND API version: 1.9
I0519 17:52:18.342267 1 onnxruntime.cc:2416] 'onnxruntime' TRITONBACKEND API version: 1.9
I0519 17:52:18.342269 1 onnxruntime.cc:2446] backend configuration:
{}
I0519 17:52:18.349727 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/openvino_2021_4/libtriton_openvino_2021_4.so
I0519 17:52:18.362640 1 openvino.cc:1207] TRITONBACKEND_Initialize: openvino
I0519 17:52:18.362652 1 openvino.cc:1217] Triton TRITONBACKEND API version: 1.9
I0519 17:52:18.362655 1 openvino.cc:1223] 'openvino' TRITONBACKEND API version: 1.9
W0519 17:52:19.532721 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: the provided PTX was compiled with an unsupported toolchain.
I0519 17:52:19.535506 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0519 17:52:19.535516 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 1 with size 67108864
I0519 17:52:19.535519 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 2 with size 67108864
I0519 17:52:19.535521 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 3 with size 67108864
E0519 17:52:20.187692 1 server.cc:199] Failed to finalize CUDA memory manager: CNMEM_STATUS_CUDA_ERROR
W0519 17:52:28.060636 1 server.cc:206] failed to enable peer access for some device pairs
I0519 17:52:28.062208 1 server.cc:549] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0519 17:52:28.062248 1 server.cc:576] 
+-------------+-------------------------------------------------------------------------+--------+
| Backend     | Path                                                                    | Config |
+-------------+-------------------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so                 | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so         | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so         | {}     |
| openvino    | /opt/tritonserver/backends/openvino_2021_4/libtriton_openvino_2021_4.so | {}     |
+-------------+-------------------------------------------------------------------------+--------+

I0519 17:52:28.062259 1 server.cc:619] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

I0519 17:52:28.148289 1 metrics.cc:650] Collecting metrics for GPU 0: NVIDIA A100-SXM-80GB
I0519 17:52:28.148332 1 metrics.cc:650] Collecting metrics for GPU 1: NVIDIA A100-SXM-80GB
I0519 17:52:28.148340 1 metrics.cc:650] Collecting metrics for GPU 2: NVIDIA A100-SXM-80GB
I0519 17:52:28.148344 1 metrics.cc:650] Collecting metrics for GPU 3: NVIDIA A100-SXM-80GB
I0519 17:52:28.149295 1 tritonserver.cc:2123] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                        |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                       |
| server_version                   | 2.21.0                                                                                                                                                                                       |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace |
| model_repository_path[0]         | /models                                                                                                                                                                                      |
| model_control_mode               | MODE_NONE                                                                                                                                                                                    |
| strict_model_config              | 1                                                                                                                                                                                            |
| rate_limit                       | OFF                                                                                                                                                                                          |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                    |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                     |
| cuda_memory_pool_byte_size{1}    | 67108864                                                                                                                                                                                     |
| cuda_memory_pool_byte_size{2}    | 67108864                                                                                                                                                                                     |
| cuda_memory_pool_byte_size{3}    | 67108864                                                                                                                                                                                     |
| response_cache_byte_size         | 0                                                                                                                                                                                            |
| min_supported_compute_capability | 6.0                                                                                                                                                                                          |
| strict_readiness                 | 1                                                                                                                                                                                            |
| exit_timeout                     | 30                                                                                                                                                                                           |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0519 17:52:28.150460 1 grpc_server.cc:4488] === GRPC KeepAlive Options ===
I0519 17:52:28.150469 1 grpc_server.cc:4489] keepalive_time_ms: 7200000
I0519 17:52:28.150471 1 grpc_server.cc:4491] keepalive_timeout_ms: 20000
I0519 17:52:28.150473 1 grpc_server.cc:4493] keepalive_permit_without_calls: 0
I0519 17:52:28.150475 1 grpc_server.cc:4495] http2_max_pings_without_data: 2
I0519 17:52:28.150477 1 grpc_server.cc:4497] http2_min_recv_ping_interval_without_data_ms: 300000
I0519 17:52:28.150479 1 grpc_server.cc:4500] http2_max_ping_strikes: 2
I0519 17:52:28.150481 1 grpc_server.cc:4502] ==============================
I0519 17:52:28.154713 1 grpc_server.cc:225] Ready for RPC 'ServerLive', 0
I0519 17:52:28.154728 1 grpc_server.cc:225] Ready for RPC 'ServerReady', 0
I0519 17:52:28.154734 1 grpc_server.cc:225] Ready for RPC 'ModelReady', 0
I0519 17:52:28.154743 1 grpc_server.cc:225] Ready for RPC 'ServerMetadata', 0
I0519 17:52:28.154792 1 grpc_server.cc:225] Ready for RPC 'ModelMetadata', 0
I0519 17:52:28.154817 1 grpc_server.cc:225] Ready for RPC 'ModelConfig', 0
I0519 17:52:28.154820 1 grpc_server.cc:225] Ready for RPC 'ModelStatistics', 0
I0519 17:52:28.154826 1 grpc_server.cc:225] Ready for RPC 'Trace', 0
I0519 17:52:28.154831 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryStatus', 0
I0519 17:52:28.154836 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryRegister', 0
I0519 17:52:28.154841 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryUnregister', 0
I0519 17:52:28.154862 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryStatus', 0
I0519 17:52:28.154866 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryRegister', 0
I0519 17:52:28.154871 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryUnregister', 0
I0519 17:52:28.154893 1 grpc_server.cc:225] Ready for RPC 'RepositoryIndex', 0
I0519 17:52:28.154898 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelLoad', 0
I0519 17:52:28.154916 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelUnload', 0
I0519 17:52:28.154935 1 grpc_server.cc:419] Thread started for CommonHandler
I0519 17:52:28.155195 1 grpc_server.cc:3542] New request handler for ModelInferHandler, 0
I0519 17:52:28.155215 1 grpc_server.cc:2472] Thread started for ModelInferHandler
I0519 17:52:28.155837 1 grpc_server.cc:3542] New request handler for ModelInferHandler, 0
I0519 17:52:28.155859 1 grpc_server.cc:2472] Thread started for ModelInferHandler
I0519 17:52:28.155900 1 grpc_server.cc:3926] New request handler for ModelStreamInferHandler, 0
I0519 17:52:28.155918 1 grpc_server.cc:2472] Thread started for ModelStreamInferHandler
I0519 17:52:28.155929 1 grpc_server.cc:4544] Started GRPCInferenceService at 0.0.0.0:8001
I0519 17:52:28.158462 1 http_server.cc:3242] Started HTTPService at 0.0.0.0:8000
I0519 17:52:28.199428 1 http_server.cc:180] Started Metrics Service at 0.0.0.0:8002
```

**Comment by bchinnari** [comment]
In the client code , I first tried like this 
```
model_name="citrinet-1024-8x-stride-gamma-025.onnx"
results = triton_client.infer(model_name, [inputs], outputs=[outputs])
```
The log from the server is as follows
```
I0519 18:08:58.019735 1 http_server.cc:3142] HTTP request: 2 /v2/models/citrinet-1024-8x-stride-gamma-025.onnx/infer
I0519 18:08:58.019794 1 http_server.cc:2685] Infer failed: Request for unknown model: 'citrinet-1024-8x-stride-gamma-025.onnx' is not found
```

I thought it is not able to find the model. Hence I appended "/model/" to the path in client code like this
```
model_name="/models/citrinet-1024-8x-stride-gamma-025.onnx"
```

Now the server log is as follows
```
I0519 18:10:06.566431 1 http_server.cc:3142] HTTP request: 2 /v2/models//models/citrinet-1024-8x-stride-gamma-025.onnx/infer
I0519 18:10:06.566483 1 http_server.cc:3224] HTTP error: 2 /v2/models//models/citrinet-1024-8x-stride-gamma-025.onnx/infer - 400
```

**Comment by krishung5** [comment]
Thanks for providing the log. After running the server, could you try to use `curl localhost:8000/v2/models/{model_name}/config` to confirm that the model is loaded correctly? If the model is loaded, it should return the configuration of the model. If not, you should see some message like
`{"error":"Request for unknown model: 'model_name' is not found"}`

Based on the log here
```
I0519 17:52:28.062259 1 server.cc:619] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+
```
It looks like there's no model loaded.

**Comment by GuanLuo** [comment]
And can you share the directory structure in `/n/w1-bchinnari/onnxruntime_expts/models`, Triton only detects a model if it is in the [expected layout ](https://github.com/triton-inference-server/server/blob/main/docs/model_repository.md#repository-layout)

**Comment by Tabrizian** [comment]
Closing due to in-activity.
