### ISSUE TITLE
Ensemble model can't obtain data from pre-processor

### ISSUE THREAD

**Issue by zhaozhiming37** [triton-inference-server/server#4673]
Q: My service consists of two torchscript models. When the triton service is started, each model service is normal, but in the pipeline, the inference model can't obtain data from pre-processor?I don't know why, and thanks for your help.

My config:
```
platform: "pytorch_libtorch"
input [
  {
    name: "image__0"
    data_type: TYPE_FP32
    dims: [ -1, -1, -1, 3 ]
  },
  {
    name: "faces__1"
    data_type: TYPE_FP32
    dims: [ -1, 15 ]
  }
]

output [
  {
    name: "boxes__0"
    data_type: TYPE_FP32
    dims: [ -1, 4 ]
  },
  {
    name: "crops__1"
    data_type: TYPE_FP32
    dims: [ -1, 3, 112, 112 ]
  }
]

instance_group [{ kind: KIND_GPU }]

model_warmup [
  {
    name: "zero_tensor"
    inputs {
      key: "image__0"
      value: {
        data_type: TYPE_FP32
        dims: [1, 112, 112, 3]
        zero_data: true
      }
    }
    inputs {
      key: "faces__1"
      value: {
        data_type: TYPE_FP32
        dims: [1, 15]
        zero_data: true
      }
    }
  },
  {
    name: "random_tensor"
    inputs {
      key: "image__0"
      value: {
        data_type: TYPE_FP32
        dims: [2, 112, 112, 3]
        random_data: true
      }
    }
    inputs {
      key: "faces__1"
      value: {
        data_type: TYPE_FP32
        dims: [2, 15]
        random_data: true
      }
    }
  }
]
```
```
platform: "pytorch_libtorch"
max_batch_size : 16
input [
  {
    name: "crops__1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 112, 112 ]
  }
]
output [
  {
    name: "scores__0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_GPU }]

dynamic_batching {
}

model_warmup [
  {
    name: "zero_tensor"
    inputs {
      key: "crops__1"
      value: {
        data_type: TYPE_FP32
        dims: [2, 3, 112, 112]
        zero_data: true
      }
    }
  },
  {
    name: "random_tensor"
    inputs {
      key: "crops__1"
      value: {
        data_type: TYPE_FP32
        dims: [2, 3, 112, 112]
        random_data: true
      }
    }
  }
]

```
```
platform: "ensemble"
input [
  {
    name: "IMAGE"
    data_type: TYPE_FP32
    dims: [ -1, -1, -1, 3 ]
  },
  {
    name: "FACES"
    data_type: TYPE_FP32
    dims: [ -1, 15 ]
  }
]
output [
  {
    name: "SCORES"
    data_type: TYPE_FP32
    dims: [ -1, 1 ]
  },
  {
    name: "BOXES"
    data_type: TYPE_FP32
    dims: [ -1, 4 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "face_iqa_preprocess"
      model_version: -1
      input_map {
        key: "image__0"
        value: "IMAGE"
      }
      input_map {
        key: "faces__1"
        value: "FACES"
      }
      output_map {
        key: "boxes__0"
        value: "BOXES"
      }
      output_map {
        key: "crops__1"
        value: "CROPS"
      }
    },
    {
      model_name: "face_iqa_inference"
      model_version: -1
      input_map {
        key: "crops__1"
        value: "CROPS"
      }
      output_map {
        key: "scores__0"
        value: "SCORES"
      }
    }
  ]
}
```
~~~

```
Traceback (most recent call last):
  File "/media/zzm/Code/work/yolov5_triton_server/face_client.py", line 357, in <module>
    FaceSRequest.GrpcRequest(gclient, image, faces)
  File "/media/zzm/Code/work/yolov5_triton_server/face_client.py", line 301, in GrpcRequest
    response = client.infer("face_iqa_pipeline",
  File "/home/zzm/anaconda3/envs/triton/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 1295, in infer
    raise_error_grpc(rpc_error)
  File "/home/zzm/anaconda3/envs/triton/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'face_iqa_pipeline', PyTorch execute failure: forward() Expected a value of type 'Tensor' for argument 'input' but instead found type 'NoneType'.
Position: 1
Declaration: forward(__torch__.torch.nn.modules.container.Sequential self, Tensor input) -> (Tensor)
Exception raised from checkArg at /opt/pytorch/pytorch/aten/src/ATen/core/function_schema_inl.h:293 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7fdbf4bf2ecc in /opt/tritonserver/backends/pytorch/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x7fdbf4bd0cb4 in /opt/tritonserver/backends/pytorch/libc10.so)
frame #2: <unknown function> + 0x107e895 (0x7fdc2c9d6895 in /opt/tritonserver/backends/pytorch/libtorch_cpu.so)
frame #3: torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) const + 0x18c (0x7fdc2eb9a86c in /opt/tritonserver/backends/pytorch/libtorch_cpu.so)
frame #4: <unknown function> + 0x27afa (0x7fdc3583eafa in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #5: <unknown function> + 0x1f429 (0x7fdc35836429 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #6: <unknown function> + 0x21aec (0x7fdc35838aec in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #7: TRITONBACKEND_ModelInstanceExecute + 0x38a (0x7fdc358394aa in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #8: <unknown function> + 0x31207a (0x7fdc3777b07a in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #9: <unknown function> + 0x312797 (0x7fdc3777b797 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #10: <unknown function> + 0x1a5221 (0x7fdc3760e221 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #11: <unknown function> + 0x30c607 (0x7fdc37775607 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #12: <unknown function> + 0xd6de4 (0x7fdc36fbfde4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #13: <unknown function> + 0x8609 (0x7fdc3743c609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #14: clone + 0x43 (0x7fdc36caa163 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by Tabrizian** [comment]
You are using the named index convention of the pytorch backend. As a result, you would need to specify `crops__0` instead of `crops__1` for your input. The` __<index>` represents the index of the input in your model's forward function. Looks like your model only has a single input so the index should be zero.
