### ISSUE TITLE
Two issues when trying to do the homework of Triton server lesson from the NVIDIA DLI

### ISSUE THREAD

**Issue by sdecoder** [triton-inference-server/server#4696]
Greetings everyone.

I am learning the course of Deploying a Model for Inference at Production Scale from the NVIDIA DLI.
First of all, I followed all block codes in the notebooks on the Jupiter Notebook server. 
Everything worked as intended - so perfect.

And I am going to reproduce all results by my own cube.
So here comes the specifications:
1. CPU: 11th Gen Intel i9-11900F (16) @ 5.000GHz
GPU: NVIDIA Tesla M40
Memory: 7143MiB / 64177MiB

2. OS: Generic Linux x86_64
Triton Inference Server: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/layers
Latest Tag: 22.06-py3
Modified: July 1, 2022
Launcher: sudo docker run --gpus all --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/pluto/tritonserver/models:/models nvcr.io/nvidia/tritonserver:22.06-py3 tritonserver --model-repository=/models

I have come across two issues:
1. as for [03_HuggingFace_NLP_Model] lesson, there comes the exception stack when I try to submit my request to the local Triton server:

```
Traceback (most recent call last):
  File "/home/noname/projects/deeplearning/tritonserver/models/huggingface-model/code/main.py", line 94, in <module>
    _run_client()
  File "/home/noname/projects/deeplearning/tritonserver/models/huggingface-model/code/main.py", line 79, in _run_client
    response = triton_client.infer(model_name, model_version=model_version, inputs=[input0, input1], outputs=[output])
  File "/home/noname/anaconda3/envs/pytorch-cuda/lib/python3.9/site-packages/tritonclient/http/__init__.py", line 1418, in infer
    _raise_if_error(response)
  File "/home/noname/anaconda3/envs/pytorch-cuda/lib/python3.9/site-packages/tritonclient/http/__init__.py", line 65, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: PyTorch execute failure: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 12, in forward
    input_ids = torch.to(data, dtype=4, layout=0, device=torch.device("cuda"), pin_memory=None, non_blocking=False, copy=False, memory_format=None)
    attention_mask0 = torch.to(attention_mask, dtype=4, layout=0, device=torch.device("cuda"), pin_memory=None, non_blocking=False, copy=False, memory_format=None)
    _1 = (_0).forward(input_ids, attention_mask0, )
          ~~~~~~~~~~~ <--- HERE
    return (_1,)
  File "code/__torch__/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 11, in forward
    attention_mask: Tensor) -> Tensor:
    _0 = self.classifier
    _1 = (self.roberta).forward(input_ids, attention_mask, )
          ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0).forward(_1, )
  File "code/__torch__/transformers/models/roberta/modeling_roberta.py", line 26, in forward
    _9 = torch.to(extended_attention_mask, 6, False, False, None)
    attention_mask0 = torch.mul(torch.rsub(_9, 1., 1), CONSTANTS.c0)
    _10 = (_0).forward((_1).forward(input_ids, input, ), attention_mask0, )
                        ~~~~~~~~~~~ <--- HERE
    return _10
class RobertaEmbeddings(Module):
  File "code/__torch__/transformers/models/roberta/modeling_roberta.py", line 53, in forward
    _18 = torch.to(incremental_indices, 4, False, False, None)
    input0 = torch.add(_18, CONSTANTS.c2, alpha=1)
    embeddings = torch.add((_15).forward(input_ids, ), (_14).forward(input, ), alpha=1)
                            ~~~~~~~~~~~~ <--- HERE
    input1 = torch.add_(embeddings, (_13).forward(input0, ), alpha=1)
    _19 = (_11).forward((_12).forward(input1, ), )
  File "code/__torch__/torch/nn/modules/sparse.py", line 8, in forward
  def forward(self: __torch__.torch.nn.modules.sparse.Embedding,
    input_ids: Tensor) -> Tensor:
    inputs_embeds = torch.embedding(self.weight, input_ids, 1, False, False)
                    ~~~~~~~~~~~~~~~ <--- HERE
    return inputs_embeds

Traceback of TorchScript, original code (most recent call last):
/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py(1828): embedding
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py(145): forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(726): _slow_forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(742): _call_impl
/opt/conda/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py(131): forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(726): _slow_forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(742): _call_impl
/opt/conda/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py(844): forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(726): _slow_forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(742): _call_impl
/opt/conda/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py(1203): forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(726): _slow_forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(742): _call_impl
<ipython-input-2-48b86358d29a>(21): forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(726): _slow_forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(742): _call_impl
/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py(934): trace_module
/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py(733): trace
<ipython-input-2-48b86358d29a>(24): <module>
/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py(3418): run_code
/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py(3338): run_ast_nodes
/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py(3146): run_cell_async
/opt/conda/lib/python3.8/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py(2923): _run_cell
/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py(2877): run_cell
/opt/conda/lib/python3.8/site-packages/ipykernel/zmqshell.py(536): run_cell
/opt/conda/lib/python3.8/site-packages/ipykernel/ipkernel.py(306): do_execute
/opt/conda/lib/python3.8/site-packages/tornado/gen.py(234): wrapper
/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py(543): execute_request
/opt/conda/lib/python3.8/site-packages/tornado/gen.py(234): wrapper
/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py(268): dispatch_shell
/opt/conda/lib/python3.8/site-packages/tornado/gen.py(234): wrapper
/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py(365): process_one
/opt/conda/lib/python3.8/site-packages/tornado/gen.py(775): run
/opt/conda/lib/python3.8/site-packages/tornado/gen.py(814): inner
/opt/conda/lib/python3.8/site-packages/tornado/ioloop.py(741): _run_callback
/opt/conda/lib/python3.8/site-packages/tornado/ioloop.py(688): <lambda>
/opt/conda/lib/python3.8/asyncio/events.py(81): _run
/opt/conda/lib/python3.8/asyncio/base_events.py(1859): _run_once
/opt/conda/lib/python3.8/asyncio/base_events.py(570): run_forever
/opt/conda/lib/python3.8/site-packages/tornado/platform/asyncio.py(199): start
/opt/conda/lib/python3.8/site-packages/ipykernel/kernelapp.py(612): start
/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py(845): launch_instance
/opt/conda/lib/python3.8/site-packages/ipykernel_launcher.py(16): <module>
/opt/conda/lib/python3.8/runpy.py(87): _run_code
/opt/conda/lib/python3.8/runpy.py(194): _run_module_as_main
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)

```

The key issue: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select) 
My code is pasted here for further inverstigation:

```
from cgi import print_form
from operator import mod
import os
import torch
from transformers import XLMRobertaForSequenceClassification, XLMRobertaTokenizer


R_tokenizer = XLMRobertaTokenizer.from_pretrained('joeddav/xlm-roberta-large-xnli')
premise = "Jupiter's Biggest Moons Started as Tiny Grains of Hail"
hypothesis = 'This text is about space & cosmos'

class PyTorch_to_TorchScript(torch.nn.Module):
    def __init__(self):
        super(PyTorch_to_TorchScript, self).__init__()
        self.model = XLMRobertaForSequenceClassification.from_pretrained('joeddav/xlm-roberta-large-xnli', return_dict=False)
    def forward(self, data, attention_mask=None):
        return self.model(data.cuda(), attention_mask.cuda())


def _main():

  print(f'[trace] start to create pytorch model')
  model_weight = '1/model.pt'
  if os.path.exists(model_weight):
    return

  pt_model = PyTorch_to_TorchScript().eval().cuda()

  input_ids = R_tokenizer.encode(premise, hypothesis, return_tensors='pt',
                               max_length=256, padding='max_length')
  mask = input_ids != 1
  mask = mask.long()
  traced_script_module = torch.jit.trace(pt_model, (input_ids, mask))
  traced_script_module.save(model_weight)
  pass

def _run_client():

  import tritonclient.http as tritonhttpclient

  VERBOSE = False
  input_name = ['input__0', 'input__1']
  input_dtype = 'INT32'
  output_name = 'output__0'
  model_name = 'huggingface-model'
  url = 'localhost:8000'
  model_version = '1'

  triton_client = tritonhttpclient.InferenceServerClient(url=url, verbose=VERBOSE)
  model_metadata = triton_client.get_model_metadata(model_name=model_name, model_version=model_version)
  model_config = triton_client.get_model_config(model_name=model_name, model_version=model_version)

  import numpy as np
  from transformers import XLMRobertaTokenizer


  # instantiate our tokenizer
  R_tokenizer = XLMRobertaTokenizer.from_pretrained('joeddav/xlm-roberta-large-xnli')

  # create our premise and topic to be passed into the model
  premise = 'Jupiter’s Biggest Moons Started as Tiny Grains of Hail'
  topic = 'This text is about space & cosmos'

  # encode our inputs, convert to numpy arrays, create our mask, and do some reshaping
  print(f'[trace] preparing the input data...')
  input_ids = R_tokenizer.encode(premise, topic, max_length=256, truncation=True, padding='max_length')
  input_ids = np.array(input_ids, dtype=np.int32)
  mask = input_ids != 1
  mask = np.array(mask, dtype=np.int32)
  mask = mask.reshape(1, 256)
  input_ids = input_ids.reshape(1, 256)

  print(f'[trace] start to call the Trition server ClientAPI')
  input0 = tritonhttpclient.InferInput(input_name[0], (1, 256), input_dtype)
  input0.set_data_from_numpy(input_ids, binary_data=False)
  input1 = tritonhttpclient.InferInput(input_name[1], (1, 256), input_dtype)
  input1.set_data_from_numpy(mask, binary_data=False)
  output = tritonhttpclient.InferRequestedOutput(output_name,  binary_data=False)
  response = triton_client.infer(model_name, model_version=model_version, inputs=[input0, input1], outputs=[output])
  print(f'[trace] get tht output from the Trition server')
  logits = response.as_numpy(output_name)
  logits = np.asarray(logits, dtype=np.float32)

  from scipy.special import softmax
  entail_contradiction_logits = logits[:,[0,2]]
  probs = softmax(entail_contradiction_logits)
  true_prob = probs[:,1].item() * 100
  print(f'Probability that the label is true: {true_prob:0.2f}%')

  pass

if __name__ == '__main__':
  #_main()
  _run_client()
  pass

```

2. as for [05 - Simple TensorRT Model] lesson, I strictly followed the lesson instructions to generate the TensorRT plan files.
Directory structures are shown here:

simple-tensorrt-fp32-model
├── 1
│   └── model.plan
├── config.pbtxt

simple-tensorrt-fp16-model
├── 1
│   └── model.plan
├── config.pbtxt

The model conversion commands are showed here:
```
For FP32:
trtexec --onnx=model.onnx \
  --explicitBatch \
  --optShapes=actual_input_1:16x3x224x224 \
  --maxShapes=actual_input_1:32x3x224x224 \
  --minShapes=actual_input_1:1x3x224x224 \
  --shapes=actual_input_1:1x3x224x224 \
  --saveEngine=1/model.plan

For FP16:
trtexec --onnx=model.onnx \
  --explicitBatch \
  --optShapes=actual_input_1:16x3x224x224 \
  --maxShapes=actual_input_1:32x3x224x224 \
  --minShapes=actual_input_1:1x3x224x224 \
  --shapes=actual_input_1:1x3x224x224 \
  --saveEngine=1/model.plan --fp16

```
Note: the onnx file are downloaded from the Jupyter Notebook server.
Launcher: sudo docker run --gpus all --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/pluto/tritonserver/models:/models nvcr.io/nvidia/tritonserver:22.06-py3 tritonserver --model-repository=/models
When I tried to launch the Triton server, following errors show up and then the server is down:
```
| simple-tensorrt-fp32-model | 1       | UNAVAILABLE: Invalid argument: unable to load model 'simple-tensorrt-fp32-model', TensorRT backend supports only GPU device |
| simple-tensorrt-fp16-model | 1       | UNAVAILABLE: Invalid argument: unable to load model 'simple-tensorrt-fp16-model', TensorRT backend supports only GPU device |
```
Here is the last SOS from server log.
```
I0726 14:18:00.960432 1 server.cc:257] Waiting for in-flight requests to complete.
I0726 14:18:00.960436 1 server.cc:273] Timeout 30: Found 0 model versions that have in-flight inferences
I0726 14:18:00.960442 1 model_repository_manager.cc:1223] unloading: simple-tensorflow-model:1
I0726 14:18:00.960470 1 model_repository_manager.cc:1223] unloading: simple-pytorch-model:1
I0726 14:18:00.960493 1 model_repository_manager.cc:1223] unloading: simple-onnx-model:1
I0726 14:18:00.960538 1 model_repository_manager.cc:1223] unloading: huggingface-model:1
I0726 14:18:00.960576 1 server.cc:288] All models are stopped, unloading models
I0726 14:18:00.960581 1 server.cc:295] Timeout 30: Found 4 live models and 0 in-flight non-inference requests
I0726 14:18:00.960593 1 onnxruntime.cc:2645] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0726 14:18:00.960596 1 libtorch.cc:2038] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0726 14:18:00.960620 1 tensorflow.cc:2397] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0726 14:18:00.960661 1 tensorflow.cc:2336] TRITONBACKEND_ModelFinalize: delete model state
I0726 14:18:00.960708 1 libtorch.cc:2038] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0726 14:18:00.963510 1 onnxruntime.cc:2591] TRITONBACKEND_ModelFinalize: delete model state
I0726 14:18:00.963534 1 model_repository_manager.cc:1328] successfully unloaded 'simple-onnx-model' version 1
I0726 14:18:00.966145 1 libtorch.cc:1983] TRITONBACKEND_ModelFinalize: delete model state
I0726 14:18:00.966163 1 model_repository_manager.cc:1328] successfully unloaded 'simple-pytorch-model' version 1
I0726 14:18:00.972774 1 libtorch.cc:1983] TRITONBACKEND_ModelFinalize: delete model state
I0726 14:18:00.972798 1 model_repository_manager.cc:1328] successfully unloaded 'huggingface-model' version 1
I0726 14:18:01.022549 1 model_repository_manager.cc:1328] successfully unloaded 'simple-tensorflow-model' version 1
I0726 14:18:01.960652 1 server.cc:295] Timeout 29: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
W0726 14:18:01.963594 1 metrics.cc:468] Unable to get energy consumption for GPU 0. Status:Success, value:0
W0726 14:18:02.963792 1 metrics.cc:468] Unable to get energy consumption for GPU 0. Status:Success, value:0

```

Thank you so much for any help. 😀

**Comment by GuanLuo** [comment]
1. @Tabrizian do you have insight on what may be happening?
2. What is the `config.pbtxt` you provided to the TRT model? The instance group in the file may be set to non-GPU which is not supported by TRT backend.

**Comment by sdecoder** [comment]
"Release 20.03 supports CUDA compute capability 6.0 and higher. This corresponds to GPUs in the Pascal, Volta, and Turing families. Specifically, for a list of GPUs that this compute capability corresponds to, see [CUDA GPUs](https://developer.nvidia.com/cuda-gpus). For additional support details, see [Deep Learning Frameworks Support Matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html)."
via https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-03.html

So my M40 GPU is not supported. Issue closed.
