### ISSUE TITLE
[BUG] Multi-input model with varying sizes gives error with gRPC client

### ISSUE THREAD

**Issue by niqbal996** [triton-inference-server/server#4780]
Hi, 
**Description**
I am trying to do inference on a 3D LiDAR point cloud detector (PointPillar) via Triton server and a gRPC client. I exported the model to ONNX and here is how the config file looks:

```bash
name: "pointpillar"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "voxels"
    data_type: TYPE_FP32
    dims: [-1, 32, 4]
  },
  {
    name: "coors"
    data_type: TYPE_INT32
    dims: [-1, 4]
  },
  {
    name: "num_points"
    data_type: TYPE_INT32
    dims: [-1]
  }
]
output [
  {
    name: "bbox_preds"
    data_type: TYPE_FP32
    dims: [1, 42, 248, 216]
  },
  {
    name: "dir_scores"
    data_type: TYPE_FP32
    dims: [1, 12, 248, 216]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [1, 18, 248, 216]
  }
]
``` 
The model is loaded by the triton server correctly without any errors. Now I am trying to send the preprocessed point clouds to the server via the client which is based on the example [grpc_image_client.py](https://github.com/triton-inference-server/client/blob/main/src/python/examples/grpc_image_client.py). 

THe model is expecting three inputs which I process in this way following the API, please let me know if you notice any mistake:
```python
self.input0 = service_pb2.ModelInferRequest().InferInputTensor() # voxels
self.input0.name = self.channel.input[0]
self.input0.datatype = self.input_types[0]
self.input1 = service_pb2.ModelInferRequest().InferInputTensor() # coors
self.input1.name = self.channel.input[1]
self.input1.datatype = self.input_types[1]
self.input2 = service_pb2.ModelInferRequest().InferInputTensor() # num_points
self.input2.name = self.channel.input[2]
self.input2.datatype = self.input_types[2]

self.channel.request.inputs.extend([self.input0])
self.channel.request.inputs.extend([self.input1])
self.channel.request.inputs.extend([self.input2])
# =============== providing the raw data here
self.channel.request.ClearField("raw_input_contents")
self.channel.request.raw_input_contents.extend([self.pc['voxels'].tobytes()])           # Shape (50, 32, 4)
self.channel.request.raw_input_contents.extend([self.pc['voxel_coords'].tobytes()])     # Shape (50, 4)
self.channel.request.raw_input_contents.extend([np.array([self.pc['voxel_num_points']], dtype=np.int32).tobytes()])    # Shape (760,)

# ================ Also tried this dummy input 
voxels = random.rand(50, 32, 4).tobytes()
coors = random.rand(50, 4).tobytes()
num_points = random.rand(50,).tobytes()
self.channel.request.raw_input_contents.extend([voxels, coors, num_points])
```
Here is the error I get when I send the request:
```
[ERROR] [1660751990.068672]: bad callback: <bound method RosInference3D._pc_callback of <communicator.ros_inference3d.RosInference3D object at 0x7fb8d5f31f10>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/workspace/triton_client_yolo/communicator/ros_inference3d.py", line 185, in _pc_callback
    self.channel.response = self.channel.do_inference() # perform the channel Inference
  File "/workspace/triton_client_yolo/communicator/channel/grpc_channel.py", line 78, in do_inference
    return self._grpc_stub.ModelInfer(self.request)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "[request id: <id_unknown>] unexpected shape for input 'num_points' for model 'pointpillar'. Expected [-1], got []"
        debug_error_string = "{"created":"@1660751990.068186658","description":"Error received from peer ipv6:[::1]:8001","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"[request id: <id_unknown>] unexpected shape for input 'num_points' for model 'pointpillar'. Expected [-1], got []","grpc_status":3}"
>
```
The first two input tensors `voxels` and `coors` do not create any errors but the third input tensor `num_points` shows weird behaviour. The `num_points` input tensor is a variable sized (hence -1) one dimensional array with length that varies for each inference sample request. But the server complains that the dimension that it has received is `[ ]` which if I am not wrong is the BUG. I tried different combinations or array dimensions assuming the input array is somehow wrong but so far I do not see any error on the client side but maybe the server mistakenly decodes the **single-dimensional variable array** in a wrong way?  

**Triton Information**
Triton server version: 2.24.0
Triton docker container: 22.07-py3 

**To Reproduce**
I can provide the ONNX model file, config file and point cloud input sample file. Unfortunately, I cannot share the full client repository code but we can arrange via a private email or something if needed. 

**Expected behavior**
I expect the server to take all three input tensors namely `voxels`, `coors` and `num_points` without producing any wrong dimension errors. 
I would be very thankful if you provide some insights or things that I could have overlooked.

**Comment by niqbal996** [comment]
Hi @GuanLuo ,
Thank you for the quick response. I tried that like this, and that worked out: 
```python
self.input0 = service_pb2.ModelInferRequest().InferInputTensor() # voxels
self.input0.name = self.channel.input[0]
self.input0.datatype = self.input_types[0]
self.input0.shape.extend([-1, 32, 4])
self.input1 = service_pb2.ModelInferRequest().InferInputTensor() # coors
self.input1.name = self.channel.input[1]
self.input1.datatype = self.input_types[1]
self.input1.shape.extend([-1, 4])
self.input2 = service_pb2.ModelInferRequest().InferInputTensor() # num_points
self.input2.name = self.channel.input[2]
self.input2.datatype = self.input_types[2]
self.input2.shape.extend([-1])
self.channel.request.inputs.extend([self.input0])
self.channel.request.inputs.extend([self.input1])
self.channel.request.inputs.extend([self.input2])
```
Here the `self.channel.input` is a list of input tensor names `['voxels', 'coors', 'num_points']` returned by the `parse_model` function. At first, I tried to assign the shapes like this and it gave me an error. 
```python
self.input0.shape = [-1, 32, 4]
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: Assignment not allowed to repeated field "shape" in protocol message object.
```
I checked the [`InferInputTensor`](https://github.com/triton-inference-server/common/blob/84892b105f5bccd248fa85cf6fae9f9769a1b30e/protobuf/grpc_service.proto#L584-L589) and it says `(repeated)`. I learned that the repeated tensors have to be used with `.extend()` function instead. 
```proto
    //@@
    //@@    .. cpp:var:: int64 shape (repeated)
    //@@
    //@@       The tensor shape.
    //@@
    repeated int64 shape = 3;
```
I realized my silly mistake where I am supposed to use `.extend()` instead of assigning the shapes.

**Comment by niqbal996** [comment]
For someone struggling like me with variable-sized input, I did a hacky fix which I do not know how to explain. For each input sample, i have varying number of voxels which is the first dimension for all 3 inputs to my network. Since its not the batch dimension, setting it to `-1` gives an error. So here is what I do: Before I send my first request, I initialize the `InferInputTensor` like this: 
```python
self.input0 = service_pb2.ModelInferRequest().InferInputTensor() # voxels
self.input0.name = self.channel.input[0]
self.input0.datatype = self.input_types[0]
tmp = 10000 #>>>>>>>>>>>>>> Dummy number of voxels
self.input0.shape.extend([tmp, 32, 4])
self.input1 = service_pb2.ModelInferRequest().InferInputTensor() # coors
self.input1.name = self.channel.input[1]
self.input1.datatype = self.input_types[1]
self.input1.shape.extend([tmp, 4])
self.input2 = service_pb2.ModelInferRequest().InferInputTensor() # num_points
self.input2.name = self.channel.input[2]
self.input2.datatype = self.input_types[2]
self.input2.shape.extend([tmp])
self.channel.request.inputs.extend([self.input0, self.input1, self.input2])
```
Then for each input message (I am using a ROS callback function that gets called for each point cloud sample) I flush the shape dimension and set it to the number of voxels for each sample like this: 
```python
num_voxels = self.pc['voxels'].shape[0]
self.input0.ClearField("shape")
self.input1.ClearField("shape")
self.input2.ClearField("shape")
self.input0.shape.extend([num_voxels, 32, 4])
self.input1.shape.extend([num_voxels, 4])
self.input2.shape.extend([num_voxels])
from numpy import random
voxels = random.rand(num_voxels, 32, 4)
coors = np.random.randint(1,100, size=(num_voxels,4), dtype=np.int32)
num_points = np.random.randint(1,1000, size=(num_voxels,), dtype=np.int32)
self.channel.request.raw_input_contents.extend([voxels.tobytes(), coors.tobytes(), num_points.tobytes()])
```
This is more related to the varying input dimension problem that the error message I had in the begining but just leaving it here if anyone else facing some issue.
