### ISSUE TITLE
docs/examples/stable_diffusion -> `scale_model_input` function should be called before `step`

### ISSUE THREAD

**Issue by nikolaydyankov** [triton-inference-server/server#5073]
I followed /docs/examples/stable_diffusion/README.md and when I started the server and prompted the model I got this error in the server log:

```
0it [00:00, ?it/s]/usr/local/lib/python3.8/dist-packages/diffusers/schedulers/scheduling_lms_discrete.py:207: UserWarning: The `scale_model_input` function should be called before `step` to ensure correct denoising. See `StableDiffusionPipeline` for a usage example.
  warnings.warn(
50it [00:04, 12.40it/s]
E1113 16:49:28.731224 1229 python_be.cc:1907] Stub process is unhealthy and it will be restarted.
```

And this in the client:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 289, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "client.py", line 26, in generate
    response = client.infer(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1431, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] Failed to process the request(s) for model instance 'pipeline_0', message: Stub process is not healthy.
```

I found this [post](https://huggingface.co/CompVis/stable-diffusion-v1-4/discussions/126#635d5d8506a944e347beeae0) on the stable diffusion community forum:

```
use image.sample instead of image.

credit: https://www.reddit.com/r/StableDiffusion/comments/xdxika/comment/is3pmfs/?utm_source=share&utm_medium=web2x&context=3
```

Perhaps the README.md needs to be updated?

EDIT: From what I understand, line 130 of stable_diffusion/model_repository/pipeline/1/model.py needs to change to this:

```
decoded_image = (decoded_image.sample / 2 + 0.5).clamp(0, 1)
```

**Comment by Tabrizian** [comment]
There is a bug in our backlog for the same issue. We'll update this issue when we get to this bug.
