### ISSUE TITLE
Mutex lock in statistics report

### ISSUE THREAD

**Issue by clementruhm** [triton-inference-server/server#5127]
**Description**
I am getting this segfault:
```
Thread 73 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fdd39fff000 (LWP 335)]
__GI___pthread_mutex_lock (mutex=0x290) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x290) at ../nptl/pthread_mutex_lock.c:67
#1  0x00007fdeae37e7b8 in triton::core::InferenceStatsAggregator::UpdateSuccessWithDuration(triton::core::MetricModelReporter*, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long) () from /opt/tritonserver/lib/libtritonserver.so
#2  0x00007fdeae36a7ab in triton::core::InferenceRequest::ReportStatistics(triton::core::MetricModelReporter*, bool, unsigned long, unsigned long, unsigned long, unsigned long) ()
   from /opt/tritonserver/lib/libtritonserver.so
#3  0x00007fdeae2fc371 in TRITONBACKEND_ModelInstanceReportStatistics () from /opt/tritonserver/lib/libtritonserver.so
#4  0x00007fdea04f67d3 in triton::backend::pytorch::ModelInstanceState::ProcessRequests(TRITONBACKEND_Request**, unsigned int) () from /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
#5  0x00007fdea04f8408 in TRITONBACKEND_ModelInstanceExecute () from /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
#6  0x00007fdeae30319a in triton::core::TritonModelInstance::Execute(std::vector<TRITONBACKEND_Request*, std::allocator<TRITONBACKEND_Request*> >&) () from /opt/tritonserver/lib/libtritonserver.so
#7  0x00007fdeae303b07 in triton::core::TritonModelInstance::Schedule(std::vector<std::unique_ptr<triton::core::InferenceRequest, std::default_delete<triton::core::InferenceRequest> >, std::allocator<std::unique_ptr<triton::core::InferenceRequest, std::default_delete<triton::core::InferenceRequest> > > >&&, std::function<void ()> const&) () from /opt/tritonserver/lib/libtritonserver.so
#8  0x00007fdeae3d7101 in triton::core::Payload::Execute(bool*) () from /opt/tritonserver/lib/libtritonserver.so
#9  0x00007fdeae2fde47 in triton::core::TritonModelInstance::TritonBackendThread::BackendThread(int, int) () from /opt/tritonserver/lib/libtritonserver.so
#10 0x00007fdeae0e4de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007fdeade89609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007fdeaddae133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

torch model is executed with triton_c_api with dynamic batching enabled. happens during second model execution. there are 3 models run sequentially. as far as I can see it happens after running 3rd one.

I added

```
TRITONSERVER_ServerOptionsSetMetrics(server_options, false);
```

but it didn't help

**Triton Information**
Tried 22.09 and 22.11 dockers. both fail in the same way.

Are you using the Triton container or did you build it yourself?
Using triton container, with app built inside it. 

**To Reproduce**
Rather difficult given I use my own code to specify interactions between models and on top of async websocket server (https://www.boost.org/doc/libs/master/libs/beast/example/websocket/server/async/websocket_server_async.cpp). I would appreciate any hints on debugging or if issue persists, will try to wrap a reproducible example.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Would omit for now, model is proprietary

**Expected behavior**
no segfaults :)

**Comment by GuanLuo** [comment]
Can you reproduce it with Triton server? Trying to rule out as many as the customized components as possible, the segfault is likely to be caused by memory corruption which may happen far from where the segfault is reported

**Comment by krishung5** [comment]
Closing issue due to lack of activity. Please re-open the issue if you would like to follow up with this issue.
