### ISSUE TITLE
Error reported while running BLS instance

### ISSUE THREAD

**Issue by JasonChao-yue** [triton-inference-server/server#5665]
Using Python_ When using the backend sample for BLS runtime, use Python_ backend/examples/bls_ Decoupled/sync in the directory_ Model. py. tritonserver successfully deployed the model, but the following error occurred during client requests
model_repository--->bls_decoupledsync--> config.pbtxt   1--->model.py
model_repository--->square_int32---->config.pbtxt   1--->model.py

nvidia@nvidia-B360M-D2V:~/server/docs/examples/model_repository/bls_decoupled_sync$ python3 sync_client.py
Traceback (most recent call last):
  File "sync_client.py", line 47, in <module>
    response = client.infer(model_name,
  File "/home/nvidia/.local/lib/python3.8/site-packages/tritonclient/http/__init__.py", line 1490, in infer
    _raise_if_error(response)
  File "/home/nvidia/.local/lib/python3.8/site-packages/tritonclient/http/__init__.py", line 65, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: Failed to process the request(s) for model instance 'bls_decoupled_sync_0', message: TypeError: exec(): incompatible function arguments. The following argument types are supported:
    1. (self: c_python_backend_utils.InferenceRequest) -> triton::backend::python::InferResponse

Invoked with: <c_python_backend_utils.InferenceRequest object at 0x7fb396d258b0>; kwargs: decoupled=True

At:
  /models/bls_decoupled_sync/1/model.py(119): execute

**Comment by JasonChao-yue** [comment]
Thank you.

The problem has been resolved due to environmental mismatch issues

**Comment by hbikki** [comment]
Hello, can you provide details regarding the  environmental mismatch issues? Is the mismatch in triton  backends  ?
