### ISSUE TITLE
Failed to register CUDA shared mem: failed to open CUDA IPC handle: invalid resource handle

### ISSUE THREAD

**Issue by SCraenen** [triton-inference-server/server#5798]
I'm running triton server nvcr.io/nvidia/tritonserver:23.04-py3 and nvcr.io/nvidia/tritonserver:23.04-py3-sdk as docker containers from my windows machine. I'm trying to run the simple_grpc_cudashm_client.py and I get this error:

```
Traceback (most recent call last):
  File "yolov7/simple_grpc_cudashm_client.py", line 88, in <module>
    triton_client.register_cuda_shared_memory(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1300, in register_cuda_shared_memory
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 75, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INVALID_ARGUMENT] failed to register CUDA shared memory region 'output0_data': failed to open CUDA IPC handle: invalid resource handle
```

I haven't changed any of the code. Here are my docker startup commands:

```
docker run --gpus all --rm --ipc=host --pid=host --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v C:\Users\media\Documents\models\triton-model-repository:/models nvcr.io/nvidia/tritonserver:23.04-py3 tritonserver --model-repository=/models --log-verbose 5
```
```
docker run -it --pid=host --rm -v C:\Users\media\Documents\triton-inference:/code --gpus all nvcr.io/nvidia/tritonserver:23.04-py3-sdk
```

The server lists the simple model as ready.

Any help would be appreciated.

_Originally posted by @SCraenen in https://github.com/triton-inference-server/server/issues/3429#issuecomment-1549314853_

**Comment by oandreeva-nv** [comment]
CUDA shared memory is not supported on Windows: https://github.com/triton-inference-server/server/issues/3429#issuecomment-1550042808
