### ISSUE TITLE
error running inference using grpc client for java 

### ISSUE THREAD

**Issue by faquir-sun** [triton-inference-server/server#6030]
**Description**
### A clear and concise description of what the bug is.
Inference using the grpc java client returns a parameter error
**Triton Information**
What version of Triton are you using?
### R22.12
Are you using the Triton container or did you build it yourself?
### self build cpu only
**To Reproduce**
Steps to reproduce the behavior.

### using java code call server ：
```
ModelInferRequest.InferInputTensor.Builder input0 = ModelInferRequest.InferInputTensor
				.newBuilder();
		input0.setName("INPUT");
		input0.setDatatype("UINT8");
		input0.addShape(-1);
		input0.addShape(-1);
		input0.addShape(-1);
		input0.addShape(3);
		input0.setContents(input0_data);
```
### got error:
```
Exception in thread "main" io.grpc.StatusRuntimeException: 
INVALID_ARGUMENT: [request id: <id_unknown>] All input dimensions should be specified for input 'INPUT' for model 't_model', got [-1,-1,-1,3]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at inference.GRPCInferenceServiceGrpc$GRPCInferenceServiceBlockingStub.modelInfer(GRPCInferenceServiceGrpc.java:1575)
	at clients.SimpleJavaClient.main(SimpleJavaClient.java:146)
```
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

### model detail is:
```
name: "t_model"
platform: "ensemble"
max_batch_size: 1
input [
  {
    name: "INPUT"
    data_type: TYPE_UINT8
    dims: [ -1, -1, 3 ]
  }
]
output [
  {
    name: "rec_texts"
    data_type: TYPE_STRING
    dims: [ -1, 1 ]
  },
  {
    name: "rec_scores"
    data_type: TYPE_FP32
    dims: [ -1, 1 ]
  },
  {
    name: "det_bboxes"
    data_type: TYPE_FP32
    dims: [ -1, -1, 1 ]
  }
]
```

**Expected behavior**

**Comment by nnshah1** [comment]
During inference the shape of the tensor must be known and a dimension of '-1' is indicating 'unknown'. -1 as a dimension is only valid in the model configuration side - not in the construction of the input on the client side. Hope that helps.

You would need to update the client side with the actual values of the input for the inference request:

```
ModelInferRequest.InferInputTensor.Builder input0 = ModelInferRequest.InferInputTensor
				.newBuilder();
		input0.setName("INPUT");
		input0.setDatatype("UINT8");
		input0.addShape(**<actual batch size>**);
		input0.addShape(**<actual shape>**);
		input0.addShape(**<actual shape>**);
		input0.addShape(3);
		input0.setContents(input0_data);
```

**Comment by faquir-sun** [comment]
Thank you very much, it has solved my confusion all the time. 
The question now is that the input sent to the model is an image. How can I convert the image to uint8 format required by the model and get the actual shape information of the image, I saw that the similar operation in the demo is:
```
InferTensorContents.Builder input0_data = InferTensorContents.newBuilder();
input0_data.addAllUintContents(Iterable<? extends Integer> values)
```

**Comment by faquir-sun** [comment]
I send the data using the following code,but get a wrong result
```
 FileInputStream fileInputStream = new FileInputStream("/Users/test.jpg");
InferTensorContents imgInput = InferTensorContents.parseFrom(fileInputStream);
// Populate the inputs in inference request
ModelInferRequest.InferInputTensor.Builder input0 = ModelInferRequest.InferInputTensor.newBuilder();
input0.setName("INPUT");
input0.setDatatype("UINT8");
input0.addShape(1);
input0.addShape(720);
input0.addShape(1150);
input0.addShape(3);
input0.setContents(imgInput);
```
response is:
```
model_name: "t_model"
model_version: "1"
parameters {
  key: "sequence_end"
  value {
    bool_param: false
  }
}
parameters {
  key: "sequence_id"
  value {
    int64_param: 0
  }
}
parameters {
  key: "sequence_start"
  value {
    bool_param: false
  }
}
outputs {
  name: "det_bboxes"
  datatype: "FP64"
  shape: 1
  shape: 0
}
outputs {
  name: "rec_scores"
  datatype: "FP64"
  shape: 1
  shape: 1
}
outputs {
  name: "rec_texts"
  datatype: "BYTES"
  shape: 1
  shape: 1
}
// print result
0_contents""
1_contents: "\000\000\000\000\000\000\000\000"
2_contents: "\000\000\000\000"
```

**Comment by nnshah1** [comment]
I believe this line needs to be changed to load the image and decode the JPG into an RGB image. 

```
InferTensorContents imgInput = InferTensorContents.parseFrom(fileInputStream);
```

You can look for examples of using `javax.imageio.ImageIO`

Since this is a new question - would you mind closing this one and opening a new one?

**Comment by faquir-sun** [comment]
thisks
