### ISSUE TITLE
Unable to open shared memory region

### ISSUE THREAD

**Issue by ZZfive** [triton-inference-server/server#6125]
I want to request inference service which is deployed by triton with system shared memory. As a test, i'm following the official grpc example, but there is a problem, environment is as follows：

- 1 the triton service is started by the officially provided Docker image, version--> nvcr.io/nvidia/tritonserver:22.04-py3, The container startup command: docker run --name triton_test --gpus device=1 --rm -p8000:8000 -p8001:8001 -p8002:8002  -v zjy/triton/model_repo:/models nvcr.io/nvidia/tritonserver:22.04-py3 tritonserver --model-repository=/models --model-control-mode poll --exit-on-error=false
- 2 the requested script file is on the same machine as the triton service
- 3 The version of tritonclient used in the Python script file: tritonclient[all]==2.36.0
- 4 Cuda Information：
![image](https://github.com/triton-inference-server/server/assets/57706634/ba9a4934-c5ea-4043-b7bf-56d567d3070f)

 code is as follows：
```
import argparse
import sys
from builtins import range
from ctypes import *

import numpy as np
import tritonclient.grpc as grpcclient
import tritonclient.utils.shared_memory as shm
from tritonclient import utils

FLAGS = None

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        required=False,
        default=True,
        help="Enable verbose output",
    )
    parser.add_argument(
        "-u",
        "--url",
        type=str,
        required=False,
        default="localhost:8001",
        help="Inference server URL. Default is localhost:8001.",
    )

    FLAGS = parser.parse_args()

    try:
        triton_client = grpcclient.InferenceServerClient(
            url=FLAGS.url, verbose=FLAGS.verbose
        )
    except Exception as e:
        print("channel creation failed: " + str(e))
        sys.exit(1)

    # To make sure no shared memory regions are registered with the
    # server.
    triton_client.unregister_system_shared_memory()
    triton_client.unregister_cuda_shared_memory()

    # We use a simple model that takes 2 input tensors of 16 integers
    # each and returns 2 output tensors of 16 integers each. One
    # output tensor is the element-wise sum of the inputs and one
    # output is the element-wise difference.
    model_name = "simple"
    model_version = ""

    # Create the data for the two input tensors. Initialize the first
    # to unique integers and the second to all ones.
    input0_data = np.arange(start=0, stop=16, dtype=np.int32)
    input1_data = np.ones(shape=16, dtype=np.int32)

    input_byte_size = input0_data.size * input0_data.itemsize
    output_byte_size = input_byte_size

    # Create shared memory region for output and store shared memory handle
    shm_op_handle = shm.create_shared_memory_region(
        "output_data", "/output_simple", output_byte_size * 2
    )

    # Register shared memory region for outputs with Triton Server
    triton_client.register_system_shared_memory(
        "output_data", "/output_simple", output_byte_size * 2
    )

    # Create shared memory region for input and store shared memory handle
    shm_ip_handle = shm.create_shared_memory_region(
        "input_data", "/input_simple", input_byte_size * 2
    )

    # Put input data values into shared memory
    shm.set_shared_memory_region(shm_ip_handle, [input0_data])
    shm.set_shared_memory_region(shm_ip_handle, [input1_data], offset=input_byte_size)

    # Register shared memory region for inputs with Triton Server
    triton_client.register_system_shared_memory(
        "input_data", "/input_simple", input_byte_size * 2
    )

    # Set the parameters to use data from shared memory
    inputs = []
    inputs.append(grpcclient.InferInput("INPUT0", [1, 16], "INT32"))
    inputs[-1].set_shared_memory("input_data", input_byte_size)

    inputs.append(grpcclient.InferInput("INPUT1", [1, 16], "INT32"))
    inputs[-1].set_shared_memory("input_data", input_byte_size, offset=input_byte_size)

    outputs = []
    outputs.append(grpcclient.InferRequestedOutput("OUTPUT0"))
    outputs[-1].set_shared_memory("output_data", output_byte_size)

    outputs.append(grpcclient.InferRequestedOutput("OUTPUT1"))
    outputs[-1].set_shared_memory(
        "output_data", output_byte_size, offset=output_byte_size
    )

    results = triton_client.infer(model_name=model_name, inputs=inputs, outputs=outputs)

    # Read results from the shared memory.
    output0 = results.get_output("OUTPUT0")
    if output0 is not None:
        output0_data = shm.get_contents_as_numpy(
            shm_op_handle, utils.triton_to_np_dtype(output0.datatype), output0.shape
        )
    else:
        print("OUTPUT0 is missing in the response.")
        sys.exit(1)

    output1 = results.get_output("OUTPUT1")
    if output1 is not None:
        output1_data = shm.get_contents_as_numpy(
            shm_op_handle,
            utils.triton_to_np_dtype(output1.datatype),
            output1.shape,
            offset=output_byte_size,
        )
    else:
        print("OUTPUT1 is missing in the response.")
        sys.exit(1)

    for i in range(16):
        print(
            str(input0_data[i])
            + " + "
            + str(input1_data[i])
            + " = "
            + str(output0_data[0][i])
        )
        print(
            str(input0_data[i])
            + " - "
            + str(input1_data[i])
            + " = "
            + str(output1_data[0][i])
        )
        if (input0_data[i] + input1_data[i]) != output0_data[0][i]:
            print("shm infer error: incorrect sum")
            sys.exit(1)
        if (input0_data[i] - input1_data[i]) != output1_data[0][i]:
            print("shm infer error: incorrect difference")
            sys.exit(1)

    print(triton_client.get_system_shared_memory_status())
    triton_client.unregister_system_shared_memory()
    assert len(shm.mapped_shared_memory_regions()) == 2
    shm.destroy_shared_memory_region(shm_ip_handle)
    shm.destroy_shared_memory_region(shm_op_handle)
    assert len(shm.mapped_shared_memory_regions()) == 0

    print("PASS: system shared memory")
```

 error message is as follows:
```
Traceback (most recent call last):
  File "/home/dbt/zjy/API_normals_pre/shm_test.py", line 95, in <module>
    triton_client.register_system_shared_memory(
  File "/home/dbt/miniconda3/envs/normals/lib/python3.9/site-packages/tritonclient/grpc/_client.py", line 1019, in register_system_shared_memory
    raise_error_grpc(rpc_error)
  File "/home/dbt/miniconda3/envs/normals/lib/python3.9/site-packages/tritonclient/grpc/_utils.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] Unable to open shared memory region: '/output_simple'
```

tracking to specific error locations based on error information:
![image](https://github.com/triton-inference-server/server/assets/57706634/36119414-45ee-4bbb-8450-e9f9e7fd69dc)
The specific error code line in the red box in the screenshot above

**Comment by dyastremsky** [comment]
Which official example is this referring to? That'd help me look at what you're referencing.

As a starting place, you'll want to make sure you're using a client and server from the same release to avoid any issues there. You're using a container that's over a year old (22.04) with the newest 23.07 client. You likely also want to pass in a `--net host` flag to the Docker container so that the client (outside the container, it sounds like) can access the server (inside the container). If that doesn't help, does this work if you run the client script in the container?

**Comment by ZZfive** [comment]
Thanks for your advices, @dyastremsky .

The official example link: https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_shm_client.py

Through the content in other issues, I found that after adding the ”- ipc=host - pid=host“  when starting the docker container, the system shared memory could be used normally. 

The container startup command: 
docker run --name normals_triton --gpus device=1 --rm --ipc=host --pid=host --shm-size=1g -p8000:8000 -p8001:8001 -p8002:8002  -v /zjy/triton/model_repo:/models nvcr.io/nvidia/tritonserver:22.04-py3 tritonserver --model-repository=/models --model-control-mode poll --exit-on-error=false

But, i have other questions. An image processing algorithm is deployed in Triton Server, that is encapsulated as an API interface using FastAPI. When accepting user requests, I want to use the system shared memory to request the triton server. At present, I globally initialize shared memory and register it to triton when the service started, code is as follows:

```
triton_client.unregister_system_shared_memory()
triton_client.unregister_cuda_shared_memory()
dummy_input_data = np.random.randn(25, 256, 256, 3).astype('float32')
input_byte_size = dummy_input_data.size * dummy_input_data.itemsize
output_byte_size = input_byte_size
# Create shared memory region for output and store shared memory handle
shm_op_handle = shm.create_shared_memory_region("output_data", "/output", output_byte_size)
# Register shared memory region for outputs with Triton Server
triton_client.register_system_shared_memory("output_data", "/output", output_byte_size)
# Create shared memory region for input and store shared memory handle
shm_ip_handle = shm.create_shared_memory_region("input_data", "/input", input_byte_size)
# Register shared memory region for inputs with Triton Server
triton_client.register_system_shared_memory("input_data", "/input", input_byte_size)
```
Every time the function is called, put the input into shared memory, and then request triton,  code is as follows:
```
def function(SubBatch):
    ......
    S = np.array(SubBatch)
    shm.set_shared_memory_region(shm_ip_handle, [S])
    
    inputs = [grpcclient.InferInput('input/X:0', S.shape, "FP32")]
    inputs[0].set_shared_memory("input_data", input_byte_size)
    outputs = [grpcclient.InferRequestedOutput('l2_normalize:0')]
    outputs[0].set_shared_memory("output_data", output_byte_size)
    
    results = triton_client.infer(model_name=normals_model_name, inputs=inputs, outputs=outputs)
    output = results.get_output("l2_normalize:0")
    predN = shm.get_contents_as_numpy(shm_op_handle, utils.triton_to_np_dtype(output.datatype), output.shape)
    ......
```

The size of the shared memory I initialize is the size of each input and output data, do I need to release system shared memory after each function call? If needed, how should be  system shared memory released?

**Comment by dyastremsky** [comment]
You'd just call destroy_shared_memory_region(handle_name), like in the [example](https://github.com/triton-inference-server/client/blob/f7c45d382639f31a5162666034fae7852681f082/src/python/examples/simple_grpc_shm_client.py#L179-L180). You may also want to call unregister there for cleanness, though I see you call it before sending another input. You can also see how this is done in some QA tests, like the [shared memory test](https://github.com/triton-inference-server/server/blob/14437dc1e4db3fd3165a96f8ccf0f4373d67eb67/qa/L0_shared_memory/shared_memory_test.py#L102).
