### ISSUE TITLE
Deploy Detectron2 converted to tensorrt  Mask R-CNN inside Triton:raise error tritonclient.utils.InferenceServerException: [400] [request id: <id_unknown>] inference request batch-size must be <= 1 for 'detectron_trt'

### ISSUE THREAD

**Issue by imenselmi** [triton-inference-server/server#6165]
## Description:
**With Detectron2, I trained the R-CNN Mask model, then i converted it to ONNX, and finally to a TensorRT model**
**I prepared the config.pbtxt file and created a model repository as described in nvidida triton  documentation and put config and trained model there**
```
name: "detectron_trt"
platform: "tensorrt_plan"
max_batch_size: 1
input [
  {
    name: "input_tensor"
    data_type: TYPE_FP32
    dims: [ 3, 1344, 1344 ]
  }
]
output [
  {
    name: "detection_boxes_box_outputs"
    data_type: TYPE_FP32
    dims: [ 100,4]
  },
  {
    name: "detection_classes_box_outputs"
    data_type: TYPE_INT32
    dims: [-1]
  },
  {
    name: "detection_masks"
    data_type: TYPE_FP32
    dims: [ 100,28,28]
  },
  {
    name: "detection_scores_box_outputs"
    data_type: TYPE_FP32
    dims: [ -1]
  },
  {
    name: "num_detections_box_outputs"
    data_type: TYPE_INT32
    dims: [ -1]
  }
]
instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]

```
**I deploy model inside the server with the command**
```
sudo docker run --gpus all --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.08-py3 tritonserver --model-repository=/models

```
**Server is starting (no errors)**
**When trying to infer using client python lib**
```
import argparse
from concurrent.futures import ThreadPoolExecutor, wait
import time
import cv2
import tritonclient.http as httpclient
from tqdm import tqdm
from PIL import Image
import numpy as np


def test_infer(req_id, image_file, model_name, print_output=False):
    """img = np.array(Image.open(image_file))
    img = np.ascontiguousarray(img.transpose(2, 0, 1))"""
    img=cv2.imread(str(image_file))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = np.array(img, dtype=np.float32)
    img /= 255
    img = np.transpose(img, (2, 0, 1))
    # Define model's inputs
    inputs = []
    inputs.append(httpclient.InferInput('input_tensor', img.shape, "FP32"))
    print(inputs)
    inputs[0].set_data_from_numpy(img)
    # Define model's outputs
    outputs = []
    outputs.append(httpclient.InferRequestedOutput('detection_boxes_box_outputs'))
    outputs.append(httpclient.InferRequestedOutput('detection_classes_box_outputs'))
    outputs.append(httpclient.InferRequestedOutput('detection_masks'))
    outputs.append(httpclient.InferRequestedOutput('detection_scores_box_outputs'))
    outputs.append(httpclient.InferRequestedOutput('num_detections_box_outputs'))
    # Send request to Triton server
    triton_client = httpclient.InferenceServerClient(
        url="localhost:8000", verbose=False)
    results = triton_client.infer(model_name, inputs=inputs, outputs=outputs)
    response_info = results.get_response()
    outputs = {}
    for output_info in response_info['outputs']:
        output_name = output_info['name']
        outputs[output_name] = results.as_numpy(output_name)

    if print_output:
        print(req_id, outputs)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--image', required=True)
    parser.add_argument('--model', required=True)
    parser.add_argument('--mode', default='sequential', choices=['sequential', 'concurrent'])
    parser.add_argument('--num-reqs', default='1')
    parser.add_argument('--print-output', action='store_true')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    image_file = args.image
    model_name = args.model
    mode = args.mode
    n_reqs = int(args.num_reqs)

    if mode == 'sequential':
        for i in tqdm(range(n_reqs)):
            test_infer(i, image_file, model_name, args.print_output)
    elif mode == 'concurrent':
        s = time.time()
        with ThreadPoolExecutor(max_workers=10) as executor:
            futures = [
                executor.submit(test_infer,
                                i,
                                image_file,
                                model_name,
                                args.print_output)
                for i in range(n_reqs)
            ]
            wait(futures)
            for f in futures:
                f.results()
        e = time.time()
        print('FPS:', n_reqs/(e - s))
```

**Get error**
[<tritonclient.http._infer_input.InferInput object at 0x7fc840e6aed0>]
  0%|                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mj/Documents/pfe/src/infer_trt_triton.py", line 64, in <module>
    test_infer(i, image_file, model_name, args.print_output)
  File "/home/mj/Documents/pfe/src/infer_trt_triton.py", line 34, in test_infer
    results = triton_client.infer(model_name, inputs=inputs, outputs=outputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mj/anaconda3/envs/detectron/lib/python3.11/site-packages/tritonclient/http/_client.py", line 1473, in infer
    _raise_if_error(response)
  File "/home/mj/anaconda3/envs/detectron/lib/python3.11/site-packages/tritonclient/http/_utils.py", line 57, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: [400] [request id: <id_unknown>] inference request batch-size must be <= 1 for 'detectron_trt'

how can i fix it !?

**Comment by dyastremsky** [comment]
If your model does not support dynamic batching, you should set the max_batch_size to 0. See documentation [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#maximum-batch-size).

**Comment by imenselmi** [comment]
@dyastremsky the Triton server returned a message indicating that I can only set either 0 or 1 for the max_batch_size in the two options. When I set it to 0 or 1, the same error message persists: 
```
raise error
tritonclient.utils.InferenceServerException: [400] [request id: <id_unknown>] inference request batch-size must be <= 1 for 'd2_1_b_trt'

```

**Comment by dyastremsky** [comment]
Could you try starting Triton with the `--disable-auto-complete-config` flag? I see you're using 22.08, which I believe may have had a bug with the auto-complete feature (which was newly expanded at that time) that may override some aspects of the model config. That might be it.

I'd also recommend seeing if this works in a newer version, like 23.07, if possible. If not, we'd need a model that has this same issue to be able to reproduce and investigate on our end.

**Comment by imenselmi** [comment]
I added the  `--disable-auto-complete-config `flag to my command for starting the Triton server and it now returns the correct dimensions of outputs. It is working correctly now. Additionally, I changed `max_batch_size` to 0. Your advice has been very helpful. Thank you so much!
# the new commands:
**config.pbtxt**
```
name: "detectron_trt"
platform: "tensorrt_plan"
max_batch_size: 0
input [
  {
    name: "input_tensor"
    data_type: TYPE_FP32
    dims: [1,3,1344,1344]
  }
]
output [
  {
    name: "detection_boxes_box_outputs"
    data_type: TYPE_FP32
    dims: [1,100,4]
  },
  {
    name: "detection_classes_box_outputs"
    data_type: TYPE_INT32
    dims: [1,100]
  },
  {
    name: "detection_masks"
    data_type: TYPE_FP32
    dims: [1,100,28,28]
  },
  {
    name: "detection_scores_box_outputs"
    data_type: TYPE_FP32
    dims: [1,100]
  },
  {
    name: "num_detections_box_outputs"
    data_type: TYPE_INT32
    dims: [1,1]
  }
]

```
**docker**
```
sudo docker run --gpus all --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.08-py3 tritonserver --model-repository=/models --disable-auto-complete-config

```
**deploying**
```
import argparse
from concurrent.futures import ThreadPoolExecutor, wait
import time
import cv2
import tritonclient.http as httpclient
from tqdm import tqdm
from PIL import Image
import numpy as np


def test_infer(req_id, image_file, model_name, print_output=False):
    img = cv2.imread(str(image_file))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (1344, 1344))  # Resize the image to the expected input shape
    img = np.array(img, dtype=np.float32)
    img /= 255
    img = np.transpose(img, (2, 0, 1))
    img = np.expand_dims(img, axis=0)
    # Define model's inputs
    inputs = []
    inputs.append(httpclient.InferInput('input_tensor', [1,3,1344,1344], "FP32"))
    print(inputs)
    inputs[0].set_data_from_numpy(img)
    # Define model's outputs
    outputs = []
    outputs.append(httpclient.InferRequestedOutput('detection_boxes_box_outputs'))
    outputs.append(httpclient.InferRequestedOutput('detection_classes_box_outputs'))
    outputs.append(httpclient.InferRequestedOutput('detection_masks'))
    outputs.append(httpclient.InferRequestedOutput('detection_scores_box_outputs'))
    outputs.append(httpclient.InferRequestedOutput('num_detections_box_outputs'))
    # Send request to Triton server
    triton_client = httpclient.InferenceServerClient(
        url="localhost:8000", verbose=False)
    results = triton_client.infer(model_name, inputs=inputs, outputs=outputs)
    response_info = results.get_response()
    outputs = {}
    for output_info in response_info['outputs']:
        output_name = output_info['name']
        outputs[output_name] = results.as_numpy(output_name)

    if print_output:
        print(req_id, outputs)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--image', required=True)
    parser.add_argument('--model', required=True)
    parser.add_argument('--mode', default='sequential', choices=['sequential', 'concurrent'])
    parser.add_argument('--num-reqs', default='1')
    parser.add_argument('--print-output', action='store_true')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    image_file = args.image
    model_name = args.model
    mode = args.mode
    n_reqs = int(args.num_reqs)

    if mode == 'sequential':
        for i in tqdm(range(n_reqs)):
            test_infer(i, image_file, model_name, args.print_output)
    elif mode == 'concurrent':
        s = time.time()
        with ThreadPoolExecutor(max_workers=10) as executor:
            futures = [
                executor.submit(test_infer,
                                i,
                                image_file,
                                model_name,
                                args.print_output)
                for i in range(n_reqs)
            ]
            wait(futures)
            for f in futures:
                f.results()
        e = time.time()
        print('FPS:', n_reqs/(e - s))
```

**Comment by dyastremsky** [comment]
Wonderful, glad it's working! Thanks for updating me.
