### ISSUE TITLE
How to send multiple request for different models

### ISSUE THREAD

**Issue by wxthu** [triton-inference-server/server#6224]
I registered three **_resnext pytorch_** models in triton server and then sent 3 requests for these individual models as examples, but I met the following timeout error:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 1580, in wrapped_post
    return self._post(request_uri, request_body, headers, query_params)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 284, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 292, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 164, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 184, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
2023-08-23T12:36:03Z <Greenlet at 0x7f8fb61fa980: wrapped_post('v2/models/resnext_torch1/infer', b'{"inputs":[{"name":"INPUT1","shape":[1,3,32,32],, {'Inference-Header-Content-Length': 173}, None)> failed with TimeoutError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 1580, in wrapped_post
    return self._post(request_uri, request_body, headers, query_params)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 284, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 292, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 164, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 184, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
2023-08-23T12:36:03Z <Greenlet at 0x7f8fb61faa20: wrapped_post('v2/models/resnext_torch2/infer', b'{"inputs":[{"name":"INPUT2","shape":[1,3,32,32],, {'Inference-Header-Content-Length': 173}, None)> failed with TimeoutError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 1580, in wrapped_post
    return self._post(request_uri, request_body, headers, query_params)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 284, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 292, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 164, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 184, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
2023-08-23T12:36:03Z <Greenlet at 0x7f8fb61faac0: wrapped_post('v2/models/resnext_torch0/infer', b'{"inputs":[{"name":"INPUT0","shape":[1,3,32,32],, {'Inference-Header-Content-Length': 173}, None)> failed with TimeoutError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 1580, in wrapped_post
    return self._post(request_uri, request_body, headers, query_params)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 284, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 292, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 164, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 184, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
2023-08-23T12:36:03Z <Greenlet at 0x7f8fb61fab60: wrapped_post('v2/models/resnext_torch1/infer', b'{"inputs":[{"name":"INPUT1","shape":[1,3,32,32],, {'Inference-Header-Content-Length': 173}, None)> failed with TimeoutError

Traceback (most recent call last):
  File "/workspace/client/src/python/examples/my_custom_http_async_infer_client.py", line 92, in <module>
    result = async_request.get_result()
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 88, in get_result
    response = self._greenlet.get(block=block, timeout=timeout)
  File "src/gevent/greenlet.py", line 831, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 373, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.10/dist-packages/gevent/_compat.py", line 48, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 1580, in wrapped_post
    return self._post(request_uri, request_body, headers, query_params)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 284, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 292, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 164, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 184, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
```
My test code as follows:
```
import argparse
import numpy as np
import sys

import tritonclient.http as httpclient

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-v',
                        '--verbose',
                        action="store_true",
                        required=False,
                        default=False,
                        help='Enable verbose output')
    parser.add_argument('-u',
                        '--url',
                        type=str,
                        required=False,
                        default='localhost:8000',
                        help='Inference server URL. Default is localhost:8000.')

    FLAGS = parser.parse_args()

    request_count = 5
    try:
        # Need to specify large enough concurrency to issue all the
        # inference requests to the server in parallel.
        triton_client = httpclient.InferenceServerClient(
            url=FLAGS.url, verbose=FLAGS.verbose, concurrency=request_count)
    except Exception as e:
        print("context creation failed: " + str(e))
        sys.exit()

    model_names = ['resnext_torch0', 'resnext_torch1', 'resnext_torch2']

    # Infer
    inputs = [[] for _ in range(len(model_names))]
    outputs = [[] for _ in range(len(model_names))]
    for i, ipt in enumerate(inputs):
        ipt.append(httpclient.InferInput('INPUT'+str(i), [1, 3, 32, 32], "FP32"))
    
        # Create the data for the two input tensors.
        input0_data = np.zeros((1, 3, 32, 32), dtype=np.float32)

        # Initialize the data
        ipt[0].set_data_from_numpy(input0_data, binary_data=True)

    for j, opt in enumerate(outputs):
        opt.append(httpclient.InferRequestedOutput('OUTPUT'+str(j), binary_data=True))
        
    async_requests = []

    for i in range(request_count):
        # Asynchronous inference call.
        # For each task
        for j, model_name in enumerate(model_names):
            async_requests.append(
                triton_client.async_infer(model_name=model_name,
                                        inputs=inputs[j],
                                        outputs=outputs[j]))

    for async_request in async_requests:
        # Get the result from the initiated asynchronous inference request.
        # Note the call will block till the server responds.
        result = async_request.get_result()

        print(result.get_response())
```
How can I do that? and Can I enable concurrent inference execution of these models when receiving the request  simultaneously

**Triton Information**
23.07
docker container

**Comment by wxthu** [comment]
@dougn

**Comment by wxthu** [comment]
whether I need to modify some core code and rebuild ? @sublee @brightsparc

**Comment by krishung5** [comment]
Hi @wxthu, can you please share the model config files and the full server log (with `--log-verbose=1` flag)? I wonder if there is any error message reported in the server side.

**Comment by wxthu** [comment]
Thanks! My model config files and client script, server logs are all [here](https://github.com/wxthu/debug_triton_server). And I found some similar issues and looking forward to you reply

**Comment by wxthu** [comment]
Hello, I'd like to wonder if there has been any progress on this matter? I'm eagerly looking forward to knowing the answer hhhhhh @krishung5
