### ISSUE TITLE
Torchscript executes successfully when inferencing in Pytorch, but throws shape mismatch with Triton

### ISSUE THREAD

**Issue by jotterbach** [triton-inference-server/server#6314]
**Description**

I traced a HF-converted LLaMA-2-7B model using `torchscript`. The model executes fine when loading the script within pytorch but throws a shape mismatach when inferencing with Triton.

**Triton Information**
using the vanilla docker container `tritonserver:23.08-py3`

**To Reproduce**

```python
from transformers import AutoTokenizer, AutoModel, AutoModelForCausalLM
import torch
import torch.nn as nn
from pathlib import Path
import numpy as np

model_name = Path("/model-weights/hf/7B")

tokenizer = AutoTokenizer.from_pretrained(model_name)
DUMMY_TEXT = "Girafatron is obsessed with giraffes, the most glorious animal on the face of this Earth. Giraftron believes all other animals are irrelevant when compared to the glorious majesty of the giraffe.\nDaniel: Hello, Girafatron!\nGirafatron:"
tok_text = tokenizer.tokenize(DUMMY_TEXT)
tokens = tokenizer.encode(DUMMY_TEXT)
tok_arr = np.asarray(tokens).reshape(1, -1).astype(np.int32)
tok_arr = np.pad(tok_arr, [(0,0), (0, 1024-tok_arr.shape[1])])
tok_arr = np.repeat(tok_arr, 2, axis=0)

class TritonWrapper(nn.Module):
    
    def __init__(self, model_name: str):
        super().__init__()

        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torchscript=True,
            device_map='cuda:0',
            torch_dtype=torch.bfloat16,
            trust_remote_code=True,
            )
        self.model.to('cuda:0')
        self.model.output_hidden_states = False
                
    def forward(self, tokens_tensor):
        self.model.eval()
        o = self.model(tokens_tensor, output_hidden_states=False)
        return o[0]

model = TritonWrapper(model_name)
model.eval()
assert model.training == False
model_name = "meta-llama/Llama-2-7b"
with torch.no_grad():
    tokens_tensor = torch.from_numpy(tok_arr).to('cuda:0')
    o = model(tokens_tensor)
    traced_model = torch.jit.trace(model, [tokens_tensor])
    print("traced_model done")
    torch.jit.save(traced_model, f"{model_name.split('/')[-1]}.pt")


print("Trying inference!")

with torch.no_grad():
    lm = torch.jit.load(f"{model_name.split('/')[-1]}.pt")
    tokens_tensor = torch.from_numpy(tok_arr).to('cuda:0')
    o = lm(tokens_tensor)
    print("loaded and fwded through trace!", o.shape, tokens_tensor.shape)
```

Note that the script does test whether the model can be inferenced. The code is running fine and a corresponding PT file being generated. Deploying the model with `Triton` I run into a shape mismatch error deep in the scripted model. The stacktrace looks like:

```bash
<HTTPSocketPoolResponse status=400 headers={'content-length': '4165', 'content-type': 'text/plain', 'x-envoy-upstream-service-time': '2837', 'date': 'Fri, 15 Sep 2023 15:11:34 GMT', 'server': 'envoy'}>
Traceback (most recent call last):
  File "/Users/jotterbach/code/flour/inference/development/llama-2-7b-inference.py", line 39, in <module>
    text_response = client.infer(model_name="llama-2-7b", inputs=[text_input], headers=headers)
  File "/Users/jotterbach/miniconda3/envs/spark341-py310/lib/python3.10/site-packages/tritonclient/http/_client.py", line 1473, in infer
    _raise_if_error(response)
  File "/Users/jotterbach/miniconda3/envs/spark341-py310/lib/python3.10/site-packages/tritonclient/http/_utils.py", line 57, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: [400] PyTorch execute failure: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 10, in forward
    tokens_tensor: Tensor) -> Tensor:
    model = self.model
    return (model).forward(tokens_tensor, )
            ~~~~~~~~~~~~~~ <--- HERE
  File "code/__torch__/transformers/models/llama/modeling_llama.py", line 12, in forward
    lm_head = self.lm_head
    model = self.model
    _0 = (lm_head).forward((model).forward(tokens_tensor, ), )
                            ~~~~~~~~~~~~~~ <--- HERE
    return torch.to(_0, 6)
class LlamaModel(Module):
  File "code/__torch__/transformers/models/llama/modeling_llama.py", line 130, in forward
    expanded_attn_mask = torch.to(_56, dtype=15, layout=0, device=torch.device("cuda:0"))
    attention_mask = torch.add(expanded_attn_mask, combined_attention_mask)
    _57 = (_0).forward(_41, position_ids0, attention_mask, )
           ~~~~~~~~~~~ <--- HERE
    _58 = (_1).forward(_57, position_ids0, attention_mask, )
    _59 = (_2).forward(_58, position_ids0, attention_mask, )
  File "code/__torch__/transformers/models/llama/modeling_llama.py", line 181, in forward
    input_layernorm = self.input_layernorm
    _58 = (input_layernorm).forward(argument_1, )
    _59 = (self_attn).forward(_58, position_ids, attention_mask, )
           ~~~~~~~~~~~~~~~~~~ <--- HERE
    hidden_states = torch.add(argument_1, _59)
    _60 = (post_attention_layernorm).forward(hidden_states, )
  File "code/__torch__/transformers/models/llama/modeling_llama.py", line 253, in forward
    hidden_states1 = torch.add(_87, torch.mul(_92, sin0))
    _93 = torch.transpose(hidden_states1, 2, 3)
    attn_weights = torch.div(torch.matmul(query_states, _93), CONSTANTS.c3)
                             ~~~~~~~~~~~~ <--- HERE
    input = torch.add(attn_weights, attention_mask)
    attn_weights0 = torch.to(torch.softmax(input, -1, 6), 15)

Traceback of TorchScript, original code (most recent call last):
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py(335): forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py(413): forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py(697): forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py(809): forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
/mnt/workspace/johannes/scratch/torchscript_converter.py(43): forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/nn/modules/module.py(1501): _call_impl
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/jit/_trace.py(1056): trace_module
/mnt/workspace/johannes/torchscript/lib/python3.10/site-packages/torch/jit/_trace.py(794): trace
/mnt/workspace/johannes/scratch/torchscript_converter.py(65): <module>
RuntimeError: The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 1
```
The `pbtxt` looks like

```python
name: "llama-2-7b"
platform: "pytorch_libtorch"
max_batch_size: 0
input [
  {
    name: "INPUT__0"
    data_type: TYPE_INT32
    dims: [ -1, 1024 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ -1, 1024, 32000]
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]
```

I tried several different version with and without dynamic batch dimension, but all lead to the same result

**Expected behavior**
The code executes in the loaded trace as well as the deployed Triton setting

**Comment by oandreeva-nv** [comment]
Thank you for reporting this issue, I filed a ticket for our team to investigate.

**Comment by jotterbach** [comment]
Thank you @oandreeva-nv . Can you give me any time estimates and/or updates on this?

**Comment by dyastremsky** [comment]
Unfortunately, we cannot provide a time estimate at this time. If you need more immediate or direct support, we recommend looking into our [NVIDIA AI Enterprise software suite](https://www.nvidia.com/en-us/data-center/products/ai-enterprise/).
