### ISSUE TITLE
Trionclient Timeout Error using in Windows WSL docker container

### ISSUE THREAD

**Issue by songkq** [triton-inference-server/server#6782]
Httpclient or grpcclient has the same error. Could you please give some advice?

```
docker BASE_IMAGE=nvcr.io/nvidia/tritonserver:23.05-py3
tritonclient           2.31.0

Exception in thread Thread-1:
Traceback (most recent call last):
    result = client.infer(self.model_name, request_data, request_id="rid_{}".format(request_id))
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/__init__.py", line 1486, in infer
    response = self._post(request_uri=request_uri,
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/__init__.py", line 309, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 292, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 164, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.10/dist-packages/geventhttpclient/response.py", line 184, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
```

**Comment by Tabrizian** [comment]
Are the server ports exposed properly? If you turn on `--log-verbose` for the server, does it print any logs when you're trying to send inference requests?

**Comment by songkq** [comment]
@Tabrizian 
As shown in the server log, the tritonserver was blocked at "Start to forward" untill client timeout.
```
Env:

Win10/Win11 wsl2
docker 24.0.7 
cuda 12.3
driver 545.36/546.01
GPU RTX3090/4090


I0111 08:07:22.906707 33655 libfastertransformer.cc:463] After Loading Weights:
after allocation    : free: 14.26 GB, total: 24.00 GB, used:  9.74 GB
W0111 08:07:22.906884 33655 libfastertransformer.cc:587] skipping model configuration auto-complete for 'base': not supported for fastertransformer backend
I0111 08:07:22.907495 33655 backend_model_instance.cc:68] Creating instance base_0 on CPU using artifact 'base'
I0111 08:07:22.907505 33655 libfastertransformer.cc:773] Model name base
I0111 08:07:22.907508 33655 libfastertransformer.cc:783] Use COUPLED (classic) API.
I0111 08:07:22.907513 33655 libfastertransformer.cc:877] Get batch input kind: BATCH_ITEM_SHAPE, target_name: input_ids_item_shape, data_type: TYPE_INT32, so
urce_input: input_ids
I0111 08:07:22.907520 33655 libfastertransformer.cc:932] Get input name: input_ids, type: TYPE_UINT32, shape: [-1], allow_ragged_batch: true
I0111 08:07:22.907523 33655 libfastertransformer.cc:932] Get input name: start_id, type: TYPE_UINT32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907526 33655 libfastertransformer.cc:932] Get input name: end_id, type: TYPE_UINT32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907528 33655 libfastertransformer.cc:932] Get input name: input_lengths, type: TYPE_UINT32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907530 33655 libfastertransformer.cc:932] Get input name: request_output_len, type: TYPE_UINT32, shape: [-1], allow_ragged_batch: false
I0111 08:07:22.907533 33655 libfastertransformer.cc:932] Get input name: runtime_top_k, type: TYPE_UINT32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907535 33655 libfastertransformer.cc:932] Get input name: runtime_top_p, type: TYPE_FP32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907537 33655 libfastertransformer.cc:932] Get input name: beam_search_diversity_rate, type: TYPE_FP32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907539 33655 libfastertransformer.cc:932] Get input name: temperature, type: TYPE_FP32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907541 33655 libfastertransformer.cc:932] Get input name: len_penalty, type: TYPE_FP32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907543 33655 libfastertransformer.cc:932] Get input name: repetition_penalty, type: TYPE_FP32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907545 33655 libfastertransformer.cc:932] Get input name: random_seed, type: TYPE_UINT64, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907548 33655 libfastertransformer.cc:932] Get input name: is_return_log_probs, type: TYPE_BOOL, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907550 33655 libfastertransformer.cc:932] Get input name: beam_width, type: TYPE_UINT32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907552 33655 libfastertransformer.cc:932] Get input name: bad_words_list, type: TYPE_INT32, shape: [2, -1], allow_ragged_batch: false
I0111 08:07:22.907554 33655 libfastertransformer.cc:932] Get input name: stop_words_list, type: TYPE_INT32, shape: [2, -1], allow_ragged_batch: false
I0111 08:07:22.907556 33655 libfastertransformer.cc:932] Get input name: prompt_learning_task_name_ids, type: TYPE_UINT32, shape: [1], allow_ragged_batch: fa
lse
I0111 08:07:22.907559 33655 libfastertransformer.cc:932] Get input name: top_p_decay, type: TYPE_FP32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907561 33655 libfastertransformer.cc:932] Get input name: top_p_min, type: TYPE_FP32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907563 33655 libfastertransformer.cc:932] Get input name: top_p_reset_ids, type: TYPE_UINT32, shape: [1], allow_ragged_batch: false
I0111 08:07:22.907567 33655 libfastertransformer.cc:976] Get output name: output_ids, type: TYPE_UINT32, shape: [-1, -1]
I0111 08:07:22.907569 33655 libfastertransformer.cc:976] Get output name: sequence_length, type: TYPE_UINT32, shape: [-1]
I0111 08:07:22.907574 33655 libfastertransformer.cc:976] Get output name: cum_log_probs, type: TYPE_FP32, shape: [-1]
I0111 08:07:22.907576 33655 libfastertransformer.cc:976] Get output name: output_log_probs, type: TYPE_FP32, shape: [-1, -1]
I0111 08:07:22.907695 33655 libfastertransformer.cc:487] Before Loading Model:
after allocation    : free: 14.26 GB, total: 24.00 GB, used:  9.74 GB
[WARNING] gemm_config.in is not found; using default GEMM algo
I0111 08:07:22.937789 33655 libfastertransformer.cc:504] After Loading Model:
after allocation    : free: 14.22 GB, total: 24.00 GB, used:  9.78 GB
I0111 08:07:22.937899 33655 libfastertransformer.cc:839] Model instance is created on GPU [ 0 ]
I0111 08:07:22.937915 33655 libfastertransformer.cc:1960] TRITONBACKEND_ModelInstanceInitialize: base_0 (count 1) (instance_id 0)
I0111 08:07:22.938024 33655 backend_model_instance.cc:800] Starting backend thread for base_0 at nice 0 on device 0...
I0111 08:07:22.938292 33655 model_lifecycle.cc:815] successfully loaded 'base'
I0111 08:07:22.938297 33655 dynamic_batch_scheduler.cc:292] Starting dynamic-batcher thread for base at nice 0...
I0111 08:07:22.938413 33655 server.cc:582]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0111 08:07:22.938454 33655 server.cc:609]
+-------------+-----------------------------------------------------------------+----------------------------------------------------------------------------
-----------------------------------------------------------------------------------+
| Backend     | Path                                                            | Config
                                                                                   |
+-------------+-----------------------------------------------------------------+----------------------------------------------------------------------------
-----------------------------------------------------------------------------------+
| qa_ensemble | /opt/tritonserver/backends/fastertransformer/libtriton_fastertransformer.so | {"cmdline":{"auto-complete-config":"true","backend-directory":"/opt/tritons
erver/backends","min-compute-capability":"6.000000","default-max-batch-size":"4"}} |
+-------------+-----------------------------------------------------------------+----------------------------------------------------------------------------
-----------------------------------------------------------------------------------+

I0111 08:07:22.938501 33655 server.cc:652]
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
| base  | 1       | READY  |
+-------+---------+--------+

I0111 08:07:23.026408 33655 metrics.cc:808] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3090
I0111 08:07:23.026577 33655 metrics.cc:701] Collecting CPU metrics
I0111 08:07:23.026711 33655 tritonserver.cc:2385]
+----------------------------------+-------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------+
| Option                           | Value
                                                                                        |
+----------------------------------+-------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------+
| server_id                        | triton
                                                                                        |
| server_version                   | 2.34.0
                                                                                        |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_
shared_memory cuda_shared_memory binary_tensor_data parameters statistics trace logging |
| model_repository_path[0]         | /model_repos/public
                                                                                        |
| model_control_mode               | MODE_NONE
                                                                                        |
| strict_model_config              | 0
                                                                                        |
| rate_limit                       | OFF
                                                                                        |
| pinned_memory_pool_byte_size     | 268435456
                                                                                        |
| cuda_memory_pool_byte_size{0}    | 67108864
                                                                                        |
| min_supported_compute_capability | 6.0
                                                                                        |
| strict_readiness                 | 1
                                                                                        |
| exit_timeout                     | 30
                                                                                        |
| cache_enabled                    | 0
                                                                                        |
+----------------------------------+-------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------+

I0111 08:07:23.027641 33655 grpc_server.cc:2344]
+----------------------------------------------+---------+
| GRPC KeepAlive Option                        | Value   |
+----------------------------------------------+---------+
| keepalive_time_ms                            | 7200000 |
| keepalive_timeout_ms                         | 20000   |
| keepalive_permit_without_calls               | 0       |
| http2_max_pings_without_data                 | 2       |
| http2_min_recv_ping_interval_without_data_ms | 300000  |
| http2_max_ping_strikes                       | 2       |
+----------------------------------------------+---------+

I0111 08:07:23.028585 33655 grpc_server.cc:128] Ready for RPC 'Check', 0
I0111 08:07:23.028605 33655 grpc_server.cc:128] Ready for RPC 'ServerLive', 0
I0111 08:07:23.028613 33655 grpc_server.cc:128] Ready for RPC 'ServerReady', 0
I0111 08:07:23.028616 33655 grpc_server.cc:128] Ready for RPC 'ModelReady', 0
I0111 08:07:23.028620 33655 grpc_server.cc:128] Ready for RPC 'ServerMetadata', 0
I0111 08:07:23.028632 33655 grpc_server.cc:128] Ready for RPC 'ModelMetadata', 0
I0111 08:07:23.028644 33655 grpc_server.cc:128] Ready for RPC 'ModelConfig', 0
I0111 08:07:23.028660 33655 grpc_server.cc:128] Ready for RPC 'SystemSharedMemoryStatus', 0
I0111 08:07:23.028675 33655 grpc_server.cc:128] Ready for RPC 'SystemSharedMemoryRegister', 0
I0111 08:07:23.028680 33655 grpc_server.cc:128] Ready for RPC 'SystemSharedMemoryUnregister', 0
I0111 08:07:23.028684 33655 grpc_server.cc:128] Ready for RPC 'CudaSharedMemoryStatus', 0
I0111 08:07:23.028687 33655 grpc_server.cc:128] Ready for RPC 'CudaSharedMemoryRegister', 0
I0111 08:07:23.028690 33655 grpc_server.cc:128] Ready for RPC 'CudaSharedMemoryUnregister', 0
I0111 08:07:23.028705 33655 grpc_server.cc:128] Ready for RPC 'RepositoryIndex', 0
I0111 08:07:23.028711 33655 grpc_server.cc:128] Ready for RPC 'RepositoryModelLoad', 0
I0111 08:07:23.028715 33655 grpc_server.cc:128] Ready for RPC 'RepositoryModelUnload', 0
I0111 08:07:23.028725 33655 grpc_server.cc:128] Ready for RPC 'ModelStatistics', 0
I0111 08:07:23.028736 33655 grpc_server.cc:128] Ready for RPC 'Trace', 0
I0111 08:07:23.028743 33655 grpc_server.cc:128] Ready for RPC 'Logging', 0
I0111 08:07:23.028759 33655 grpc_server.cc:377] Thread started for CommonHandler
I0111 08:07:23.028956 33655 infer_handler.cc:629] New request handler for ModelInferHandler, 0
I0111 08:07:23.028992 33655 infer_handler.h:1025] Thread started for ModelInferHandler
I0111 08:07:23.029032 33655 infer_handler.cc:629] New request handler for ModelInferHandler, 0
I0111 08:07:23.029050 33655 infer_handler.h:1025] Thread started for ModelInferHandler
I0111 08:07:23.029122 33655 stream_infer_handler.cc:122] New request handler for ModelStreamInferHandler, 0
I0111 08:07:23.029137 33655 infer_handler.h:1025] Thread started for ModelStreamInferHandler
I0111 08:07:23.029141 33655 grpc_server.cc:2450] Started GRPCInferenceService at 0.0.0.0:10001
I0111 08:07:23.029300 33655 http_server.cc:3555] Started HTTPService at 0.0.0.0:10000
I0111 08:07:23.070300 33655 http_server.cc:185] Started Metrics Service at 0.0.0.0:10002
I0111 08:11:53.881882 33655 http_server.cc:3449] HTTP request: 2 /v2/models/base/infer
I0111 08:11:53.882078 33655 infer_request.cc:751] [request id: rid_6000_33859] prepared: [0x0x7f9b14004630] request id: rid_6000_33859, model: base, requeste
d version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f9b14016208] input: repetition_penalty, type: FP32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015ff8] input: temperature, type: FP32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015de8] input: runtime_top_p, type: FP32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015bd8] input: runtime_top_k, type: UINT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b140159c8] input: end_id, type: UINT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b140157b8] input: start_id, type: UINT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015568] input: request_output_len, type: UINT32, original shape: [1,1], batch + shape: [1,1], shape: [1]
[0x0x7f9b14015358] input: input_lengths, type: UINT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015148] input: input_ids, type: UINT32, original shape: [1,667], batch + shape: [1,667], shape: [667]
[0x0x7f9b14014e68] input: random_seed, type: UINT64, original shape: [1,1], batch + shape: [1], shape: []
override inputs:
inputs:
[0x0x7f9b14014e68] input: random_seed, type: UINT64, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015148] input: input_ids, type: UINT32, original shape: [1,667], batch + shape: [1,667], shape: [667]
[0x0x7f9b14015358] input: input_lengths, type: UINT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015568] input: request_output_len, type: UINT32, original shape: [1,1], batch + shape: [1,1], shape: [1]
[0x0x7f9b140157b8] input: start_id, type: UINT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b140159c8] input: end_id, type: UINT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015bd8] input: runtime_top_k, type: UINT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015de8] input: runtime_top_p, type: FP32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14015ff8] input: temperature, type: FP32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f9b14016208] input: repetition_penalty, type: FP32, original shape: [1,1], batch + shape: [1], shape: []
original requested outputs:
requested outputs:
cum_log_probs
output_ids
output_log_probs
sequence_length

I0111 08:11:53.882235 33655 libfastertransformer.cc:2017] model base, instance base_0, executing 1 requests
I0111 08:11:53.882249 33655 libfastertransformer.cc:990] TRITONBACKEND_ModelExecute: Running base_0 with 1 requests
I0111 08:11:53.882267 33655 libfastertransformer.cc:1064] get total batch_size = 1
I0111 08:11:53.882282 33655 libfastertransformer.cc:1490] get input count = 10
I0111 08:11:53.882294 33655 libfastertransformer.cc:1734] collect name: random_seed size: 8 bytes
I0111 08:11:53.882298 33655 libfastertransformer.cc:1734] collect name: input_ids size: 2668 bytes
I0111 08:11:53.882302 33655 libfastertransformer.cc:1734] collect name: input_lengths size: 4 bytes
I0111 08:11:53.882305 33655 libfastertransformer.cc:1734] collect name: request_output_len size: 4 bytes
I0111 08:11:53.882309 33655 libfastertransformer.cc:1734] collect name: start_id size: 4 bytes
I0111 08:11:53.882311 33655 libfastertransformer.cc:1734] collect name: end_id size: 4 bytes
I0111 08:11:53.882320 33655 libfastertransformer.cc:1734] collect name: runtime_top_k size: 4 bytes
I0111 08:11:53.882325 33655 libfastertransformer.cc:1734] collect name: runtime_top_p size: 4 bytes
I0111 08:11:53.882328 33655 libfastertransformer.cc:1734] collect name: temperature size: 4 bytes
I0111 08:11:53.882331 33655 libfastertransformer.cc:1734] collect name: repetition_penalty size: 4 bytes
I0111 08:11:53.882333 33655 libfastertransformer.cc:1745] the data is in CPU
I0111 08:11:53.882335 33655 libfastertransformer.cc:1752] the data is in CPU
I0111 08:11:53.882355 33655 libfastertransformer.cc:1430] before ThreadForward 0
I0111 08:11:53.882410 33655 libfastertransformer.cc:1438] after ThreadForward 0
I0111 08:11:53.882440 33655 libfastertransformer.cc:1273] Start to forward
```

**Comment by Tabrizian** [comment]
Ah, I see. Faster transformer is not supported on Windows and is no longer maintained. I suggest looking into TRT-LLM backend and libraries to see if there are any offerings for Windows.

**Comment by songkq** [comment]
@Tabrizian Thanks. Unfortunately, TRT-LLM also has some issues in WSL2. https://github.com/NVIDIA/TensorRT-LLM/issues/886

**Comment by songkq** [comment]
@Tabrizian Solved by upgrading to Win11.
Maybe a bug in Win10. After upgrading to Win11 (Pro 23H2 22631.3007) or Win11(HOME 22H2 22621.3007) , everything is OK.
