### ISSUE TITLE
Triton request fails with "Failed to categorical encode column"

### ISSUE THREAD

**Issue by orlev2** [triton-inference-server/server#6798]
**Description**
Sending a request to a model hosted on Triton fails with "Failed to categorical encode column" error.
The model includes an nvt feature engineering component `0_transformworkflowtriton` and a pytorch model `1_predictpytorchtriton`. 

Full error: 
```
RuntimeError: Error: <class 'RuntimeError'> - Failed to categorical encode column action, Traceback: ['  
File "/tmp/folder9WnMku/1/model.py", line 117, in execute\n    transformed = self.runner.run_workflow(input_tensors)\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/systems/workflow/base.py", line 103, in run_workflow\n    transformed = LocalExecutor().transform(transformable, self.workflow.graph)\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 102, in transform\n    transformed_data = self._execute_node(node, transformable, capture_dtypes, strict)\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 116, in _execute_node\n    upstream_outputs = self._run_upstream_transforms(\n', '  File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 130, in _run_upstream_transforms\n    node_output = self._execute_node(\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 116, in _execute_node\n    upstream_outputs = self._run_upstream_transforms(\n', '  File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 130, in _run_upstream_transforms\n    node_output = self._execute_node(\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 116, in _execute_node\n    upstream_outputs = self._run_upstream_transforms(\n', '  File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 130, in _run_upstream_transforms\n    node_output = self._execute_node(\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 116, in _execute_node\n    upstream_outputs = self._run_upstream_transforms(\n', '  File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 130, in _run_upstream_transforms\n    node_output = self._execute_node(\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 116, in _execute_node\n    upstream_outputs = self._run_upstream_transforms(\n', '  File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 130, in _run_upstream_transforms\n    node_output = self._execute_node(\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 116, in _execute_node\n    upstream_outputs = self._run_upstream_transforms(\n', '  File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 130, in _run_upstream_transforms\n    node_output = self._execute_node(\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 122, in _execute_node\n    transform_output = self._run_node_transform(node, transform_input, capture_dtypes, strict)\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 250, in _run_node_transform\n    raise exc\n', '  File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/dag/executors.py", line 237, in _run_node_transform\n    transformed_data = node.op.transform(selection, input_data)\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/merlin/core/dispatch.py", line 69, in inner2\n    return func(*args, **kwargs)\n', '  
File "/tmp/python_env_cgBwOZ/0/lib/python3.10/site-packages/nvtabular/ops/categorify.py", line 482, in transform\n    raise RuntimeError(f"Failed to categorical encode column {name}") from e\n']
```

**Triton Information**
23.12-pyt-python-py3

Are you using the Triton container or did you build it yourself?
using Triton container

**To Reproduce**
```
docker run -t -p 8000:8000 --rm --shm-size=15g  -e AIP_MODE=True 
artifact-registry/nba-triton-2312/tritonserver:latest 
--model-repository=gs://project-id/bucket/path/to/model_artifacts_repository 
```

On vertex ai notebook: 
```
from merlin.systems import triton
import tritonclient.http as httpclient
import tritonhttpclient
from merlin.core.dispatch import get_lib
import nvtabular as nvt

workflow = nvt.Workflow.load('processed_nvt/workflow')
df_lib = get_lib()

batch = df_lib.read_parquet(
    'path/to/data_file.parquet', 
    columns=workflow.input_schema.column_names
)

inputs = triton.convert_df_to_triton_input(
    workflow.input_schema, 
    batch.iloc[:1000],
    httpclient.InferInput, 
)

output_cols = ['next-item', 'interaction_score/regression_task']

output_names = output_cols 
outputs = []
for col in output_names:
    outputs.append(httpclient.InferRequestedOutput(col))
    
MODEL_NAME_NVT = "nba_model"

with httpclient.InferenceServerClient(url="localhost:8000") as client:
    response = client.infer(model_name=MODEL_NAME_NVT, inputs=inputs, request_id="1", outputs=outputs) 
    # fails with error
```

```
workflow.transform(batch.iloc[:1000]) # results in transformed data output
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Ensemble:
```
ensemble/
├─0_transformworkflowtriton/
│ ├─1/
│ │ ├─model.py
│ │ └─workflow/
│ │   ├─categories/
│ │   │ ├─unique.action.parquet
│ │   │ ├─unique.campaign_category.parquet
│ │   │ ├─unique.device_category.parquet
│ │   │ ├─unique.event_page_type.parquet
│ │   │ ├─unique.item_family.parquet
│ │   │ ├─unique.item_hfb_name.parquet
│ │   │ ├─unique.item_pa_name.parquet
│ │   │ ├─unique.language.parquet
│ │   │ ├─unique.market_code.parquet
│ │   │ └─unique.marketing_channel.parquet
│ │   ├─metadata.json
│ │   └─workflow.pkl
│ └─config.pbtxt
├─1_predictpytorchtriton/
│ ├─1/
│ │ └─model.pt
│ └─config.pbtxt
├─executor_model/
│ └─1/
│   └─ensemble/
│     └─ensemble.pkl
└─nba_model/
  ├─1/
  │ ├─ensemble/
  │ │ ├─ensemble.pkl
  │ │ └─metadata.json
  │ └─model.py
  └─config.pbtxt
```

**Expected behavior**
Data in inference request to be transformed, and triton to return inference response

**Comment by orlev2** [comment]
ensemble config.pbtxt file:
```
name: "nba_model"
platform: "merlin_executor"
input {
  name: "epoch"
  data_type: TYPE_INT64
  dims: -1
}
input {
  name: "action"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "event_page_type"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "item_family"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "item_pa_name"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "item_hfb_name"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "page_content_group"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "marketing_channel"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "device_category"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "language"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "promotion_language"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "market_code"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "seconds_since_last_event"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "campaign_category"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "email_int_target"
  data_type: TYPE_INT64
  dims: -1
}
input {
  name: "bloom_0"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_1"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_2"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_3"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_4"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_5"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_6"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_7"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_8"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_9"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_10"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_11"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_12"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_13"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_14"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_15"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_16"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_17"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_18"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_19"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_20"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_21"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_22"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_23"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_24"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_25"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_26"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_27"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_28"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_29"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_30"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_31"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_32"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_33"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_34"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_35"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_36"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_37"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_38"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_39"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_40"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_41"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_42"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_43"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_44"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_45"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_46"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_47"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_48"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_49"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_50"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_51"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_52"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_53"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_54"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_55"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_56"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_57"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_58"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_59"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_60"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_61"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_62"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "bloom_63"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "promotion_id"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "customer_id"
  data_type: TYPE_STRING
  dims: -1
}
output {
  name: "next-item"
  data_type: TYPE_FP32
  dims: -1
  dims: 942
}
output {
  name: "interaction_score/regression_task"
  data_type: TYPE_FP32
  dims: -1
}
instance_group {
}
backend: "python"

parameters: {
key: "EXECUTION_ENV_PATH",
value: {string_value: "$$TRITON_MODEL_DIRECTORY/python3.10.tar.gz"}
}
```

**Comment by orlev2** [comment]
running the server with log-verbose 1 showed this error: 
```
Failed to transform operator <nvtabular.ops.categorify.Categorify object at 0x7f5b27a498a0>
Traceback (most recent call last):
  File "/tmp/python_env_WtQwiu/0/lib/python3.10/site-packages/nvtabular/ops/categorify.py", line 468, in transform
    na_sentinel=self.na_sentinel,
AttributeError: 'Categorify' object has no attribute 'na_sentinel'
```

Could be related to versions compatibility?

The workflow was created using nvtabular==23.8.0, ensemble was created using merlin-systems==23.8.0 
This is the code for creating the ensemble:
```
from merlin.systems.dag import Ensemble
import merlin.systems.dag.ops.pytorch as PredictPyTorch
import merlin.systems.dag.ops.workflow as TransformWorkflow

trasform_workflow = TransformWorkflow.TransformWorkflow(
        workflow,
        label_columns=["interaction_score"],
        max_batch_size=0
)

trasform_workflow.set_nvt_model_name(nvt_model_name=model_name)

pt_predict_workflow = PredictPyTorch.PredictPyTorch(
    traced_model, workflow.output_schema, model.output_schema
)

pipeline = workflow.input_schema.column_names >> trasform_workflow >> pt_predict_workflow

# export ensemble
ensemble = Ensemble(pipeline, workflow.input_schema)
ensemble.export(f"{ensemble_artifacts_repository}", name=model_name)
```

**Comment by rmccorm4** [comment]
Hi @orlev2, this looks like a versioning issue with the nvtabular package you're using in your model, not a specific Triton issue. I would double check the versions being used all around. The merlin or nvtabular teams may be able to help as well.

**Comment by orlev2** [comment]
It's been a while so I'm not sure anymore. I believe we fixed it by switching to a different version of the merlin-pytorch container for training the workflow and the model and exporting the ensemble to triton.
