### ISSUE TITLE
Text generation cURL/HTTP interface seems frozen for Llama2 running on TensorRT LLM backend

### ISSUE THREAD

**Issue by amir1m** [triton-inference-server/server#6821]
**Description**
I have FP16 Llama2 engine built for Tesnsor RT LLM.It works fine from the command line using run.py. However, when deployed/launched using Triton Server the HTTP end point doesn't resond.

**Triton Information**
2.41.0

Are you using the Triton container or did you build it yourself?
From NGC container

**To Reproduce**
1. Build Tensor RT LLM engine. This is a PEFT fine tuned Lllam2.
`python /tensorrtllm_backend/tensorrt_llm/examples/llama/build.py --model_dir /engines/llama --use_gpt_attention_plugin float16 --use_inflight_batching --paged_kv_cache --remove_input_padding --use_gemm_plugin float16 --output_dir /engines/llama/1-gpu/ --world_size 1
`

2. Deploy it with following configs in `tensorrt_llm/config.pbtxt`:
- max_batch_size: 64
- decoupled: False
- gpt_model_type: inflight_fused_batching
- max_attention_window_size: 2560
- batch_scheduler_policy: guaranteed_completion
- kv_cache_free_gpu_mem_fraction: 0.9
- enable_trt_overlap: 1

3. Model is launched successfully. /config and other end points work as expected.
I0122 09:48:46.347909 1180 grpc_server.cc:2495] Started GRPCInferenceService at 0.0.0.0:8001
I0122 09:48:46.348120 1180 http_server.cc:4619] Started HTTPService at 0.0.0.0:8000
I0122 09:48:46.388973 1180 http_server.cc:282] Started Metrics Service at 0.0.0.0:8002

4.  Try running generate using:
`curl -X POST localhost:8000/v2/models/ensemble/generate -d '{"text_input": "What is machine learning?", "max_tokens": 20, "bad_words": "", "stop_words": ""}'`

It just hangs with no response.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Mode deployed should respond to /generate end point.

**Comment by jbkyang-nvi** [comment]
How long did you wait, and just to clarify if using the client or just running the engine with [run.py](https://github.com/NVIDIA/TensorRT-LLM/blob/c89653021e66ca78c55f02b366f404455bc12e8d/examples/run.py) everything works ok? 
By the way, the official tutorial to follow is https://github.com/NVIDIA/TensorRT-LLM/tree/c89653021e66ca78c55f02b366f404455bc12e8d/examples/llama

**Comment by amir1m** [comment]
> How long did you wait, and just to clarify if using the client or just running the engine with [run.py](https://github.com/NVIDIA/TensorRT-LLM/blob/c89653021e66ca78c55f02b366f404455bc12e8d/examples/run.py) everything works ok?
> By the way, the official tutorial to follow is https://github.com/NVIDIA/TensorRT-LLM/tree/c89653021e66ca78c55f02b366f404455bc12e8d/examples/llama

Hi @jbkyang-nvi ,
I waited for many minutes, curl just keep waiting to show any response. Strangely, **run.py** is failing now

```
root@6a09950471c8:/opt/tritonserver# python3 /tensorrtllm_backend/tensorrt_llm/examples/run.py --engine_dir=/engines/llama/1-gpu/  --max_output_len 100 --tokenizer_dir /engines/llama/ --input_text "How do I count to ten in French?"
Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/run.py", line 388, in <module>
    main(args)
  File "/tensorrtllm_backend/tensorrt_llm/examples/run.py", line 330, in main
    runner = runner_cls.from_dir(**runner_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner.py", line 409, in from_dir
    session = session_cls(model_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 457, in __init__
    self.runtime = _Runtime(engine_buffer, mapping)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 150, in __init__
    self.__prepare(mapping, engine_buffer)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 170, in __prepare
    address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 99, in CUASSERT
    raise RuntimeError(
RuntimeError: CUDA ERROR: 2, error code reference: https://nvidia.github.io/cuda-python/module/cudart.html#cuda.cudart.cudaError_t
Exception ignored in: <function _Runtime.__del__ at 0x7f33b21daef0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 266, in __del__
    cudart.cudaFree(self.address)  # FIXME: cudaFree is None??
AttributeError: '_Runtime' object has no attribute 'address
```

**Comment by jbkyang-nvi** [comment]
The GPU size and the world size is correlated. If you build the engine with `WORLD_SIZE=1` it can't be run with 2 GPUs. 
Have you tried with [the triton client script](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/inflight_batcher_llm_client.py) and not through the generate endpoint? 
cc: @rmccorm4

**Comment by amir1m** [comment]
> The GPU size and the world size is correlated. If you build the engine with `WORLD_SIZE=1` it can't be run with 2 GPUs.

Yes. I rebuilt the engine with world size = 2 but run.py complained about the sizes not matching.

> Have you tried with [the triton client script](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/inflight_batcher_llm_client.py) and not through the generate endpoint?

Yes, same results - no resopone.

I am wondering if even the request is reaching the REST end point. how do we check? Logs are not much helpful but I can recheck if I know what to look for.

Thanks.

**Comment by rmccorm4** [comment]
Hi @amir1m,

> I am wondering if even the request is reaching the REST end point. how do we check? Logs are not much helpful but I can recheck if I know what to look for.

If you enable verbose logging (`tritonserver --log-verbose=1 ...`) on the server, you should see a log like this when any REST endpoint (ex: `/generate`) gets called:
```
I0124 20:41:38.070906 7 http_server.cc:4505] HTTP request: 2 /v2/models/gpt2/generate
...
<other verbose logs for inference>
```

**Comment by dyastremsky** [comment]
Closing issue due to inactivity. Please reopen if you would like to follow up with this issue.
