### ISSUE TITLE
Cannot use model-analyzer on ONNX classification model with dynamic input

### ISSUE THREAD

**Issue by ghost** [triton-inference-server/server#7184]
**•	RTX 3060**
**•	Docker nvcr.io/nvidia/tritonserver:24.04-py3-sdk**
**•	Cannot run model-analyzer on a model**

I am currently profiling several models with `model-analyzer`.

I can't manage to do this with one of my models and I'd like to have more information about the error encountered ...

Here is the error message: 

```
[Model Analyzer] Initializing GPUDevice handles
[Model Analyzer] Using GPU 0 NVIDIA GeForce RTX 3060 Laptop GPU with UUID GPU-87703e76-5ffe-5cde-d056-3c70fa64251a
[Model Analyzer] Starting a Triton Server using docker
[Model Analyzer] Loaded checkpoint from file /workspace/checkpoints/2.ckpt
[Model Analyzer] GPU devices match checkpoint - skipping server metric acquisition
[Model Analyzer] Starting a Triton Server using docker
[Model Analyzer] 
[Model Analyzer] Starting automatic brute search
[Model Analyzer] 
[Model Analyzer] Creating model config: age_config_default
[Model Analyzer] 
[Model Analyzer] Profiling age_config_default: client batch size=1, concurrency=1
[Model Analyzer] Running perf_analyzer failed with exit status 99:
error: Failed to init manager inputs: input input contains dynamic shape, provide shapes to send along with the request


[Model Analyzer] Saved checkpoint to /workspace/checkpoints/3.ckpt
[Model Analyzer] Creating model config: age_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer] 
[Model Analyzer] Profiling age_config_0: client batch size=1, concurrency=1
[Model Analyzer] Running perf_analyzer failed with exit status 99:
error: Failed to init manager inputs: input input contains dynamic shape, provide shapes to send along with the request


[Model Analyzer] No changes made to analyzer data, no checkpoint saved.
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/entrypoint.py", line 278, in main
    analyzer.profile(
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 124, in profile
    self._profile_models()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 242, in _profile_models
    self._model_manager.run_models(models=[model])
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/model_manager.py", line 145, in run_models
    self._stop_ma_if_no_valid_measurement_threshold_reached()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/model_manager.py", line 239, in _stop_ma_if_no_valid_measurement_threshold_reached
    raise TritonModelAnalyzerException(
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: The first 2 attempts to acquire measurements have failed. Please examine the Tritonserver/PA error logs to determine what has gone wrong.
```

Here ares the steps to reproduce:

Clone that repo and go to that directory:
https://github.com/triton-inference-server/model_analyzer

Start Triton container
`docker run -it --gpus all -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/examples/quick-start:$(pwd)/examples/quick-start --net=host nvcr.io/nvidia/tritonserver:24.04-py3-sdk` 

Add this folder in the model repository:
[age.zip|attachment](upload://oCwRSrtUdxZPukzfqhp8lR4cK4p.zip) (21.3 MB)

Run model analyis:
`model-analyzer profile --model-repository /YOUR_PATH/examples/quick-start/ --profile-models age --triton-launch-mode=docker --output-model-repository-path /opt/output_dir --export-path profile_results`

Thanks

**Comment by krishung5** [comment]
From the log it seems like the input shape needs to be specified:
```
error: Failed to init manager inputs: input input contains dynamic shape, provide shapes to send along with the request
```
I think you might need to specify the input shape as mentioned [here](https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#shape-input-data-and-streaming).

cc @debermudez for possible correction.

**Comment by debermudez** [comment]
@nv-braf @tgerdesnv

**Comment by siretru** [comment]
Yes I tried but I still have the same issue...
Could you please try to replicate and see what is causing the issue ? 
Here is the model  file: 
[Uploading age.zip…]()

Input is = tensor: float32[1,3,224,224]

**Comment by siretru** [comment]
[age.zip](https://github.com/triton-inference-server/server/files/15269289/age.zip)

**Comment by riyajatar37003** [comment]
i am also facing exact same issue, 

model-analyzer profile --run-config-profile-models-concurrently-enable --override-output-model-repository --model-repository model_repositories --profile-models model1\,model2 --output-model-repository-path ./model1_op --export-path model1_report


Model Analyzer] Initializing GPUDevice handles

[Model Analyzer] Using GPU 0 NVIDIA A100-SXM4-40GB with UUID GPU-d9a0447f-f8fa-9d2f-79fc-ecf2567dacc2

[Model Analyzer] WARNING: Overriding the output model repo path "./rerenker_output1"

[Model Analyzer] Starting a local Triton Server

[Model Analyzer] Loaded checkpoint from file /model_repositories/checkpoints/0.ckpt

[Model Analyzer] GPU devices match checkpoint - skipping server metric acquisition

[Model Analyzer]

[Model Analyzer] Starting quick mode search to find optimal configs

[Model Analyzer]

[Model Analyzer] Creating model config: reranker_config_default

[Model Analyzer]

[Model Analyzer] Creating model config: bge_reranker_v2_onnx_config_default

[Model Analyzer]

[Model Analyzer] Profiling reranker_config_default: client batch size=1, concurrency=24

[Model Analyzer] Profiling bge_reranker_v2_onnx_config_default: client batch size=1, concurrency=8

[Model Analyzer]

[Model Analyzer] perf_analyzer took very long to exit, killing perf_analyzer

[Model Analyzer] perf_analyzer did not produce any output.

[Model Analyzer] Saved checkpoint to model_repositories/checkpoints/1.ckpt

[Model Analyzer] Creating model config: reranker_config_0

[Model Analyzer] Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]

[Model Analyzer] Setting max_batch_size to 1

[Model Analyzer] Enabling dynamic_batching

[Model Analyzer]

[Model Analyzer] Creating model config: bge_reranker_v2_onnx_config_0

[Model Analyzer] Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]

[Model Analyzer] Setting max_batch_size to 1

[Model Analyzer] Enabling dynamic_batching

[Model Analyzer]

[Model Analyzer] Profiling reranker_config_0: client batch size=1, concurrency=2

[Model Analyzer] Profiling bge_reranker_v2_onnx_config_0: client batch size=1, concurrency=2

[Model Analyzer]

[Model Analyzer] perf_analyzer took very long to exit, killing perf_analyzer

[Model Analyzer] perf_analyzer did not produce any output.

[Model Analyzer] No changes made to analyzer data, no checkpoint saved.

Traceback (most recent call last):

File "/opt/app_venv/bin/model-analyzer", line 8, in

sys.exit(main())

File "/opt/app_venv/lib/python3.10/site-packages/model_analyzer/entrypoint.py", line 278, in main

analyzer.profile(

File "/opt/app_venv/lib/python3.10/site-packages/model_analyzer/analyzer.py", line 124, in profile

self._profile_models()

File "/opt/app_venv/lib/python3.10/site-packages/model_analyzer/analyzer.py", line 233, in _profile_models

self._model_manager.run_models(models=models)

File "/opt/app_venv/lib/python3.10/site-packages/model_analyzer/model_manager.py", line 145, in run_models

self._stop_ma_if_no_valid_measurement_threshold_reached()

File "/opt/app_venv/lib/python3.10/site-packages/model_analyzer/model_manager.py", line 239, in _stop_ma_if_no_valid_measurement_threshold_reached

raise TritonModelAnalyzerException(

model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: The first 2 attempts to acquire measurements have failed. Please examine the Tritonserver/PA error logs to determine what has gone wrong.

**Comment by dyastremsky** [comment]
Your command above does not specify the shape. Could you add a flag like `--shape input:1,3,224,224` or whatever is appropriate for your model?

If you already added the flag, can you provide the full command and new error you are running?

**Comment by siretru** [comment]
`root@trudemo-Inspiron-16-Plus-7620:/workspace# model-analyzer profile --model-repository /home/trudemo/Documents/repos/model_analyzer/examples/quick-start/ --profile-models age --triton-launch-mode=docker --output-model-repository-path /opt/output_dir --export-path profile_results --shape input:1,3,224,224
usage: model-analyzer [-h] [-q] [-v] [-m {online,offline}] [--version] {profile,analyze,report} ...
model-analyzer: error: unrecognized arguments: --shape input:1,3,224,224
`

**Comment by dyastremsky** [comment]
Could you try this actually? `--perf-analyzer-flags="--shape input:1,3,224,224"`

I haven't used MA in a while and did not realize that `--shape` is only for perf analyzer.

**Comment by siretru** [comment]
Don't think this can be used that way...
```
root@trudemo-Inspiron-16-Plus-7620:/workspace# model-analyzer profile --model-repository /home/trudemo/Documents/repos/model_analyzer/examples/quick-start/ --profile-models age --triton
-launch-mode=docker --output-model-repository-path /opt/output_dir --export-path profile_results --perf-analyzer-flags="--shape input:1,3,224,224"
usage: model-analyzer [-h] [-q] [-v] [-m {online,offline}] [--version] {profile,analyze,report} ...
model-analyzer: error: unrecognized arguments: --perf-analyzer-flags=--shape input:1,3,224,224
```

I think it might be more straightforward if you can replicate (I provided the model file)

Thanks

**Comment by dyastremsky** [comment]
Ah, it looked like that was a flag, but you can only [submit it via the config](https://github.com/triton-inference-server/model_analyzer/blob/ef12a857c526f25b49a18e0b3509502c4556a4c1/docs/config.md#variable-sized-dimensions), I believe. @nv-braf may know another way, but that looks to be what the documentation is suggesting for this exact use case. Please take a look at the documentation and see if following it resolves your dynamic input shape error.

**Comment by nv-braf** [comment]
`perf_analyzer_flags` must be specified via the config file
