### ISSUE TITLE
YOLOv8n-poses is giving me a negative output error

### ISSUE THREAD

**Issue by olooeez** [triton-inference-server/server#7278]
**Description**
I'm trying to run the YOLOv8n pose model (yolov8n-poses). When I make the inference using the YOLO class through Ultralytics, it gives me the following error:

```
Traceback (most recent call last):
  File "/home/luiz/dev/triton-model-management/main.py", line 24, in <module>
    main(args.model_name, args.image_path, args.output_path, args.method, args.port, args.server)
  File "/home/luiz/dev/triton-model-management/main.py", line 8, in main
    results = model.predict(image_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luiz/dev/triton-model-management/venv/lib/python3.12/site-packages/ultralytics/engine/model.py", line 453, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luiz/dev/triton-model-management/venv/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luiz/dev/triton-model-management/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/luiz/dev/triton-model-management/venv/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luiz/dev/triton-model-management/venv/lib/python3.12/site-packages/ultralytics/models/yolo/pose/predict.py", line 35, in postprocess
    preds = ops.non_max_suppression(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luiz/dev/triton-model-management/venv/lib/python3.12/site-packages/ultralytics/utils/ops.py", line 235, in non_max_suppression
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to create tensor with negative dimension -941: [0, -941]
```

**Triton Information**
* What version of Triton are you using?
I'm using Triton Server 21.10.

* Are you using the Triton container or did you build it yourself?
I'm using Triton container on Docker version 26.1.3.

**To Reproduce**
First, I placed the triton pose model converted to ONNX in the model repository, using the following command:

```python
model = YOLO("yolov8n-pose.pt")
model.export(format='onnx', opset=15)
```

Secondly, I create the model configuration below:

```
name: "yolov8n_pose"
platform: "onnxruntime_onnx"
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
![man-holding-mug-output](https://github.com/triton-inference-server/server/assets/94930726/e40d27b7-ba8c-4f11-b207-ef917178c478)

    dims: [1, 56, 8400]
  }
]
```

Thirdly, I upload the triton inference server and run my inference code below:

```python
model = YOLO(f"grpc://localhost:8001/yolov8n_pose", task="pose")

results = model.predict(image_path)

results[0].save(output_path)
```

**Expected behavior**
The expected result is that I could have run the inference code and generated an image annotated with the trackpoints, such as the image below that was generated by loading the torch file in the traditional way:

![man-holding-mug-output](https://github.com/triton-inference-server/server/assets/94930726/54547955-4ed8-4d9d-b934-339a4d92ae11)

**Comment by statiraju** [comment]
Can you please try it on the latest triton release?

**Comment by olooeez** [comment]
Got it working now. I created a new class to setup a model predictor with `kpt_shape` and `names` like the one bellow:

```python
from ultralytics import YOLO


class CustomYOLO(YOLO):
    def __init__(self, model="yolov8n.pt", task=None, verbose=False):
        super().__init__(model, task, verbose)

        if task == 'pose':
            var_names = {0: "person"}
            self.predictor = self._smart_load("predictor")(_callbacks=self.callbacks)
            self.predictor.setup_model(model=self.model, verbose=False)
            self.predictor.model.__dict__.update({"names": var_names, "kpt_shape": [17, 3]})

```

Then I imported it and ran without any errors:

```python
from custom_yolo import CustomYOLO as YOLO


model = YOLO(f"grpc://localhost:8001/yolov8n_pose", task="pose")

results = model.predict(image_path)

results[0].save(output_path)
```
