### ISSUE TITLE
Model Analyzer Fails to Connect to Triton Server ([StatusCode.UNAVAILABLE] failed to connect to all addresses)

### ISSUE THREAD

**Issue by goudemaoningsir** [triton-inference-server/server#7813]
I encountered an issue while using the model-analyzer tool with Triton Server. The profiler fails to connect to the server and raises the following exception:

`
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/entrypoint.py", line 278, in main
    analyzer.profile(
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 130, in profile
    self._get_server_only_metrics(client, gpus)
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 229, in _get_server_only_metrics
    client.wait_for_server_ready(
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/triton/client/client.py", line 72, in wait_for_server_ready
    raise TritonModelAnalyzerException(e)
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: Timeout occurred: FD Shutdown
`

`
model-analyzer profile \
  --model-repository=/mnt/models \
  --profile-models=densenet_onnx \
  --output-model-repository-path=results
`

**Comment by C-Dhayananthan** [comment]
@goudemaoningsir I'am facing same issue... did you get any solution

**Comment by rmccorm4** [comment]
CC @nv-braf @ganeshku1

**Comment by C-Dhayananthan** [comment]
@goudemaoningsir 
this is issue [https://github.com/triton-inference-server/model_analyzer/issues/950](https://github.com/triton-inference-server/model_analyzer/issues/950)
I'm following the same which has given in model-analyzer docs
