### ISSUE TITLE
Core was generated by /opt/tritonserver/backends/python/triton_python_backend_stub

### ISSUE THREAD

**Issue by powerpistn** [triton-inference-server/server#7875]
**Description**
Use Triton to load the model. After executing inference for a while, a core will appear. The information viewed by gdb is as follows
1）the stack information
`
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `/opt/tritonserver/backends/python/triton_python_backend_stub /workspace/models'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/361693' in core file.
#0  0x00007fcb71a70a84 in __new_sem_wait_slow64 (sem=0x7fcb717ed220, abstime=0x7ffde7f060a0, clockid=0) at ./nptl/sem_waitcommon.c:198
198     ./nptl/sem_waitcommon.c: No such file or directory.
[Current thread is 1 (Thread 0x7fcb72773000 (LWP 361693))]
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007fcb71a70a84 in __new_sem_wait_slow64 (sem=0x7fcb717ed220, abstime=0x7ffde7f060a0, clockid=0) at ./nptl/sem_waitcommon.c:198
#1  0x000055ed01d7d434 in triton::backend::python::Stub::PopMessage() ()
#2  0x000055ed01d91896 in triton::backend::python::Stub::RunCommand() ()
#3  0x000055ed01d5a170 in main ()
`

2）all threads

`
(gdb) info threads
  Id   Target Id                          Frame 
* 1    Thread 0x7fcb72773000 (LWP 361693) 0x00007fcb71a70a84 in __new_sem_wait_slow64 (sem=0x7fcb717ed220, abstime=0x7ffde7f060a0, clockid=0) at ./nptl/sem_waitcommon.c:198
  2    Thread 0x7fcb609f9000 (LWP 361796) warning: Unexpected size of section `.reg-xstate/361796' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c0e0 <thread_status+864>) at ./nptl/futex-internal.c:57
  3    Thread 0x7fcb714ec000 (LWP 361726) warning: Unexpected size of section `.reg-xstate/361726' in core file.
0x00007fcab2ab1b80 in c10::isIncludedInAlias(c10::DispatchKey, c10::DispatchKey)@plt () from /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so
  4    Thread 0x7fcb699ff000 (LWP 361790) warning: Unexpected size of section `.reg-xstate/361790' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4bde0 <thread_status+96>) at ./nptl/futex-internal.c:57
  5    Thread 0x7fcb621fc000 (LWP 361793) warning: Unexpected size of section `.reg-xstate/361793' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4bf60 <thread_status+480>) at ./nptl/futex-internal.c:57
  6    Thread 0x7fcb619fb000 (LWP 361794) warning: Unexpected size of section `.reg-xstate/361794' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4bfe0 <thread_status+608>) at ./nptl/futex-internal.c:57
  7    Thread 0x7fcb691fe000 (LWP 361791) warning: Unexpected size of section `.reg-xstate/361791' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4be60 <thread_status+224>) at ./nptl/futex-internal.c:57
  8    Thread 0x7fcb601f8000 (LWP 361797) warning: Unexpected size of section `.reg-xstate/361797' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c160 <thread_status+992>) at ./nptl/futex-internal.c:57
  9    Thread 0x7fcb5f9f7000 (LWP 361798) warning: Unexpected size of section `.reg-xstate/361798' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c1e0 <thread_status+1120>) at ./nptl/futex-internal.c:57
  10   Thread 0x7fcb649fd000 (LWP 361792) warning: Unexpected size of section `.reg-xstate/361792' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4bee0 <thread_status+352>) at ./nptl/futex-internal.c:57
  11   Thread 0x7fcb5f1f6000 (LWP 361799) warning: Unexpected size of section `.reg-xstate/361799' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c260 <thread_status+1248>) at ./nptl/futex-internal.c:57
  12   Thread 0x7fcb5d1f2000 (LWP 361803) warning: Unexpected size of section `.reg-xstate/361803' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c460 <thread_status+1760>) at ./nptl/futex-internal.c:57
  13   Thread 0x7fcb5c9f1000 (LWP 361804) warning: Unexpected size of section `.reg-xstate/361804' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c4e0 <thread_status+1888>) at ./nptl/futex-internal.c:57
  14   Thread 0x7fcb5d9f3000 (LWP 361802) warning: Unexpected size of section `.reg-xstate/361802' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c3e0 <thread_status+1632>) at ./nptl/futex-internal.c:57
  15   Thread 0x7fcb5b9ef000 (LWP 361806) warning: Unexpected size of section `.reg-xstate/361806' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c5e0 <thread_status+2144>) at ./nptl/futex-internal.c:57
  16   Thread 0x7fcb5e9f5000 (LWP 361800) warning: Unexpected size of section `.reg-xstate/361800' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c2e0 <thread_status+1376>) at ./nptl/futex-internal.c:57
  17   Thread 0x7fcb5c1f0000 (LWP 361805) warning: Unexpected size of section `.reg-xstate/361805' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c560 <thread_status+2016>) at ./nptl/futex-internal.c:57
  18   Thread 0x7fcb5a1ec000 (LWP 361809) warning: Unexpected size of section `.reg-xstate/361809' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c760 <thread_status+2528>) at ./nptl/futex-internal.c:57
  19   Thread 0x7fcb5e1f4000 (LWP 361801) warning: Unexpected size of section `.reg-xstate/361801' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c360 <thread_status+1504>) at ./nptl/futex-internal.c:57
  20   Thread 0x7fcb599eb000 (LWP 361810) warning: Unexpected size of section `.reg-xstate/361810' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c7e0 <thread_status+2656>) at ./nptl/futex-internal.c:57
  21   Thread 0x7fcb5a9ed000 (LWP 361808) warning: Unexpected size of section `.reg-xstate/361808' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c6e0 <thread_status+2400>) at ./nptl/futex-internal.c:57
  22   Thread 0x7fcb591ea000 (LWP 361811) warning: Unexpected size of section `.reg-xstate/361811' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c860 <thread_status+2784>) at ./nptl/futex-internal.c:57
  23   Thread 0x7fcb581e8000 (LWP 361813) warning: Unexpected size of section `.reg-xstate/361813' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c960 <thread_status+3040>) at ./nptl/futex-internal.c:57
  24   Thread 0x7fcb571e6000 (LWP 361815) warning: Unexpected size of section `.reg-xstate/361815' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4ca60 <thread_status+3296>) at ./nptl/futex-internal.c:57
  25   Thread 0x7fcb589e9000 (LWP 361812) warning: Unexpected size of section `.reg-xstate/361812' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c8e0 <thread_status+2912>) at ./nptl/futex-internal.c:57
  26   Thread 0x7fcb559e3000 (LWP 361818) warning: Unexpected size of section `.reg-xstate/361818' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cbe0 <thread_status+3680>) at ./nptl/futex-internal.c:57
  27   Thread 0x7fcb579e7000 (LWP 361814) warning: Unexpected size of section `.reg-xstate/361814' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c9e0 <thread_status+3168>) at ./nptl/futex-internal.c:57
  28   Thread 0x7fcb561e4000 (LWP 361817) warning: Unexpected size of section `.reg-xstate/361817' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cb60 <thread_status+3552>) at ./nptl/futex-internal.c:57
  29   Thread 0x7fcb569e5000 (LWP 361816) warning: Unexpected size of section `.reg-xstate/361816' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cae0 <thread_status+3424>) at ./nptl/futex-internal.c:57
  30   Thread 0x7fcb549e1000 (LWP 361820) warning: Unexpected size of section `.reg-xstate/361820' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cce0 <thread_status+3936>) at ./nptl/futex-internal.c:57
  31   Thread 0x7fcb541e0000 (LWP 361821) warning: Unexpected size of section `.reg-xstate/361821' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cd60 <thread_status+4064>) at ./nptl/futex-internal.c:57
  32   Thread 0x7fcb539df000 (LWP 361822) warning: Unexpected size of section `.reg-xstate/361822' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cde0 <thread_status+4192>) at ./nptl/futex-internal.c:57
  33   Thread 0x7fcb519db000 (LWP 361826) warning: Unexpected size of section `.reg-xstate/361826' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cfe0 <thread_status+4704>) at ./nptl/futex-internal.c:57
  34   Thread 0x7fcb521dc000 (LWP 361825) warning: Unexpected size of section `.reg-xstate/361825' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cf60 <thread_status+4576>) at ./nptl/futex-internal.c:57
  35   Thread 0x7fcb4f1d6000 (LWP 361831) warning: Unexpected size of section `.reg-xstate/361831' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d260 <thread_status+5344>) at ./nptl/futex-internal.c:57
  36   Thread 0x7fcb4c1d4000 (LWP 361833) warning: Unexpected size of section `.reg-xstate/361833' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d360 <thread_status+5600>) at ./nptl/futex-internal.c:57
  37   Thread 0x7fcb4f9d7000 (LWP 361830) warning: Unexpected size of section `.reg-xstate/361830' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d1e0 <thread_status+5216>) at ./nptl/futex-internal.c:57
  38   Thread 0x7fcb479d3000 (LWP 361834) warning: Unexpected size of section `.reg-xstate/361834' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d3e0 <thread_status+5728>) at ./nptl/futex-internal.c:57
  39   Thread 0x7fcb4c9d5000 (LWP 361832) warning: Unexpected size of section `.reg-xstate/361832' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d2e0 <thread_status+5472>) at ./nptl/futex-internal.c:57
  40   Thread 0x7fcb501d8000 (LWP 361829) warning: Unexpected size of section `.reg-xstate/361829' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d160 <thread_status+5088>) at ./nptl/futex-internal.c:57
  41   Thread 0x7fcb5b1ee000 (LWP 361807) warning: Unexpected size of section `.reg-xstate/361807' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c660 <thread_status+2272>) at ./nptl/futex-internal.c:57
  42   Thread 0x7fcb551e2000 (LWP 361819) warning: Unexpected size of section `.reg-xstate/361819' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cc60 <thread_status+3808>) at ./nptl/futex-internal.c:57
  43   Thread 0x7fcb451d2000 (LWP 361835) warning: Unexpected size of section `.reg-xstate/361835' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d460 <thread_status+5856>) at ./nptl/futex-internal.c:57
  44   Thread 0x7fcb529dd000 (LWP 361824) warning: Unexpected size of section `.reg-xstate/361824' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4cee0 <thread_status+4448>) at ./nptl/futex-internal.c:57
  45   Thread 0x7fcb511da000 (LWP 361827) warning: Unexpected size of section `.reg-xstate/361827' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d060 <thread_status+4832>) at ./nptl/futex-internal.c:57
  46   Thread 0x7fcb509d9000 (LWP 361828) warning: Unexpected size of section `.reg-xstate/361828' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d0e0 <thread_status+4960>) at ./nptl/futex-internal.c:57
  47   Thread 0x7fcb611fa000 (LWP 361795) warning: Unexpected size of section `.reg-xstate/361795' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4c060 <thread_status+736>) at ./nptl/futex-internal.c:57
  48   Thread 0x7fcb531de000 (LWP 361823) warning: Unexpected size of section `.reg-xstate/361823' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4ce60 <thread_status+4320>) at ./nptl/futex-internal.c:57
  49   Thread 0x7fcb209c1000 (LWP 361852) warning: Unexpected size of section `.reg-xstate/361852' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4dce0 <thread_status+8032>) at ./nptl/futex-internal.c:57
  50   Thread 0x7fca1887a000 (LWP 429458) warning: Unexpected size of section `.reg-xstate/429458' in core file.
0x00007fcb71aecbcf in __GI___poll (fds=0x7fcb6c000b70, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  51   Thread 0x7fcb2e9c5000 (LWP 361848) warning: Unexpected size of section `.reg-xstate/361848' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4dae0 <thread_status+7520>) at ./nptl/futex-internal.c:57
  52   Thread 0x7fcb3a1c8000 (LWP 361845) warning: Unexpected size of section `.reg-xstate/361845' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d960 <thread_status+7136>) at ./nptl/futex-internal.c:57
  53   Thread 0x7fcb3f1ce000 (LWP 361839) warning: Unexpected size of section `.reg-xstate/361839' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d660 <thread_status+6368>) at ./nptl/futex-internal.c:57
  54   Thread 0x7fcb2f1c6000 (LWP 361847) warning: Unexpected size of section `.reg-xstate/361847' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4da60 <thread_status+7392>) at ./nptl/futex-internal.c:57
  55   Thread 0x7fcb3d9cb000 (LWP 361842) warning: Unexpected size of section `.reg-xstate/361842' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d7e0 <thread_status+6752>) at ./nptl/futex-internal.c:57
  56   Thread 0x7fcb419cf000 (LWP 361838) warning: Unexpected size of section `.reg-xstate/361838' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d5e0 <thread_status+6240>) at ./nptl/futex-internal.c:57
  57   Thread 0x7fcb3e1cc000 (LWP 361841) warning: Unexpected size of section `.reg-xstate/361841' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d760 <thread_status+6624>) at ./nptl/futex-internal.c:57
  58   Thread 0x7fcb429d1000 (LWP 361836) warning: Unexpected size of section `.reg-xstate/361836' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d4e0 <thread_status+5984>) at ./nptl/futex-internal.c:57
  59   Thread 0x7fcb339c7000 (LWP 361846) warning: Unexpected size of section `.reg-xstate/361846' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d9e0 <thread_status+7264>) at ./nptl/futex-internal.c:57
  60   Thread 0x7fcb3d1ca000 (LWP 361843) warning: Unexpected size of section `.reg-xstate/361843' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d860 <thread_status+6880>) at ./nptl/futex-internal.c:57
  61   Thread 0x7fcb3c9c9000 (LWP 361844) warning: Unexpected size of section `.reg-xstate/361844' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d8e0 <thread_status+7008>) at ./nptl/futex-internal.c:57
--Type <RET> for more, q to quit, c to continue without paging--
  62   Thread 0x7fcb2a1c4000 (LWP 361849) warning: Unexpected size of section `.reg-xstate/361849' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4db60 <thread_status+7648>) at ./nptl/futex-internal.c:57
  63   Thread 0x7fcb421d0000 (LWP 361837) warning: Unexpected size of section `.reg-xstate/361837' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d560 <thread_status+6112>) at ./nptl/futex-internal.c:57
  64   Thread 0x7fcb3e9cd000 (LWP 361840) warning: Unexpected size of section `.reg-xstate/361840' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4d6e0 <thread_status+6496>) at ./nptl/futex-internal.c:57
  65   Thread 0x7fcb271c2000 (LWP 361851) warning: Unexpected size of section `.reg-xstate/361851' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4dc60 <thread_status+7904>) at ./nptl/futex-internal.c:57
  66   Thread 0x7fcb279c3000 (LWP 361850) warning: Unexpected size of section `.reg-xstate/361850' in core file.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fcb6bf4dbe0 <thread_status+7776>) at ./nptl/futex-internal.c:57
(gdb) 
(gdb) 
`

**Triton Information**
All projects are recompiled, using the 24.05 branch.
Official mirror nvcr.io/nvidia/tritonserver:24.05-py3

**Expected behavior**
The inference service can run stably, but sometimes crashes suddenly

When executing the inference service, use top to get the following information
`
top - 03:03:57 up 104 days, 14:15,  0 users,  load average: 8.64, 4.02, 4.95
Tasks:  34 total,   2 running,  26 sleeping,   5 stopped,   1 zombie
%Cpu(s):  5.7 us, 13.6 sy,  0.0 ni, 80.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 1031739.+total, 276389.6 free, 116346.1 used, 639003.8 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 891398.5 avail Mem 

    PID USER      PR  NI    VIRT       RES        SHR     S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                       
 431649 root      20   0   17.5g   629696   332664 S  1043   0.1 272:37.31 pt_main_thread                                                                                                                                                
 441526 root      20   0   14.9g     4.7g       298460 R  99.3   0.5   0:20.58 pt_main_thread                                                                                                                                                
 429536 root      20   0 4163.9g   4.9g         1.2g    S   9.3   0.5   4:13.75 tritonserver                                                                                                                                                      
      1       root      20   0    1104       4               0       S   0.0   0.0   0:04.99 docker-init                                                                                                                                                   
      7       root      20   0    4616   3824         3260 S   0.0   0.0   0:00.01 bash                                                                                                                                                          
    138    root      20   0    4616   3952          3308 S   0.0   0.0   0:00.03 bash                                                                                                                                                          
   3589  root      20   0    4740   3912          3252 S   0.0   0.0   0:00.04 bash                                                                                                                                                          
 101529 root      20   0    4616   3920         3268 S   0.0   0.0   0:00.03 bash                                                                                                                                                          
 101573 root      20   0    2820   1120           1024 T   0.0   0.0   0:00.00 tail                                                                                                                                                          
 104941 root      20   0    4740   3868        3208 S   0.0   0.0   0:00.04 bash                                                                                                                                                          
 122287 root      20   0    2820   1032         936 T   0.0   0.0   0:00.00 tail     
`
the information of cpu
`
lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  96
  On-line CPU(s) list:   0-95
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Gold 5318Y CPU @ 2.10GHz
    CPU family:          6
    Model:               106
    Thread(s) per core:  2
    Core(s) per socket:  24
    Socket(s):           2
    Stepping:            6
    BogoMIPS:            4200.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xt
                         opology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_
                         lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_
                         a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm id
                         a arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   2.3 MiB (48 instances)
  L1i:                   1.5 MiB (48 instances)
  L2:                    60 MiB (48 instances)
  L3:                    72 MiB (2 instances)
NUMA:                    
  NUMA node(s):          4
  NUMA node0 CPU(s):     0-11,48-59
  NUMA node1 CPU(s):     12-23,60-71
  NUMA node2 CPU(s):     24-35,72-83
  NUMA node3 CPU(s):     36-47,84-95
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
`
I want to know why a core appears after running for a while, and the gdb information shows that all threads are waiting.
There are multiple models running on the server at the same time. Is it because of resource problems that cause timeouts?

**Comment by rmccorm4** [comment]
Hi @powerpistn, can you reproduce this on the latest 24.12 version? If so, can you share step-by-step reproduction steps and `model.py` for 24.12?
